#!/usr/bin/env python

import os
import sys
import sqlite3
import random

cwd    = os.path.dirname(os.path.abspath(__file__))
pyfarm = os.path.abspath(os.path.join(cwd, "..", ".."))
db     = os.path.join(pyfarm, "PyFarmDB.sql")

script = ""
total  = 50
if len(sys.argv) > 1:
    total = int(sys.argv[1])

for i in range(total):
    host = "host%i" % i
    ip   = "192.168.%i.%i" % (random.randint(1, 255), random.randint(1, 255))
    stat = random.randint(0, 5)

    script+= "INSERT INTO hosts values('%s', '%s', 'None', %i,0,0,0,0,0,0,0);" % (host, ip, stat)

if os.path.isfile(db):
    os.remove(db)

try:
    conn = sqlite3.connect(db)
    c    = conn.cursor()
    conn.executescript(script)
    c.close()

except sqlite3.OperationalError:
    reset = os.path.join(pyfarm, "lib", "db", "base", "SQLGeneral.py")
    os.system("python %s" % reset)
    conn = sqlite3.connect(db)
    c    = conn.cursor()
    conn.executescript(script)
    c.close()
