language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"

install:
  - pip install . --use-mirrors
  - pip install -r requirements.txt --use-mirrors

script: ./dev/bin/travis-ci/build.sh

env:
  - DB=postgres
  - DB=mysql

before_script: ./dev/bin/travis-ci/before_script.sh
after_script: ./dev/bin/travis-ci/after_script.sh