language: python
python:
  - "2.5"
  - "2.6"
  - "2.7"

env:
  - DB=postgres
  - DB=mysql
  - DB=sqlite
  - BUILD_DOCS=true

install: dev/travis-ci/install.sh
script: dev/travis-ci/build.sh

after_success:
  coveralls