#!/usr/bin/env python26
#
# INITIAL: June 29 2011
# PURPOSE: To provide a simple and general means to 'build' and run
#          parts or sections of PyFarm
#
# This file is part of PyFarm.
# Copyright (C) 2008-2011 Oliver Palmer
#
# PyFarm is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PyFarm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PyFarm.  If not, see <http://www.gnu.org/licenses/>.

import os
import inspect
import tempfile
import subprocess

from dev.lib import pmake

def clean():
    '''Cleanup temp files'''
    pass

def test():
    '''Run test code'''
    pass

def designer(clean, test):
    '''Run Qt designer with the environment necessary for custom widgets'''
    #cmd = Command()
    print "designer call"


if __name__ == '__main__':
    methods = pmake.methods(inspect.currentframe())
    args = pmake.parseInput(methods)

    # iterate over all input arguments and ensure the method being called
    # exists
    for arg in args:
        if arg not in methods.keys():
            pmake.HelpString.noSuchCall(arg)

        pmake.command.execute(methods[arg], methods)