# Copyright 2013 Oliver Palmer
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#    http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# path(s) to search for jobtypes
search-paths:
  - $pyfarm/lib/python/pyfarm/jobtypes
  - $root/pyfarm/jobtypes

# The path(s) to search for executable files. All environment
# variables as well as some template variables will
# be run through os.path.expandvars
path:
  - $root/bin
  - $PATH

# possible extensions that the command could have (platform dependent)
extensions:
  common:
    - py
    - pyc

  windows: [bat, cmd, exe]
  linux: [sh, csh, tcsh]
  mac: [app, sh, csh]

# Maps jobtypes to specific module names.  If
# a mapping is not provided for a specific jobtype then
# it's assumed a jobtype with the same name as the jobtype
# exists.
mappings: {}

# default values to insert into the jobs table if none
# are specified when submitting the job
defaults:
  requeue-failed: true
  requeue-max: 5
