<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_topic_3 {

 var $ipsclass;
//===========================================================================
// <ips:announcement_show:desc::trigger:>
//===========================================================================
function announcement_show($announce="",$author="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['announce_title']}: {$announce['announce_title']}</div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td valign=\"middle\" class=\"post_head\" width=\"1%\">
				<a name=\"entry{$post['pid']}\"></a>
				" . (($author['id']) ? ("
					<div id=\"post-member-{$announce['announce_member_id']}\" class='popmenubutton-new-out'>
						<span class=\"normalname\">{$author['_pp_online_image']}<a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\">{$author['_members_display_name']}</a></span>
					</div>
					<!-- member menu -->
					<div class='popupmenu-new' id='post-member-{$announce['announce_member_id']}_menu' style='display:none;width:230px'>
						<div class='popupmenu-item-last'>
							" . (($author['members_display_name_short'] != $author['members_display_name']) ? ("
								<div class='popupmenu-item'><strong>{$author['members_display_name']}</strong></div>
							") : ("")) . "
							<div style='float:right'>
								<div class='pp-image-thumb-wrap'>
									<img src='{$author['pp_thumb_photo']}' width='{$author['pp_thumb_width']}' height='{$author['pp_thumb_height']}' alt='' />
								</div>
								" . (($this->ipsclass->vars['pp_allow_member_rate']) ? ("
									<div style='margin-top:5px;margin-left:6px;'>
										<img src=\"{$this->ipsclass->vars['img_url']}/rating_{$author['_pp_rating_real']}_mini.gif\" alt='{$this->ipsclass->lang['rating_prefix']}: {$author['_pp_rating_real']}' style='vertical-align:middle' border='0' />
									</div>
								") : ("")) . "
							</div>
							<div class='popupmenu-item'>
								{$author['_pp_gender_image']} <a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\">{$this->ipsclass->lang['dd_view_profile']}</a>
							</div>
							" . (($this->ipsclass->member['id']) ? ("
								<div class='popupmenu-item'>
									" . ((in_array( $author['id'], array_keys( $this->ipsclass->member['_cache']['friends'] ) )) ? ("
										<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_remove_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=remove&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['dd_remove_friend']}</a>
									") : ("
										<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_add_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=add&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['dd_add_friend']}</a>
									")) . "
								</div>
								<div class='popupmenu-item'>
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/send_pm_small.png' alt='' border='0' /> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=4&amp;MID={$author['id']}\">{$this->ipsclass->lang['dd_send_pm']}</a>
								</div>
								<div class='popupmenu-item'>
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=gettopicsuser&amp;mid={$author['id']}'>{$this->ipsclass->lang['dd_find_topics']}</a>
								</div>								
							") : ("")) . "
							<div class='popupmenu-item-last'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=getalluser&amp;mid={$author['id']}'>{$this->ipsclass->lang['dd_find_posts']}</a>
							</div>
						</div>
					</div>
					<!-- member menu -->
					<script type=\"text/javascript\">
						ipsmenu.register( \"post-member-{$announce['announce_member_id']}\", '', 'popmenubutton-new', 'popmenubutton-new-out' );
					</script>
				") : ("
					<span class=\"normalname\">{$author['_members_display_name']}</span>
				")) . "
				
			</td>
			<td class=\"post_head\" valign=\"middle\" width=\"99%\">
				<!-- POSTED DATE DIV -->
				<div align='left'>
					<span class=\"postdetails\"><b>{$announce['announce_title']}</b>&nbsp; {$announce['running_date']}</span>
				</div>
			</td>
		</tr>
		<tr>
			<td valign=\"top\" class=\"post1 post_left\">
	        	<span class=\"postdetails\">
					" . (($author['id'] AND $author['avatar']) ? ("
						<a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\" title=\"{$this->ipsclass->lang['dd_view_profile']}\">{$author['avatar']}</a><br /><br />
					") : ("
	        			{$author['avatar']}<br /><br />
					")) . "
	        		{$author['title']}<br />
	        		{$author['member_rank_img']}<br /><br />
	        		{$author['member_group']}<br />
	        		{$author['member_posts']}<br />
	        		{$author['member_joined']}<br />
	        		{$author['member_location']}
	        		{$author['member_number']}<br />
					" . (($author['custom_fields'] != "") ? ("
						{$author['custom_fields']}
					") : ("")) . "
					<br />
	        		{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
	        	</span><br />
	        	<img src=\"{$this->ipsclass->vars['img_url']}/spacer.gif\" alt=\"\" width=\"160\" height=\"1\" /><br /> 
	       </td>
	       <td width=\"100%\" valign=\"top\" class=\"post1\">
				<div class=\"postcolor\">
					{$announce['announce_post']}
				</div>
			</td>
		</tr>
		<tr>
			<td class=\"formbuttonrow\" nowrap=\"nowrap\">
				<div style='text-align:left'><a href=\"javascript:scroll(0,0);\"><{P_UP}></a>{$post['report_link']}</div>
			</td>
			<td class=\"formbuttonrow\" nowrap=\"nowrap\">
	         	<div align=\"right\">
	         		&nbsp;
	         	</div>
	         </td>
		</tr><tr>
		<td class=\"catend\" colspan=\"2\">
		<!-- no content -->
		</td>
	</tr>
	</table>

</div>
<script type=\"text/javascript\" src=\"jscripts/ipb_topic.js\"></script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_delete:desc::trigger:>
//===========================================================================
function button_delete($fid="",$tid="",$pid="",$key="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:delete_post('{$this->ipsclass->base_url}act=Mod&amp;CODE=04&amp;f={$fid}&amp;t={$tid}&amp;p={$pid}&amp;st={$this->ipsclass->input['st']}&amp;auth_key=$key')\"><{P_DELETE}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_edit:desc::trigger:>
//===========================================================================
function button_edit($fid="",$tid="",$pid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a id='edit-but-{$pid}' href=\"{$this->ipsclass->base_url}act=post&amp;do=edit_post&amp;f={$fid}&amp;t={$tid}&amp;p={$pid}&amp;st={$this->ipsclass->input['st']}\"><{P_EDIT}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_posting:desc::trigger:>
//===========================================================================
function button_posting($url="",$macro="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"$url\">$macro</a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:edited_by:desc::trigger:>
//===========================================================================
function edited_by($text="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br /><br /><span class='edit'>{$text}</span>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:golastpost_link:desc::trigger:>
//===========================================================================
function golastpost_link($fid="",$tid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--
	( <a href=\"{$this->ipsclass->base_url}act=ST&amp;f=$fid&amp;t=$tid&amp;view=getnewpost\">{$this->ipsclass->lang['go_new_post']}</a> )
-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ip_admin_hide:desc::trigger:>
//===========================================================================
function ip_admin_hide() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<i>{$this->ipsclass->lang['ip_private']}</i>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ip_admin_show:desc::trigger:>
//===========================================================================
function ip_admin_show($ip="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=usercp&amp;CODE=iptool&amp;ip={$ip}\" target=\"_blank\">{$ip}</a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:ip_show:desc::trigger:>
//===========================================================================
function ip_show($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['ip']}: $data &#0124;";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_group:desc::trigger:>
//===========================================================================
function member_group($title="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_group']} $title";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_email:desc::trigger:>
//===========================================================================
function member_icon_email($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=Mail&amp;CODE=00&amp;MID={$id}\"><{P_EMAIL}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_msg:desc::trigger:>
//===========================================================================
function member_icon_msg($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=04&amp;MID={$id}\"><{P_MSG}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_profile:desc::trigger:>
//===========================================================================
function member_icon_profile($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}showuser={$id}\"><{P_PROFILE}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_vcard:desc::trigger:>
//===========================================================================
function member_icon_vcard($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=Profile&amp;CODE=showcard&amp;MID={$id}','AddressCard','600','300','0','1','1','1')\" title=\"{$this->ipsclass->lang['ac_title']}\"><{P_CARD}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_joined:desc::trigger:>
//===========================================================================
function member_joined($date="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_joined']} $date";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_location:desc::trigger:>
//===========================================================================
function member_location($location="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_location']} $location<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_number:desc::trigger:>
//===========================================================================
function member_number($number="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['member_no']} $number";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_posts:desc::trigger:>
//===========================================================================
function member_posts($posts="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_posts']} $posts";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_rank_img:desc::trigger:>
//===========================================================================
function member_rank_img($filename="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"$filename\" alt=\"{$this->ipsclass->lang['group_icon']}\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mm_end:desc::trigger:>
//===========================================================================
function mm_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</select>&nbsp;
		<input type=\"submit\" value=\"{$this->ipsclass->lang['mm_submit']}\" class=\"button\" />
	</form>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mm_entry:desc::trigger:>
//===========================================================================
function mm_entry($id="",$name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<option value=\"$id\">$name</option>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mm_start:desc::trigger:>
//===========================================================================
function mm_start($tid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div style=\"float: left;\">
	<form action=\"{$this->ipsclass->base_url}act=mmod&amp;t=$tid\" method=\"post\">
	<input type=\"hidden\" name=\"check\" value=\"1\" />
		<select name=\"mm_id\" class=\"dropdown\">
			<option value=\"-1\">{$this->ipsclass->lang['mm_title']}</option>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Mod_Panel:desc::trigger:>
//===========================================================================
function Mod_Panel($data="",$fid="",$tid="",$key="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "" . (($this->ipsclass->member['is_mod'] != 1) ? ("
<div class=\"borderwrap\">
	<div class=\"bar\" style=\"padding: 5px;\">
") : ("")) . "
		<div>
			<form method=\"post\" name=\"modform2\" action=\"{$this->ipsclass->base_url}\">
			<input type=\"hidden\" name=\"t\" value=\"$tid\" />
			<input type=\"hidden\" name=\"f\" value=\"$fid\" />
			<input type=\"hidden\" name=\"st\" value=\"{$this->ipsclass->input['st']}\" />
			<input type=\"hidden\" name=\"auth_key\" value=\"$key\" />
			<input type=\"hidden\" name=\"act\" value=\"Mod\" />
				<select name=\"CODE\" class=\"dropdown\">
					<option value=\"-1\">{$this->ipsclass->lang['moderation_ops']}</option>
					$data
				</select>&nbsp;
				<input type=\"submit\" value=\"{$this->ipsclass->lang['jmp_go']}\" class=\"button\" />
			</form>
		</div>
" . (($this->ipsclass->member['is_mod'] != 1) ? ("
	 </div>
</div>
") : ("")) . "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_panel_wrapper:desc::trigger:>
//===========================================================================
function mod_panel_wrapper($data=array(),$auth_key="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "" . (($this->ipsclass->member['is_mod']) ? ("
<div class=\"borderwrap\">
	<div class=\"bar\" style=\"padding: 5px;\">
		<div style=\"float: right; text-align: right;\">
	 		<form name=\"modform\" method=\"post\" action=\"{$this->ipsclass->base_url}\" onsubmit=\"return checkdelete();\">
	 			<input type=\"hidden\" name=\"act\" value=\"mod\" />
	 			<input type=\"hidden\" name=\"CODE\" value=\"postchoice\" />
	 			<input type=\"hidden\" name=\"f\" value=\"{$data['TOPIC']['forum_id']}\" />
	 			<input type=\"hidden\" name=\"t\" value=\"{$data['TOPIC']['tid']}\" />
	 			<input type=\"hidden\" name=\"auth_key\" value=\"{$auth_key}\" />
	 			<input type=\"hidden\" name=\"st\" value=\"{$this->ipsclass->input['st']}\" />
	 			<input type=\"hidden\" value=\"{$this->ipsclass->input['selectedpids']}\" name=\"selectedpids\" />
	 			<select name=\"tact\">
	 				<option value=\"merge\">{$this->ipsclass->lang['cpt_merge']}</option>
	 				<option value=\"move\">{$this->ipsclass->lang['cpt_move']}</option>
	 				<option value=\"delete\">{$this->ipsclass->lang['cpt_delete']}</option>
	 				<option value=\"split\">{$this->ipsclass->lang['cpt_split']}</option>
	 				<option value=\"approve\">{$this->ipsclass->lang['cpt_approve']}</option>
	 				<option value=\"unapprove\">{$this->ipsclass->lang['cpt_unapprove']}</option>
	 			</select>&nbsp;
	 			<input type=\"submit\" name=\"gobutton\" value=\"{$this->ipsclass->lang['f_go']} ({$this->ipsclass->input['selectedpidcount']})\" class=\"button\" />
	 		</form>
	 	</div>
		<!--IBF.MOD_PANEL-->
	 </div>
</div>
") : ("")) . "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_wrapper:desc::trigger:>
//===========================================================================
function mod_wrapper($id="",$text="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<option value=\"$id\">-{$text}</option>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mq_image_add:desc::trigger:>
//===========================================================================
function mq_image_add($pid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"{$this->ipsclass->vars['img_url']}/p_mq_add.gif\" name=\"mad_$pid\" alt=\"+\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mq_image_remove:desc::trigger:>
//===========================================================================
function mq_image_remove($pid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"{$this->ipsclass->vars['img_url']}/p_mq_remove.gif\" name=\"mad_$pid\" alt=\"-\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:personal_portal_gender_image:desc::trigger:>
//===========================================================================
function personal_portal_gender_image($member=array(),$noid=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "" . (($member['pp_gender']) ? ("
	" . (($member['pp_gender'] == 'male') ? ("
		<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/gender_male.png' " . (($noid==0) ? ("id='pp-entry-gender-img-{$member['id']}'") : ("")) . " style='vertical-align:top' alt='' border='0' />
	") : ("
		" . (($member['pp_gender'] == 'female') ? ("
			<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/gender_female.png' " . (($noid==0) ? ("id='pp-entry-gender-img-{$member['id']}'") : ("")) . " alt='' border='0' />
		") : ("")) . "
	")) . "
") : ("
	<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/gender_mystery.png' " . (($noid==0) ? ("id='pp-entry-gender-img-{$member['id']}'") : ("")) . " alt='' border='0' />
")) . "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:personal_portal_online_image:desc::trigger:>
//===========================================================================
function personal_portal_online_image($member=array()) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "" . (($member['_online']) ? ("
	<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/user-online.png' alt='' border='0' />") : ("
	<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/user-offline.png' alt='' border='0' />")) . "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:pid_image_selected:desc::trigger:>
//===========================================================================
function pid_image_selected($pid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img name=\"img{$pid}\" src=\"{$this->ipsclass->vars['img_url']}/topic_selected.gif\" alt='' />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:pid_image_unselected:desc::trigger:>
//===========================================================================
function pid_image_unselected($pid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img name=\"img{$pid}\" src=\"{$this->ipsclass->vars['img_url']}/topic_unselected.gif\" alt='' />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_icon:desc::trigger:>
//===========================================================================
function post_icon($icon="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon{$icon}.gif\" alt=\"\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:quick_reply_box_closed:desc::trigger:>
//===========================================================================
function quick_reply_box_closed() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:ShowHide('qr_open','qr_closed');\" title=\"{$this->ipsclass->lang['qr_open']}\" accesskey=\"f\"><{T_QREPLY}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:quick_reply_box_open:desc::trigger:>
//===========================================================================
function quick_reply_box_open($fid="",$tid="",$show="hide",$key="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div id=\"qr_open\" style=\"display: $show; position: relative;\">
<br />
<form name=\"REPLIER\" action=\"{$this->ipsclass->base_url}\" method=\"post\">
<input type=\"hidden\" name=\"act\" value=\"Post\" />
<input type=\"hidden\" name=\"CODE\" value=\"03\" />
<input type=\"hidden\" name=\"f\" value=\"$fid\" />
<input type=\"hidden\" name=\"t\" value=\"$tid\" />
<input type=\"hidden\" name=\"st\" value=\"{$this->ipsclass->input['st']}\" />
<input type=\"hidden\" name=\"auth_key\" value=\"$key\" />
<input type=\"hidden\" name=\"fast_reply_used\" value=\"1\" />
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['qr_title']}</div>
	<div style='padding:6px;' align=\"center\" class='row2'>
		<div id='fast-reply-controls' align='center' style='width:75%;padding:6px; margin:0 auto 0 auto' class=\"rte-buttonbar\">
		<table cellpadding=\"2\" cellspacing=\"0\" width='100%'>
		<tr>
		 <td width='1%' align='left' nowrap='nowrap'>
		  <table cellpadding='0' cellspacing='0' width='100%'>
		   <tr>
		     <td><div class=\"rte-normal\" id=\"fast-reply_cmd_bold\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-bold.png\"  alt=\"{$this->ipsclass->lang['js_tt_bold']}\" title=\"{$this->ipsclass->lang['js_tt_bold']}\" /></div></td>
		     <td><div class=\"rte-normal\" id=\"fast-reply_cmd_italic\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-italic.png\"  alt=\"{$this->ipsclass->lang['js_tt_italic']}\" title=\"{$this->ipsclass->lang['js_tt_italic']}\" /></div></td>
		     <td><div class=\"rte-normal\" id=\"fast-reply_cmd_underline\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-underlined.png\" alt=\"{$this->ipsclass->lang['js_tt_underline']}\" title=\"{$this->ipsclass->lang['js_tt_underline']}\" /></div></td>
		   	 <td><div class=\"rte-normal\" id=\"fast-reply_cmd_createlink\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-link-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_link']}\" title=\"{$this->ipsclass->lang['js_rte_lite_link']}\" /></div></td>
			 <td><div class=\"rte-normal\" id=\"fast-reply_cmd_insertimage\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-image-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_img']}\" title=\"{$this->ipsclass->lang['js_rte_lite_img']}\" /></div></td>
			 <td><div class=\"rte-normal\" id=\"fast-reply_cmd_emoticon\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-emo-button.png\"  alt=\"{$this->ipsclass->lang['js_tt_emoticons']}\" title=\"{$this->ipsclass->lang['js_tt_emoticons']}\" /></div></td>
		     <td><div class=\"rte-normal\" id=\"fast-reply_cmd_ipb_quote\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-quote-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_quote']}\" title=\"{$this->ipsclass->lang['js_rte_lite_quote']}\" /></div></td>
			 <td><div class=\"rte-normal\" id=\"fast-reply_cmd_ipb_code\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-code-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_code']}\" title=\"{$this->ipsclass->lang['js_rte_lite_code']}\" /></div></td>
		</tr>
		  </table>
		 </td>
		 <td width='98%'>&nbsp;</td>
		 <td width='1%' align='right' nowrap='nowrap'>
			<table cellpadding='0' cellspacing='0' width='100%'>
	           <tr>
	               	<td>
					   <div class=\"rte-normal\" id=\"fast-reply_resize_up\" style='padding:0px;margin:0px;'><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-resize-up.gif\"  alt=\"\" /></div>
					   <div class=\"rte-normal\" id=\"fast-reply_resize_down\" style='padding:0px;margin:0px;padding-top:1px'><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-resize-down.gif\"  alt=\"\" title=\"\" /></div>
				   </td>
	           </tr>
	          </table>
		 </td>
		</tr>
		</table>
	   <div style='padding-bottom:8px'>
	    	<textarea style='margin:0px;padding:4px;width:98%' tabindex=\"1\" name='Post' id='fast-reply_textarea' class='rte-iframe' cols='80' rows='15'></textarea>
	   </div>
	   <div>
			<div>
				" . (($this->ipsclass->member['auto_track'] == "" or $this->ipsclass->member['auto_track'] == '0') ? ("
					<input type=\"checkbox\" name=\"enabletrack\" value=\"1\" class=\"checkbox\" />&nbsp;{$this->ipsclass->lang['qr_add_email']} &#124;
				") : ("
					<input type=\"checkbox\" name=\"enabletrack\" value=\"1\" class=\"checkbox\" checked=\"checked\" />&nbsp;{$this->ipsclass->lang['qr_add_email']} &#124;
				")) . "
				<input type=\"checkbox\" name=\"enableemo\" value=\"yes\" class=\"checkbox\" checked=\"checked\" />&nbsp;{$this->ipsclass->lang['qr_add_smilie']} &#124;
				<input type=\"checkbox\" name=\"enablesig\" value=\"yes\" class=\"checkbox\" checked=\"checked\" />&nbsp;{$this->ipsclass->lang['qr_add_sig']}
			</div>
		    <div style='margin-top:3px'>
				<input type=\"submit\" name=\"submit\" value=\"{$this->ipsclass->lang['qr_submit']}\" class=\"button\" tabindex=\"2\" accesskey=\"s\" /> &nbsp;
				<input type=\"submit\" name=\"preview\" value=\"{$this->ipsclass->lang['qr_more_opts']}\" class=\"button\" /> &nbsp;
				<input type=\"button\" name=\"qrc\" onclick=\"ShowHide('qr_open','qr_closed');\" value=\"{$this->ipsclass->lang['qr_closeit']}\" class=\"button\" />
			</div>
	   </div>
	</div>
	</div>
</div>
</form>
</div>
<script type='text/javascript'>
<!--
IPS_Lite_Editor[ 'fast-reply' ] = new ips_text_editor_lite( 'fast-reply' );
IPS_Lite_Editor[ 'fast-reply' ].init();
IPS_Lite_Editor[ 'fast-reply' ].text_obj.style.height = '150px';
-->
</script>
<!--<div id=\"qr_open\" style=\"display: $show; position: relative;\">
<br />
<form name=\"REPLIER\" action=\"{$this->ipsclass->base_url}\" method=\"post\">
<input type=\"hidden\" name=\"act\" value=\"Post\" />
<input type=\"hidden\" name=\"CODE\" value=\"03\" />
<input type=\"hidden\" name=\"f\" value=\"$fid\" />
<input type=\"hidden\" name=\"t\" value=\"$tid\" />
<input type=\"hidden\" name=\"st\" value=\"{$this->ipsclass->input['st']}\" />
<input type=\"hidden\" name=\"auth_key\" value=\"$key\" />
<input type=\"hidden\" name=\"fast_reply_used\" value=\"1\" />
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['qr_title']}</div>
	<div style='padding:6px' align=\"center\">
		
" . (($this->ipsclass->member['auto_track'] == "" or $this->ipsclass->member['auto_track'] == '0') ? ("
	<input type=\"checkbox\" name=\"enabletrack\" value=\"1\" class=\"checkbox\" />&nbsp;{$this->ipsclass->lang['qr_add_email']} &#124;
") : ("
	<input type=\"checkbox\" name=\"enabletrack\" value=\"1\" class=\"checkbox\" checked=\"checked\" />&nbsp;{$this->ipsclass->lang['qr_add_email']} &#124;
")) . "
		<input type=\"checkbox\" name=\"enableemo\" value=\"yes\" class=\"checkbox\" checked=\"checked\" />&nbsp;<a href=\"javascript:emo_pop();\">{$this->ipsclass->lang['qr_add_smilie']}</a> &#124;
		<input type=\"checkbox\" name=\"enablesig\" value=\"yes\" class=\"checkbox\" checked=\"checked\" />&nbsp;{$this->ipsclass->lang['qr_add_sig']}
		<br />
		<br />
		<input type=\"submit\" name=\"submit\" value=\"{$this->ipsclass->lang['qr_submit']}\" class=\"button\" tabindex=\"2\" accesskey=\"s\" /> &nbsp;
		<input type=\"submit\" name=\"preview\" value=\"{$this->ipsclass->lang['qr_more_opts']}\" class=\"button\" /> &nbsp;
		<input type=\"button\" name=\"qrc\" onclick=\"ShowHide('qr_open','qr_closed');\" value=\"{$this->ipsclass->lang['qr_closeit']}\" class=\"button\" />
	</div>
</div>
</form>
</div>-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:render_row_hidden:desc::trigger:>
//===========================================================================
function render_row_hidden($post="",$author="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div id='post-ignore-{$post['pid']}' style='display:none'>
 <div class=\"postcolor\" id='post-{$post['pid']}'>
   <strong>{$this->ipsclass->lang['ignore_first_line']} {$post['members_display_name']}.</strong>
   <br />
   <br />
   &middot; <a href=\"#\" onclick=\"return topic_show_ignored_post('{$post['pid']}')\">{$this->ipsclass->lang['ignore_view_post']}</a>
   <br />
   &middot; <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=ignoreremove&amp;id={$author['id']}\">{$this->ipsclass->lang['ignore_unignore']} {$post['members_display_name']}</a>
 </div>
</div>
<script type=\"text/javascript\">
//<![CDATA[
topic_init_ignored_post( '{$post['pid']}' );
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:RenderRow:desc::trigger:>
//===========================================================================
function RenderRow($post="",$author="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--Begin Msg Number {$post['pid']}-->
<table class='ipbtable' cellspacing=\"0\">
	<tr>
		<td valign=\"middle\" class=\"post_head\" width=\"1%\">
			<a name=\"entry{$post['pid']}\"></a>
			" . (($author['id']) ? ("
				<div id=\"post-member-{$post['pid']}\" class='popmenubutton-new-out'>
					<span class=\"{$post['name_css']}\">{$author['_pp_online_image']}{$author['_members_display_name']}</span>
				</div>
				<!-- member menu -->
				<div class='popupmenu-new' id='post-member-{$post['pid']}_menu' style='display:none;width:230px'>
					<div class='popupmenu-item-last'>
						" . (($author['members_display_name_short'] != $author['members_display_name']) ? ("
							<div class='popupmenu-item'><strong>{$author['members_display_name']}</strong></div>
						") : ("")) . "
						<div style='float:right'>
							<div class='pp-image-thumb-wrap'>
								<img src='{$author['pp_thumb_photo']}' width='{$author['pp_thumb_width']}' height='{$author['pp_thumb_height']}' alt='' />
							</div>
							" . (($this->ipsclass->vars['pp_allow_member_rate']) ? ("
								<div style='margin-top:5px;margin-left:6px;'>
									<img src=\"{$this->ipsclass->vars['img_url']}/rating_{$author['_pp_rating_real']}_mini.gif\" alt='{$this->ipsclass->lang['rating_prefix']}: {$author['_pp_rating_real']}' style='vertical-align:middle' border='0' />
								</div>
							") : ("")) . "
						</div>
						<div class='popupmenu-item'>
							{$author['_pp_gender_image']} <a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\">{$this->ipsclass->lang['dd_view_profile']}</a>
						</div>
						" . (($this->ipsclass->member['id']) ? ("
							<div class='popupmenu-item'>
								" . ((in_array( $author['id'], array_keys( $this->ipsclass->member['_cache']['friends'] ) )) ? ("
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_remove_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=remove&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['dd_remove_friend']}</a>
								") : ("
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_add_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=add&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['dd_add_friend']}</a>
								")) . "
							</div>
							<div class='popupmenu-item'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/send_pm_small.png' alt='' border='0' /> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=4&amp;MID={$author['id']}\">{$this->ipsclass->lang['dd_send_pm']}</a>
							</div>
							<div class='popupmenu-item'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=gettopicsuser&amp;mid={$author['id']}'>{$this->ipsclass->lang['dd_find_topics']}</a>
							</div>
							<div class='popupmenu-item-last'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=getalluser&amp;mid={$author['id']}'>{$this->ipsclass->lang['dd_find_posts']}</a>
							</div>
						") : ("")) . "
					</div>
				</div>
				<!-- member menu -->
				<script type=\"text/javascript\">
					ipsmenu.register( \"post-member-{$post['pid']}\", '', 'popmenubutton-new', 'popmenubutton-new-out' );
				</script>
			") : ("
				<span class=\"{$post['name_css']}\">{$author['_members_display_name']}</span>
			")) . "
			
		</td>
		<td class=\"post_head\" valign=\"middle\" width=\"99%\">
			<!-- POSTED DATE DIV -->
			<div style=\"float: left;\">
				<span class=\"postdetails\">{$post['post_icon']} <img src='{$this->ipsclass->vars['img_url']}/to_post_off.gif' alt='{$this->ipsclass->lang['to_post_alt']}' border='0' style='padding-bottom:2px' /> {$post['post_date']}</span>
			</div>
			<!-- REPORT / DELETE / EDIT / QUOTE DIV -->
			<div align=\"right\">
				<span class=\"postdetails\">{$post['ip_address']} {$this->ipsclass->lang['posted_on']}
					<a title=\"{$this->ipsclass->lang['tt_link']}\" href=\"{$this->ipsclass->vars['board_url']}/index.{$this->ipsclass->vars['php_ext']}?showtopic={$post['topic_id']}&view=findpost&p={$post['pid']}\" onclick=\"link_to_post({$post['pid']}); return false;\">#{$post['post_count']}</a>
					" . (($this->ipsclass->member['is_mod']) ? ("
						&#0124; <a href=\"#\" title=\"{$this->ipsclass->lang['click_for_mod']}\" onclick=\"topic_toggle_pid('{$post['pid']}'); return false;\">{$post['pid_start_image']}</a>
					") : ("")) . "
				</span>
			</div>
		</td>
	</tr>
	<tr>
		<td valign=\"top\" class=\"{$post['post_css']} post_left\">
        	<span class=\"postdetails\">
				" . (($author['id'] AND $author['avatar']) ? ("
					<a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\" title=\"{$this->ipsclass->lang['dd_view_profile']}\">{$author['avatar']}</a><br /><br />
				") : ("
        			{$author['avatar']}<br /><br />
				")) . "
        		{$author['title']}<br />
        		{$author['member_rank_img']}<br /><br />
        		{$author['member_group']}<br />
        		{$author['member_posts']}<br />
        		{$author['member_joined']}<br />
        		{$author['member_location']}
        		{$author['member_number']}<br />
				" . (($author['custom_fields'] != "") ? ("
					{$author['custom_fields']}
				") : ("")) . "
				<br />
        		{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
        	</span><br />
        	<img src=\"{$this->ipsclass->vars['img_url']}/spacer.gif\" alt=\"\" width=\"160\" height=\"1\" /><br /> 
       </td>
       <td width=\"100%\" valign=\"top\" class=\"{$post['post_css']}\" id='post-main-{$post['pid']}'>
			<!-- THE POST {$post['pid']} -->
			<div class=\"postcolor\" id='post-{$post['pid']}'>
				{$post['post']}
				{$post['edit_by']}
				" . (($post['post_edit_reason'] != '') ? ("
					<div class='post-edit-reason'>
						{$this->ipsclass->lang['reason_for_edit']}: {$post['post_edit_reason']}
					</div>
				") : ("")) . "
				<!--IBF.ATTACHMENT_{$post['pid']}-->
			</div>
			
			{$post['signature']}
			<!-- THE POST -->		
		</td>
	</tr>
	<tr>
		<td class=\"formbuttonrow\" nowrap=\"nowrap\">
			<div style='text-align:left'><a href=\"javascript:scroll(0,0);\"><{P_UP}></a>{$post['report_link']}</div>
		</td>
		<td class=\"formbuttonrow\" nowrap=\"nowrap\">
			<!-- PM / EMAIL / WWW / MSGR -->
			<div style=\"float: left;\">
				&nbsp;
			</div>
			<!-- REPORT / UP -->
         	<div align=\"right\">
         		{$post['delete_button']}{$post['edit_button']}<a href=\"#\" onclick=\"multiquote_add({$post['pid']}); return false;\" title=\"{$this->ipsclass->lang['mq_title']}\">{$post['mq_start_image']}</a><a href=\"{$this->ipsclass->base_url}act=Post&amp;CODE=02&amp;f={$this->ipsclass->input['f']}&amp;t={$this->ipsclass->input['t']}&amp;qpid={$post['pid']}\" title=\"{$this->ipsclass->lang['tt_reply_to_post']}\"><{P_QUOTE}></a>
         	</div>
         </td>
	</tr><tr>
	<td class=\"catend\" colspan=\"2\">
	<!-- no content -->
	</td>
</tr>
</table>
" . (($post['edit_button']!='') ? ("
<script type='text/javascript'>
//<![CDATA[
if ( ajax_loaded && use_enhanced_js )
{
menu_build_menu( 'edit-but-{$post['pid']}',
	new Array(  img_item + \" <a title='{$this->ipsclass->lang['edit_full_desc']}' href='{$this->ipsclass->base_url}act=post&amp;do=edit_post&amp;f={$post['forum_id']}&amp;t={$post['topic_id']}&amp;p={$post['pid']}&amp;st={$this->ipsclass->input['st']}'>{$this->ipsclass->lang['edit_full_title']}</a>\",
				img_item + \" <a href='#' title='{$this->ipsclass->lang['edit_quick_desc']}' onclick='return ajax_prep_for_edit({$post['pid']}, event);'>{$this->ipsclass->lang['edit_quick_title']}</a>\" ) );
}
//]]>
</script>
") : ("")) . "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:report_link:desc::trigger:>
//===========================================================================
function report_link($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=report&amp;t={$data['topic_id']}&amp;p={$data['pid']}&amp;st={$this->ipsclass->input['st']}\"><{P_REPORT}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_attachment_title:desc::trigger:>
//===========================================================================
function show_attachment_title($title="",$data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<div>
	<strong><span class=\"edit\">$title</span></strong>
	<div>
		$data
	</div>
</div>
<div>&nbsp;</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Show_attachments:desc::trigger:>
//===========================================================================
function Show_attachments($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=attach&amp;type={$data['type']}&amp;id={$data['attach_id']}\" title=\"{$this->ipsclass->lang['attach_dl']}\" target=\"_blank\"><img src=\"{$this->ipsclass->vars['mime_img']}/{$data['mime_image']}\" alt=\"{$this->ipsclass->lang['attached_file']}\" /></a>
&nbsp;<a href=\"{$this->ipsclass->base_url}act=attach&amp;type={$data['type']}&amp;id={$data['attach_id']}\" title=\"{$this->ipsclass->lang['attach_dl']}\" target=\"_blank\">{$data['attach_file']}</a> ( {$data['file_size']} )
<span class=\"desc\">{$this->ipsclass->lang['attach_hits']}: {$data['attach_hits']}</span><br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Show_attachments_img:desc::trigger:>
//===========================================================================
function Show_attachments_img($file_name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"{$this->ipsclass->vars['upload_url']}/$file_name\" class='linked-image' alt=\"{$this->ipsclass->lang['pic_attach']}\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Show_attachments_img_thumb:desc::trigger:>
//===========================================================================
function Show_attachments_img_thumb($data=array()) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "" . ((!$data['notinline']) ? ("
 <br />
") : ("")) . "
<table style='width:auto;display:inline;' id='ipb-attach-table-{$data['_attach_id']}' cellspacing='0' cellpadding='0'>
<tr>
 <td>
	<div id='ipb-attach-div-{$data['_attach_id']}'>
		<div id='ipb-attach-ct-{$data['_attach_id']}'></div>
		<a id='ipb-attach-url-{$data['_attach_id']}' href=\"{$this->ipsclass->base_url}act=attach&amp;type={$data['type']}&amp;id={$data['attach_id']}\" title=\"{$data['location']} - {$this->ipsclass->lang['attach_size']} {$data['file_size']}, {$this->ipsclass->lang['attach_ahits']} {$data['attach_hits']}\" target=\"_blank\"><img src=\"{$this->ipsclass->vars['upload_url']}/{$data['t_location']}\" id='ipb-attach-img-{$data['_attach_id']}' style='width:{$data['t_width']};height:{$data['t_height']}' class='attach' width=\"{$data['t_width']}\" height=\"{$data['t_height']}\" alt=\"{$this->ipsclass->lang['pic_attach']}\" /></a>
		<div id='ipb-attach-cb-{$data['_attach_id']}' style='margin:0px'></div>
	</div>
 </td>
</tr>
</table>
<script type='text/javascript'>
//<![CDATA[
	fix_linked_image_sizes_attach_thumb( \"{$data['_attach_id']}\", parseInt(\"{$data['o_width']}\"), parseInt(\"{$data['o_height']}\"), \"{$data['file_size']}\" );
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:start_poll_link:desc::trigger:>
//===========================================================================
function start_poll_link($fid="",$tid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=post&amp;CODE=14&amp;f=$fid&amp;t=$tid\"><{A_APOLL}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:TableFooter:desc::trigger:>
//===========================================================================
function TableFooter($data="",$is_outline="",$auth_key="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- END TABLE -->
" . (($is_outline == 1) ? ("
<br />
<div class=\"borderwrap\">
") : ("")) . "
<!-- TABLE FOOTER -->
<div class=\"barc\">
	<div style=\"float: right; padding: 5px 5px 0 0;\"><a href=\"{$this->ipsclass->base_url}showtopic={$data['TOPIC']['tid']}&amp;view=old\" style='text-decoration:none'>&laquo; {$this->ipsclass->lang['t_old']}</a>
	&middot; <a href=\"{$this->ipsclass->base_url}showforum={$data['FORUM']['id']}\" style='font-weight: bold;text-decoration:none'>{$data['FORUM']['name']}</a>
	&middot; <a href=\"{$this->ipsclass->base_url}showtopic={$data['TOPIC']['tid']}&amp;view=new\" style='text-decoration:none'>{$this->ipsclass->lang['t_new']} &raquo;</a></div>
	<div>
		<form action=\"{$this->ipsclass->base_url}\" method=\"post\" name=\"search\">
			<input type=\"hidden\" name=\"forums\" value=\"{$data['FORUM']['id']}\" />
			<input type=\"hidden\" name=\"topic\" value=\"{$data['TOPIC']['tid']}\" />
			<input type=\"hidden\" name=\"act\" value=\"Search\" />
			<input type=\"hidden\" name=\"CODE\" value=\"searchtopic\" />
			<input type=\"text\" size=\"25\" name=\"keywords\" class=\"searchinput\" value=\"{$this->ipsclass->lang['enter_keywords']}\" onfocus=\"this.value = '';\" />&nbsp;
			<input type=\"submit\" value=\"{$this->ipsclass->lang['search_topic']}\" class=\"button\" />
		</form>
	</div>
</div>
</div>
<br />
<!--IBF.MOD_FULL_WRAPPER-->
<!--IBF.MOD_PANEL_NO_MOD-->
<table class='ipbtable' cellspacing=\"0\">
	<tr>
		<td style='padding-left:0px' width=\"30%\" nowrap=\"nowrap\" valign=\"middle\"><div>{$data['TOPIC']['SHOW_PAGES']}</div></td>
		<td class='nopad' style='padding:5px 0px 5px 0px' align=\"right\" width=\"70%\"><!--IBF.QUICK_REPLY_CLOSED--><!--IBF.TOPIC_REPLY--><a href=\"{$this->ipsclass->base_url}act=post&amp;do=new_post&amp;f={$data['FORUM']['id']}\" title=\"{$this->ipsclass->lang['start_new_topic']}\"><{A_POST}></a></td>
	</tr>
</table>
<!--IBF.TOPIC_ACTIVE-->
<!--IBF.QUICK_REPLY_OPEN-->
<br />
<div class=\"borderwrap\">
	<div class=\"row2\" style=\"padding: 5px;\">
		<!--IBF.MULTIMOD-->
		<div align=\"right\">{$data['FORUM']['JUMP']}</div>
	</div>
</div>
<br />
<!-- NON JS STUFF -->
<div id='topicoptionsjs'>
 <a name='topicdisplay'></a>
 <div class='borderwrap'>
  <div class=\"bar\" style=\"padding: 5px;text-align:center\">
  <strong>{$this->ipsclass->lang['topic_display']}:</strong> {$data['TOPIC']['to_button_standard']} &middot;
  {$data['TOPIC']['to_button_linearpl']} &middot;
  {$data['TOPIC']['to_button_threaded']}
  </div>
 </div>
 <br />
 <a name='topicoptions'></a>
 <div class='borderwrap'>
  <div class=\"bar\" style=\"padding: 5px;text-align:center\">
  <a href='{$this->ipsclass->base_url}act=usercp&amp;CODE=start_subs&amp;method=topic&amp;tid={$data['TOPIC']['tid']}'>{$this->ipsclass->lang['track_topic']}</a> &middot;
  <a href='{$this->ipsclass->base_url}act=Forward&amp;f={$data['FORUM']['id']}&amp;t={$data['TOPIC']['tid']}'>{$this->ipsclass->lang['forward']}</a> &middot;
  <a href='{$this->ipsclass->base_url}act=Print&amp;client=printer&amp;f={$data['FORUM']['id']}&amp;t={$data['TOPIC']['tid']}'>{$this->ipsclass->lang['print']}</a> &middot;
  <a href='{$this->ipsclass->base_url}act=usercp&amp;CODE=start_subs&amp;method=forum&amp;fid={$data['FORUM']['id']}'>{$this->ipsclass->lang['ft_title']}</a>
  </div>
 </div>
 <br />
" . (($data['TOPIC']['_allow_rate'] != 0) ? ("
<a name='topicrating'></a>
 <div class='borderwrap'>
  <div class=\"bar\" style=\"padding: 5px;text-align:center\">
  <form action='{$this->ipsclass->base_url}&amp;showtopic={$data['TOPIC']['tid']}&amp;addrating=1&amp;st={$this->ipsclass->input['st']}' method='POST'>
  <strong>{$this->ipsclass->lang['topic_rating']}</strong> &nbsp;<select name='rating'>
   <option value='5'>* * * * *</option>
   <option value='4'>* * * *</option>
   <option value='3'>* * *</option>
   <option value='2'>* *</option>
   <option value='1'>*</option>
  </select> <input class='button' type='submit' value=' {$this->ipsclass->lang['dd_rate_button']} ' />
  </form>
  </div>
 </div>
") : ("")) . "
</div>
<script type='text/javascript'>
//<![CDATA[
document.getElementById('topicoptionsjs').style.display = 'none';
 
// Scroll to PID?
topic_scroll_to_post( parseInt(\"{$this->ipsclass->input['gopid']}\") );
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topic_active_users:desc::trigger:>
//===========================================================================
function topic_active_users($active=array()) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\" style='padding-bottom:1px;'>
	<div class=\"formsubtitle\" style=\"padding: 4px;\">{$this->ipsclass->lang['active_users_title']} ({$this->ipsclass->lang['active_users_detail']})</div>
	<div class=\"row1\" style=\"padding: 4px;\">{$this->ipsclass->lang['active_users_members']} {$active['names']}</div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topic_end_first_post:desc::trigger:>
//===========================================================================
function topic_end_first_post($data="",$noreplieshow=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</div>
<table class='ipbtable' cellspacing=\"0\">
	<tr>
		<td style='padding-left:0px' width=\"40%\" valign=\"middle\" nowrap=\"nowrap\"><div>{$data['TOPIC']['SHOW_PAGES']}&nbsp;{$data['TOPIC']['go_new']}</div></td>
		<td class='nopad' style='padding:5px 0px 5px 0px' align=\"right\" width=\"60%\" valign=\"middle\">{$data['TOPIC']['REPLY_BUTTON']}<a href=\"{$this->ipsclass->base_url}act=post&amp;do=new_post&amp;f={$data['FORUM']['id']}\" title=\"{$this->ipsclass->lang['start_new_topic']}\"><{A_POST}></a></td>
	</tr>
</table>
<a name=\"firstpost\"></a>
<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['tom_replies']}
" . (($noreplieshow != 1) ? ("
({$data['TOPIC']['new_mode_start']} - {$data['TOPIC']['new_mode_end']})
") : ("")) . "
	</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topic_end_outline:desc::trigger:>
//===========================================================================
function topic_end_outline($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topic_opts_closed:desc::trigger:>
//===========================================================================
function topic_opts_closed() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:ShowHide('topic_open','topic_closed')\" title=\"{$this->ipsclass->lang['to_open']}\"><{T_OPTS}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topic_page_top:desc::trigger:>
//===========================================================================
function topic_page_top($data="",$threaded=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\">
<!--
var ipb_lang_tt_prompt = \"{$this->ipsclass->lang['tt_prompt']}\";
var ipb_lang_js_del_1  = \"{$this->ipsclass->lang['js_del_1']}\";
var ipb_lang_js_del_2  = \"{$this->ipsclass->lang['js_del_2']}\";
var addquotebutton     = \"{$this->ipsclass->vars['img_url']}/p_mq_add.gif\";
var removequotebutton  = \"{$this->ipsclass->vars['img_url']}/p_mq_remove.gif\";
var unselectedbutton = \"{$this->ipsclass->vars['img_url']}/topic_unselected.gif\";
var selectedbutton   = \"{$this->ipsclass->vars['img_url']}/topic_selected.gif\";
var lang_gobutton    = \"{$this->ipsclass->lang['f_go']}\";
var lang_suredelete  = \"{$this->ipsclass->lang['cp_js_delete']}\";
var js_error_no_permission = \"{$this->ipsclass->lang['js_error_no_permission']}\";
var js_no_empty_post = \"{$this->ipsclass->lang['js_no_empty_post']}\";
//-->
</script>
<script type=\"text/javascript\" src=\"jscripts/ipb_topic.js\"></script>
<script type=\"text/javascript\" src=\"jscripts/ips_text_editor_lite.js\"></script>
<script type='text/javascript'>
//<![CDATA[
topic_rate = new topic_rate();
//]]>
</script>
<a name=\"top\"></a>
<!--IBF.FORUM_RULES-->
" . (($threaded == 0) ? ("
<table class='ipbtable' cellspacing=\"0\">
	<tr>
		<td style='padding-left:0px' width=\"40%\" valign=\"middle\" nowrap=\"nowrap\"><div>{$data['TOPIC']['SHOW_PAGES']}&nbsp;{$data['TOPIC']['go_new']}</div></td>
		<td class='nopad' style='padding:0px 0px 5px 0px' align=\"right\" width=\"60%\" valign=\"middle\"><!--IBF.TOPIC_REPLY--><a href=\"{$this->ipsclass->base_url}act=post&amp;do=new_post&amp;f={$data['FORUM']['id']}\" title=\"{$this->ipsclass->lang['start_new_topic']}\"><{A_POST}></a></td>
	</tr>
</table>
") : ("")) . "
<div class=\"borderwrap\">
	<div class=\"maintitle\">
	<!-- TABLE FIX FOR MOZILLA WRAPPING-->
	<table width='100%' style='padding:0px' cellspacing='0' cellpadding='0'>
	<tr>
	 <td width='99%' style='word-wrap:break-word;'><div><b>{$data['TOPIC']['title']}</b>{$data['TOPIC']['description']}</div></td>
	 
	 <td width='1%' align='right' nowrap='nowrap'>
		
		" . (($data['TOPIC']['_allow_rate'] != 0) ? ("
			<div class='popmenubutton' id='topic-rating'>
				<a href='#topicrating'>{$this->ipsclass->lang['topic_rating']}</a>
				{$data['TOPIC']['_rate_img']} <img src='{$this->ipsclass->vars['img_url']}/menu_action_down.gif' alt='V' title='{$this->ipsclass->lang['global_open_menu']}' border='0' />
			</div>&nbsp;
		") : ("
			" . (($data['TOPIC']['_rate_show'] == 1 AND $data['TOPIC']['_rate_img'] != '') ? ("
				<div class='popmenubutton' id='topic-rating'>
					{$this->ipsclass->lang['topic_rating']} {$data['TOPIC']['_rate_img']} <img src='{$this->ipsclass->vars['img_url']}/menu_action_down.gif' alt='V' title='{$this->ipsclass->lang['global_open_menu']}' border='0' />
				</div>&nbsp;
			") : ("")) . "
		")) . "
		" . (($data['TOPIC']['_allow_rate'] != 0) ? ("
			<div id='topic-rating_menu' class='popupmenu-new' style='display:none;width:140px'>
				<div class='popupmenu-item'>
					<div id='topic-rating-wrapper'></div>
				</div>
				<div class='popupmenu-item'>
					{$this->ipsclass->lang['you_have_rated_x']} <span id='topic-rating-my-rating'>{$data['TOPIC']['_rating_value']}</span>
				</div>
				<div class='popupmenu-item-last'>
					{$this->ipsclass->lang['total_ratings']} <span id='topic-rating-hits'>{$data['TOPIC']['topic_rating_hits']}</span>
				</div>
			</div>
			<script type='text/javascript'>
				ipsmenu.register( \"topic-rating\" );
			</script>
		") : ("")) . "
     </td>
	 <td width='1%' align='right' nowrap='nowrap'>
	    <div class='popmenubutton' id='topicmenu-options'><a href='#topicoptions'>{$this->ipsclass->lang['topic_options']}</a> <img src='{$this->ipsclass->vars['img_url']}/menu_action_down.gif' alt='V' title='{$this->ipsclass->lang['global_open_menu']}' border='0' /></div>
	 </td>
	</tr>
  </table>
	 
 </div>
 <!--{IBF.POLL}-->
<script type=\"text/javascript\">
<!--
menu_build_menu(
\"topicmenu-options\",
new Array(   img_item + \" <a href='{$this->ipsclass->base_url}act=usercp&amp;CODE=start_subs&amp;method=topic&amp;tid={$data['TOPIC']['tid']}'>{$this->ipsclass->lang['track_topic']}</a>\",
 			 img_item + \" <a href='{$this->ipsclass->base_url}act=Forward&amp;f={$data['FORUM']['id']}&amp;t={$data['TOPIC']['tid']}'>{$this->ipsclass->lang['forward']}</a>\",
 			 img_item + \" <a href='{$this->ipsclass->base_url}act=Print&amp;client=printer&amp;f={$data['FORUM']['id']}&amp;t={$data['TOPIC']['tid']}'>{$this->ipsclass->lang['print']}</a>\",
             img_item + \" <a href='{$this->ipsclass->base_url}act=Print&amp;client=choose&amp;f={$data['FORUM']['id']}&amp;t={$data['TOPIC']['tid']}'>{$this->ipsclass->lang['av_title']}</a>\",
 			 img_item + \" <a href='{$this->ipsclass->base_url}act=usercp&amp;CODE=start_subs&amp;method=forum&amp;fid={$data['FORUM']['id']}'>{$this->ipsclass->lang['ft_title']}</a>\",
 			 \"~~NODIV~~<div class='popupmenu-category' align='center'>{$this->ipsclass->lang['dd_display_modes']}</div>\",
 			 img_item + \" {$data['TOPIC']['to_button_threaded']}\",
 			 img_item + \" {$data['TOPIC']['to_button_standard']}\",
 			 img_item + \" {$data['TOPIC']['to_button_linearpl']}\"
	    ) );
topic_rate.settings['allow_rating']       = parseInt(\"{$data['TOPIC']['_allow_rate']}\");
topic_rate.settings['default_rating']     = parseInt(\"{$data['TOPIC']['_rate_int']}\");
topic_rate.settings['img_base_url']       = ipb_var_image_url + '/folder_topic_view';
topic_rate.settings['div_rating_wrapper'] = 'topic-rating-wrapper';
topic_rate.settings['text_rating_image']  = 'topic-rating-img-';
topic_rate.languages['img_alt_rate']      = \"{$this->ipsclass->lang['js_img_alt_rate']}\";
topic_rate.languages['rate_me']           = \"{$this->ipsclass->lang['js_rate_me']}\";
topic_rate.init_rating_images();
-->
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topic_rating_image:desc::trigger:>
//===========================================================================
function topic_rating_image($rating_id=0,$title='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "" . (($rating_id > 0) ? ("
	<img src='{$this->ipsclass->vars['img_url']}/folder_topic_view/rating_{$rating_id}.gif' id='topic-rating-img-main' border='0' alt='{$rating_id}' />
") : ("
	<img src='{$this->ipsclass->vars['img_url']}/blank.gif' id='topic-rating-img-main' border='0' alt='' />
")) . "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:toutline_end_list:desc::trigger:>
//===========================================================================
function toutline_end_list($pages="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</div>
	<div class=\"row1\">$pages</div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:toutline_end_new_parent:desc::trigger:>
//===========================================================================
function toutline_end_new_parent() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:toutline_mode_choice_off:desc::trigger:>
//===========================================================================
function toutline_mode_choice_off($url="",$macro="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href='$url'>{$this->ipsclass->lang['topic_display_switch']} $macro</a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:toutline_mode_choice_on:desc::trigger:>
//===========================================================================
function toutline_mode_choice_on($url="",$macro="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<strong><em><a href='$url'>$macro</a></em></strong>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:toutline_show_row:desc::trigger:>
//===========================================================================
function toutline_show_row($data="",$show=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$data['depthguide']} {$data['new_post']} <b>{$data['linked_name']}</b> &nbsp; <i><a href=\"{$this->ipsclass->base_url}showtopic={$data['topic_id']}&amp;pid={$data['pid']}&amp;mode=threaded&amp;start={$show}#entry{$data['pid']}\">{$data['post_title']}</a></i> &nbsp; <span class=\"desc\">{$data['formatted_date']}</span><br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:toutline_show_row_highlight:desc::trigger:>
//===========================================================================
function toutline_show_row_highlight($data="",$show=0,$st=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div style='background:#FFF9BA;'>{$data['depthguide']} {$data['new_post']} <b>{$data['linked_name']}</b> &nbsp; <i><a href=\"{$this->ipsclass->base_url}showtopic={$data['topic_id']}&amp;pid={$data['pid']}&amp;mode=threaded&amp;show={$show}&amp;st={$st}#entry{$data['pid']}\">{$data['post_title']}</a></i> &nbsp; <span class=\"desc\">{$data['formatted_date']}</span></div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:toutline_start_list:desc::trigger:>
//===========================================================================
function toutline_start_list() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['outline_posts_topic']}</div>
	<div class=\"tablepad\">";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:toutline_start_new_parent:desc::trigger:>
//===========================================================================
function toutline_start_new_parent() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_level_rating:desc::trigger:>
//===========================================================================
function warn_level_rating($id="",$level="",$min=0,$max=10) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&lt;&nbsp;$min ( <a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')\">{$level}</a> ) $max&nbsp;&gt;";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_level_warn:desc::trigger:>
//===========================================================================
function warn_level_warn($id="",$percent="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['tt_warn']} (<a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')\">{$percent}</a>%)";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
announcement_show,RenderRow,topic_page_top
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>