<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_legends_3 {

 var $ipsclass;
//===========================================================================
// <ips:bbcode_header:desc::trigger:>
//===========================================================================
function bbcode_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div>{$this->ipsclass->lang['bbc_intro']}</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:bbcode_row:desc::trigger:>
//===========================================================================
function bbcode_row($before="",$after="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class=\"row1\" valign=\"middle\">$before</td>
	<td class=\"row1\" valign=\"middle\">$after</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:bbcode_row_footer:desc::trigger:>
//===========================================================================
function bbcode_row_footer() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table>
	</div>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:bbcode_row_header:desc::trigger:>
//===========================================================================
function bbcode_row_header($title="",$desc="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div>
	<div class=\"borderwrap\">
		<div class=\"maintitle\">$title</div>
		<div class=\"row2\">$desc</div>
		<table class='ipbtable' cellspacing=\"1\">
			<tr>
				<td width=\"50%\" align=\"center\" class=\"row1\" valign=\"middle\">{$this->ipsclass->lang['bbc_before']}</td>
				<td width=\"50%\" align=\"center\" class=\"row1\" valign=\"middle\">{$this->ipsclass->lang['bbc_after']}</td>
			</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:emoticon_javascript:desc::trigger:>
//===========================================================================
function emoticon_javascript($editor_id='ed-0') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script language='javascript'>
" . (($editor_id != '' ) ? ("
	" . (($_REQUEST['_lite']) ? ("
			function add_smilie(scode, smid)
			{
				var _image = document.getElementById(smid).src;
				_image     = _image.replace( /.*\\/(.+?)$/, \"$1\" );
				try
				{
					opener.IPS_Lite_Editor[ '{$editor_id}' ].insert_emoticon( smid.replace( 'smid_', '' ), _image, scode, this );
				}
				catch(error)
				{
				}
			}
	") : ("
		function add_smilie(scode, smid)
		{
			var _image = document.getElementById(smid).src;
			_image     = _image.replace( /.*\\/(.+?)$/, \"$1\" );
			try
			{
				opener.IPS_editor[ '{$editor_id}' ].insert_emoticon( smid.replace( 'smid_', '' ), _image, scode, this );
			}
			catch(error)
			{
			}
		}
	")) . "
") : ("
	function add_smilie(scode, smid)
	{
		surl = document.getElementById(smid).src;
		opener.emoticon( scode, '', surl );
	}
")) . "
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:emoticons_row:desc::trigger:>
//===========================================================================
function emoticons_row($code="",$image="",$in="'",$out="'",$smilie_id=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td align=\"center\" class=\"row1\" valign=\"middle\"><a href={$out}javascript:add_smilie({$in}$code{$in},{$in}smid_$smilie_id{$in}){$out}>$code</a></td>
	<td align=\"center\" class=\"row1\" valign=\"middle\"><a href={$out}javascript:add_smilie({$in}$code{$in},{$in}smid_$smilie_id{$in}){$out}><img src=\"{$this->ipsclass->vars['EMOTICONS_URL']}/$image\" id='smid_$smilie_id' valign=\"absmiddle\" alt=\"$image\" /></a></td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:find_user_error:desc::trigger:>
//===========================================================================
function find_user_error($msg="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form name=\"finduser\" method=\"post\" action=\"{$this->ipsclass->base_url}entry=$entry&amp;name=$name&amp;sep=$sep&amp;CODE=finduser_two\">
	<table class='ipbtable' cellspacing=\"1\">
		<tr>
			<td class=\"pagetitle\">{$this->ipsclass->lang['fu_error']}<hr noshade='noshade' /></td>
		</tr>
		<tr>
			<td align=\"center\" valign=\"middle\">{$msg}</td>
		</tr>
		<tr>
			<td class=\"pcen\"><a href=\"javascript:history.go(-1);\">{$this->ipsclass->lang['fu_back']}</a> :: <a href=\"javascript:window.close();\">{$this->ipsclass->lang['fu_close_win']}</a></td>
		</tr>
	</table>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:find_user_final:desc::trigger:>
//===========================================================================
function find_user_final($names="",$entry="",$name="",$sep="line") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\">
<!--
var separator = '$sep';
var entry     = '$entry';
var in_name   = '$name';
-->
</script>
<script type=\"text/javascript\" src=\"jscripts/ipb_finduser.js\"></script>
<form name=\"finduser\">
	<table class='ipbtable' cellspacing=\"1\">
		<tr>
			<td class=\"pagetitle\">{$this->ipsclass->lang['fu_title']}<hr noshade='noshade' /></td>
		</tr>
		<tr>
			<td align=\"center\" valign=\"middle\">{$this->ipsclass->lang['fu_add_desc']}<br /><br /><select name=\"username\">$names</select><br /><br /><input type=\"button\" name=\"add\" onClick=\"add_to_form()\" value=\"{$this->ipsclass->lang['fu_add_mem']}\"></td>
		</tr>
		<tr>
			<td class=\"pcen\"><a href=\"javascript:history.go(-1);\">{$this->ipsclass->lang['fu_back']}</a> :: <a href=\"javascript:window.close();\">{$this->ipsclass->lang['fu_close_win']}</a></td>
		</tr>
	</table>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:find_user_one:desc::trigger:>
//===========================================================================
function find_user_one($entry="",$name="",$sep="comma") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src='jscripts/ipb_xhr_findnames.js'></script>
<div id='ipb-get-members' style='border:1px solid #000; background:#FFF; padding:2px;position:absolute;width:252px;display:none;z-index:1'></div>
<form name=\"finduser\" method=\"post\" action=\"{$this->ipsclass->base_url}act=legends&amp;entry=$entry&amp;name=$name&amp;sep=$sep&amp;CODE=finduser_two\" id=\"postingform\">
	<table class='ipbtable' cellspacing=\"1\">
		<tr>
			<td class=\"pagetitle\">{$this->ipsclass->lang['fu_title']}<hr noshade='noshade' /></td>
		</tr>
		<tr>
			<td align=\"center\" valign=\"middle\"><b>{$this->ipsclass->lang['fu_enter_name']}</b><br /><br /><input type=\"text\" size=\"40\" id=\"username\" name=\"username\" /><br /><br /><input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['fu_search_but']}\" /></td>
		</tr>
		<tr>
			<td class=\"pcen\"><a href=\"javascript:window.close();\">{$this->ipsclass->lang['fu_close_win']}</a></td>
		</tr>
	</table>
</form>
<script type=\"text/javascript\">
// INIT find names
init_js( 'postingform', 'username', 'get-member-names');
// Run main loop
setTimeout( 'main_loop()', 10 );
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:page_footer:desc::trigger:>
//===========================================================================
function page_footer() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table>
	</div>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:page_header:desc::trigger:>
//===========================================================================
function page_header($title="",$row1="",$row2="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div>
	<div class=\"borderwrap\">
		<div class=\"maintitle\">$title</div>
		<table class='ipbtable' cellspacing=\"1\">
			<tr>
				<td width=\"50%\" align=\"center\" class=\"formsubtitle\" valign=\"middle\">$row1</td>
				<td width=\"50%\" align=\"center\" class=\"formsubtitle\" valign=\"middle\">$row2</td>
			</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:wrap_tag:desc::trigger:>
//===========================================================================
function wrap_tag($tag="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div><b>$tag</b></div>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>