<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_blog_forward_3 {

 var $ipsclass;
//===========================================================================
// <ips:entry_email_form:desc::trigger:>
//===========================================================================
function entry_email_form($title="",$text="",$lang="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->vars['blog_url']}\" method=\"post\" name='REPLIER'>
	<input type=\"hidden\" name=\"req\" value=\"dosendentry\" />
	<input type=\"hidden\" name=\"eid\" value=\"{$this->ipsclass->input['eid']}\" />
	<input type=\"hidden\" name=\"st\" value=\"{$this->ipsclass->input['eid']}\" />
	<div class=\"borderwrap\">
		<div class=\"maintitle\">{$this->ipsclass->lang['entry_email_title']}</div>
		<table cellspacing=\"0\" class=\"ipbtable\">
			<tr>
				<td class=\"pformleft\" valign=\"top\"><b>{$this->ipsclass->lang['entry_send_lang']}</b></td>
				<td class=\"pformright\">$lang</td>
			</tr>
			<tr>
				<td class=\"pformleft\" valign=\"top\"><b>{$this->ipsclass->lang['entry_send_to_name']}</b></td>
				<td class=\"pformright\"><input type=\"text\" name=\"to_name\" value=\"\" size=\"30\" maxlength=\"100\" /></td>
			</tr>
			<tr>
				<td class=\"pformleft\" valign=\"top\"><b>{$this->ipsclass->lang['entry_send_to_email']}</b></td>
				<td class=\"pformright\"><input type=\"text\" name=\"to_email\" value=\"\" size=\"30\" maxlength=\"100\" /></td>
			</tr>
			<tr>
				<td class=\"pformleft\" valign=\"top\"><b>{$this->ipsclass->lang['entry_send_subject']}</b></td>
				<td class=\"pformright\"><input type=\"text\" name=\"subject\" value=\"{$title}\" size=\"30\" maxlength=\"120\" /></td>
			</tr>
			<tr>
				<td class=\"pformleft\" valign=\"top\"><b>{$this->ipsclass->lang['entry_send_message']}</b></td>
				<td class=\"pformright\"><textarea cols=\"60\" rows=\"12\" wrap=\"soft\" name=\"message\" class=\"textinput\">{$text}</textarea>
				</td>
			</tr>
			<tr>
				<td class=\"formbuttonrow\" colspan=\"2\"><input type=\"submit\" class=\"button\" value=\"{$this->ipsclass->lang['entry_submit_send']}\" /></td>
			</tr>
		</table>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
entry_email_form
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>