<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_search_3 {

 var $ipsclass;
//===========================================================================
// <ips:boolean_explain_link:desc::trigger:>
//===========================================================================
function boolean_explain_link() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&#091; <a href=\"#\" title=\"{$this->ipsclass->lang['be_ttip']}\" onclick=\"win_pop()\">{$this->ipsclass->lang['be_link']}</a> &#093;";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:boolean_explain_page:desc::trigger:>
//===========================================================================
function boolean_explain_page() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['be_link']}</div>
	<table class='ipbtable' cellspacing=\"1\">
		<tr>
			<th width=\"30%\" class=\"formsubtitle\">{$this->ipsclass->lang['be_use']}</th>
			<th width=\"70%\" class=\"formsubtitle\">{$this->ipsclass->lang['be_means']}</th>
		</tr>
		<tr>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_u1']}</td>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_m1']}</td>
		</tr>
		<tr>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_u2']}</td>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_m2']}</td>
		</tr>
		<tr>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_u3']}</td>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_m3']}</td>
		</tr>
		<tr>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_u4']}</td>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_m4']}</td>
		</tr>
		<tr>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_u5']}</td>
			<td class=\"pformleft\">{$this->ipsclass->lang['be_m5']}</td>
		</tr>
		<tr>
			<td class=\"catend\" colspan=\"2\"><!-- no content --></td>
		</tr>
	</table>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:end_results_table:desc::trigger:>
//===========================================================================
function end_results_table($data="",$as_post="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- END RESULTS TABLE -->
" . (($as_post != 1) ? ("
<tr>
	<td class=\"formbuttonrow\" colspan=\"8\" style=\"text-align: right;\">
	<form action=\"{$this->ipsclass->base_url}act=search&amp;CODE=getnew&amp;active=1\" method=\"post\">
		{$this->ipsclass->lang['active_start']}&nbsp;
		<select class=\"dropdown\" name=\"lastdate\">
			<option value=\"86400\">{$this->ipsclass->lang['active_today']}</option>
			<option value=\"604800\">{$this->ipsclass->lang['active_week']}</option>
			<option value=\"1209600\">{$this->ipsclass->lang['active_week2']}</option>
			<option value=\"2419200\">{$this->ipsclass->lang['active_month']}</option>
			<option value=\"7257600\">{$this->ipsclass->lang['active_month3']}</option>
			<option value=\"31449600\">{$this->ipsclass->lang['active_year']}</option>
		</select>
		<input type=\"submit\" value=\"{$this->ipsclass->lang['active_go']}\" class=\"button\" /></form></td>
</tr><tr>
	<td class=\"catend\" colspan=\"8\"><!-- no content --></td>
</tr>
</table>
</div>
") : ("")) . "
<br />
<div>{$data['SHOW_PAGES']}</div>
<br />
<div class=\"borderwrap\">
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td width=\"5%\" class=\"row2\" nowrap=\"nowrap\"><{B_NEW}>&nbsp;&nbsp;{$this->ipsclass->lang['pm_open_new']}<br /><{B_NORM}>&nbsp;&nbsp;{$this->ipsclass->lang['pm_open_no']}<br /><{B_HOT}>&nbsp;&nbsp;{$this->ipsclass->lang['pm_hot_new']}<br /><{B_HOT_NN}>&nbsp;&nbsp;{$this->ipsclass->lang['pm_hot_no']}</td>
			<td width=\"5%\" class=\"row2\" nowrap=\"nowrap\"><{B_POLL}>&nbsp;&nbsp;{$this->ipsclass->lang['pm_poll']}<br /><{B_POLL_NN}>&nbsp;&nbsp;{$this->ipsclass->lang['pm_poll_no']}<br /><{B_LOCKED}>&nbsp;&nbsp;{$this->ipsclass->lang['pm_locked']}<br /><{B_MOVED}>&nbsp;&nbsp;{$this->ipsclass->lang['pm_moved']}</td>
			<td align=\"right\" width=\"90%\" class=\"row2\">{$this->ipsclass->forum_jump}</td>
		</tr>
	</table>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Form:desc::trigger:>
//===========================================================================
function Form($forums="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src='jscripts/ipb_xhr_findnames.js'></script>
<script type=\"text/javascript\">
//<![CDATA[
<!-- // Hide js from html validator
	function go_gadget_simple(){
		window.location = \"{$this->ipsclass->js_base_url}act=Search&mode=simple&f={$this->ipsclass->input['f']}\";
	}
	
	function win_pop(){
		window.open(\"{$this->ipsclass->js_base_url}act=Search&CODE=explain\",\"WIN\",\"width=400,height=300,resizable=yes,scrollbars=yes\"); 
	}
//-->
//]]>
</script>
<form action=\"{$this->ipsclass->base_url}act=Search&amp;CODE=01\" id='postingform' method=\"post\" name=\"sForm\">
<div id='ipb-get-members' style='border:1px solid #000; background:#FFF; padding:2px;position:absolute;width:210px;display:none;z-index:1'></div>
<div class=\"borderwrap\">
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td colspan=\"2\" class=\"maintitle\"  align=\"center\">{$this->ipsclass->lang['keywords_title']}</td>
		</tr>
		<tr>
			<td class=\"subtitle\" width=\"50%\">{$this->ipsclass->lang['key_search']}</td>
			<td class=\"subtitle\" width=\"50%\">{$this->ipsclass->lang['mem_search']}</td>
		</tr>
		<tr>
			<td class=\"row1\" valign=\"top\">
				<input type=\"text\" maxlength=\"100\" size=\"40\" name=\"keywords\" id=\"keywords\" />
				<br /><br />
				<label for=\"keywords\">{$this->ipsclass->lang['keysearch_text']}</label> <!--IBF.BOOLEAN_EXPLAIN-->
			</td>
			<td class=\"row2\" valign=\"top\">
				<table class='ipbtable' cellspacing=\"0\">
					<tr>
						<td><input type=\"text\" maxlength=\"100\" size=\"50\" id=\"entered_name\" style='width:210px' name=\"namesearch\" /></td>
					</tr>
					<tr>
						<td width=\"40%\"><input type=\"checkbox\" name=\"exactname\" id=\"matchexact\" value=\"1\" class=\"checkbox\" /><label for=\"matchexact\">{$this->ipsclass->lang['match_name_ex']}</label></td>
					</tr>
				</table>
			</td>
		</tr>
	</table>
</div>
<br />
<div class=\"borderwrap\">
	<table class='ipbtable' cellspacing=\"0\">         
		<tr>
			<td colspan=\"2\" class=\"maintitle\"  align=\"center\">{$this->ipsclass->lang['search_options']}</td>
		</tr>
		<tr>
			<td class=\"subtitle\" width=\"50%\" valign=\"middle\">{$this->ipsclass->lang['search_where']}</td>
			<td class=\"subtitle\" width=\"50%\" valign=\"middle\">{$this->ipsclass->lang['search_refine']}</td>
		</tr>
		<tr>
			<td class=\"row1\" valign=\"middle\">
				$forums
				<br />
				<input type=\"checkbox\" name=\"searchsubs\" value=\"1\" id=\"searchsubs\" checked=\"checked\" class='checkbox' />&nbsp;<label for=\"searchsubs\">{$this->ipsclass->lang['search_in_subs']}</label>
			</td>
			<td class=\"row2\" valign=\"top\">
				<table class='ipbtable' cellspacing=\"1\">
					<tr>
						<td valign=\"top\">
							<fieldset class=\"search\">
							<legend><b>{$this->ipsclass->lang['search_from']}</b></legend>
								<select name=\"prune\">
									<option value=\"1\">{$this->ipsclass->lang['today']}</option>
									<option value=\"7\">{$this->ipsclass->lang['this_week']}</option>
									<option value=\"30\">{$this->ipsclass->lang['this_month']}</option>
									<option value=\"60\">{$this->ipsclass->lang['this_60']}</option>
									<option value=\"90\">{$this->ipsclass->lang['this_90']}</option>
									<option value=\"180\">{$this->ipsclass->lang['this_180']}</option>
									<option value=\"365\">{$this->ipsclass->lang['this_year']}</option>
									<option value=\"0\" selected=\"selected\">{$this->ipsclass->lang['ever']}</option>
								</select><br />
								<input type=\"radio\" name=\"prune_type\" id=\"prune_older\" value=\"older\" class=\"radiobutton\" />&nbsp;<label for=\"prune_older\">{$this->ipsclass->lang['older']}</label><br />
								<input type=\"radio\" name=\"prune_type\" id=\"prune_newer\" value=\"newer\" class=\"radiobutton\" checked=\"checked\" />&nbsp;<label for=\"prune_newer\">{$this->ipsclass->lang['newer']}</label>
							</fieldset>
						</td>
						<td valign=\"top\">
							<fieldset class=\"search\">
								<legend><b>{$this->ipsclass->lang['sort_results']}</b></legend>
									<select name=\"sort_key\">
										<option value=\"last_post\">{$this->ipsclass->lang['last_date']}</option>
										<option value=\"posts\">{$this->ipsclass->lang['number_topics']}</option>
										<option value=\"starter_name\">{$this->ipsclass->lang['poster_name']}</option>
										<option value=\"forum_id\">{$this->ipsclass->lang['forum_name']}</option>
									</select><br />
									<input type=\"radio\" name=\"sort_order\" id=\"sort_desc\" class=\"radiobutton\" value=\"desc\" checked=\"checked\" /><label for=\"sort_desc\">{$this->ipsclass->lang['descending']}</label><br />
									<input type=\"radio\" name=\"sort_order\" id=\"sort_asc\" class=\"radiobutton\" value=\"asc\" /><label for=\"sort_asc\">{$this->ipsclass->lang['ascending']}</label>
								</fieldset>
							</td>
						</tr>
						<tr>
							<td nowrap=\"nowrap\">
								<fieldset class=\"search\">
								<legend><b>{$this->ipsclass->lang['search_where']}</b></legend>
									<input type=\"radio\" name=\"search_in\" class=\"radiobutton\" id=\"search_in_posts\" value=\"posts\" checked=\"checked\" /><label for=\"search_in_posts\">{$this->ipsclass->lang['in_posts']}</label><br />
									<input type=\"radio\" name=\"search_in\" class=\"radiobutton\" id=\"search_in_titles\" value=\"titles\" /><label for=\"search_in_titles\">{$this->ipsclass->lang['in_topics']}</label>
								</fieldset>
							</td>
							<td>
								<fieldset class=\"search\">
								<legend><b>{$this->ipsclass->lang['result_type']}</b></legend>
									<input type=\"radio\" name=\"result_type\" class=\"radiobutton\" value=\"topics\" id=\"result_topics\" checked=\"checked\" /><label for=\"result_topics\">{$this->ipsclass->lang['results_topics']}</label><br />
									<input type=\"radio\" name=\"result_type\" class=\"radiobutton\" value=\"posts\" id=\"result_posts\" /><label for=\"result_posts\">{$this->ipsclass->lang['results_post']}</label>
								</fieldset>
							</td>
						</tr>
					</table>
				</td>
			</tr>
			<tr>
				<td class=\"formbuttonrow\" colspan=\"2\" align=\"center\"><input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['do_search']}\" /><!--IBF.SIMPLE_BUTTON--></td>
			</tr>
		</table>
	</div>
</form>
<script type=\"text/javascript\">
	// INIT find names
	formobj = document.getElementById('postingform');
	formobj.entered_name.autocomplete = 'off';
	init_js( 'postingform', 'entered_name', 'get-member-names');
	// Run main loop
	setTimeout( 'main_loop()', 10 );
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:form_simple_button:desc::trigger:>
//===========================================================================
function form_simple_button() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&nbsp;<input class='button' type=\"button\" value=\"{$this->ipsclass->lang['so_less_opts']}\" onclick=\"go_gadget_simple()\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_group:desc::trigger:>
//===========================================================================
function member_group($title="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_group']} $title";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_email:desc::trigger:>
//===========================================================================
function member_icon_email($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=Mail&amp;CODE=00&amp;MID={$id}\"><{P_EMAIL}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_msg:desc::trigger:>
//===========================================================================
function member_icon_msg($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=04&amp;MID={$id}\"><{P_MSG}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_profile:desc::trigger:>
//===========================================================================
function member_icon_profile($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}showuser={$id}\"><{P_PROFILE}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_vcard:desc::trigger:>
//===========================================================================
function member_icon_vcard($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=Profile&amp;CODE=showcard&amp;MID={$id}','AddressCard','600','300','0','1','1','1')\" title=\"{$this->ipsclass->lang['ac_title']}\"><{P_CARD}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_joined:desc::trigger:>
//===========================================================================
function member_joined($date="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_joined']} $date";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_location:desc::trigger:>
//===========================================================================
function member_location($location="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_location']} $location<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_number:desc::trigger:>
//===========================================================================
function member_number($number="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['member_no']} $number";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_posts:desc::trigger:>
//===========================================================================
function member_posts($posts="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_posts']} $posts";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_rank_img:desc::trigger:>
//===========================================================================
function member_rank_img($filename="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"$filename\" alt=\"{$this->ipsclass->lang['group_icon']}\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:no_results_row:desc::trigger:>
//===========================================================================
function no_results_row() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- Begin Topic Entry {$data['tid']} -->
	<tr>
		<td align=\"center\" colspan=\"8\" class=\"row1\"><b>{$this->ipsclass->lang['no_search_topics']}</b></td>
	</tr>
    <!-- End Topic Entry {$data['tid']} -->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:render_row_hidden:desc::trigger:>
//===========================================================================
function render_row_hidden($post="",$author=array()) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div id='post-ignore-{$post['pid']}' style='display:none'>
 <div class=\"postcolor\" id='post-{$post['pid']}'>
   <strong>{$this->ipsclass->lang['ignore_first_line']} {$post['members_display_name']}.</strong>
   <br />
   <br />
   &middot; <a href=\"#\" onclick=\"return topic_show_ignored_post('{$post['pid']}')\">{$this->ipsclass->lang['ignore_view_post']}</a>
   <br />
   &middot; <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=ignoreremove&amp;id={$author['id']}\">{$this->ipsclass->lang['ignore_unignore']} {$post['members_display_name']}</a>
 </div>
</div>
<script type=\"text/javascript\">
//<![CDATA[
topic_init_ignored_post( '{$post['pid']}' );
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:RenderPostRow:desc::trigger:>
//===========================================================================
function RenderPostRow($data="",$author="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<div class=\"borderwrap\">
	<div class=\"maintitle\">{$data['prefix']} <a href=\"{$this->ipsclass->base_url}showtopic={$data['tid']}&amp;hl={$data['keywords']}\">{$data['topic_title']}</a></div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td width=\"150\" class=\"post_head\">
				" . (($author['id']) ? ("
					<div id=\"post-member-{$data['pid']}\" class='popmenubutton-new-out'>
						<span class=\"normalname\">{$author['_pp_online_image']}{$author['_members_display_name']}</span>
					</div>
					<!-- member menu -->
					<div class='popupmenu-new' id='post-member-{$data['pid']}_menu' style='display:none;width:230px'>
						<div class='popupmenu-item-last'>
							" . (($author['members_display_name_short'] != $author['members_display_name']) ? ("
								<div class='popupmenu-item'><strong>{$author['members_display_name']}</strong></div>
							") : ("")) . "
							<div style='float:right'>
								<div class='pp-image-thumb-wrap'>
									<img src='{$author['pp_thumb_photo']}' width='{$author['pp_thumb_width']}' height='{$author['pp_thumb_height']}' alt='' />
								</div>
								" . (($this->ipsclass->vars['pp_allow_member_rate']) ? ("
									<div style='margin-top:5px;margin-left:6px;'>
										<img src=\"{$this->ipsclass->vars['img_url']}/rating_{$author['_pp_rating_real']}_mini.gif\" alt='{$this->ipsclass->lang['rating_prefix']}: {$author['_pp_rating_real']}' style='vertical-align:middle' border='0' />
									</div>
								") : ("")) . "
							</div>
							<div class='popupmenu-item'>
								{$author['_pp_gender_image']} <a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\">{$this->ipsclass->lang['dd_view_profile']}</a>
							</div>
							" . (($this->ipsclass->member['id']) ? ("
								<div class='popupmenu-item'>
									" . ((in_array( $author['id'], array_keys( $this->ipsclass->member['_cache']['friends'] ) )) ? ("
										<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_remove_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=remove&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['dd_remove_friend']}</a>
									") : ("
										<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_add_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=add&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['dd_add_friend']}</a>
									")) . "
								</div>
								<div class='popupmenu-item'>
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/send_pm_small.png' alt='' border='0' /> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=4&amp;MID={$author['id']}\">{$this->ipsclass->lang['dd_send_pm']}</a>
								</div>
							") : ("")) . "
							<div class='popupmenu-item-last'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=getalluser&amp;mid={$author['id']}'>{$this->ipsclass->lang['dd_find_posts']}</a>
							</div>
						</div>
					</div>
					<!-- member menu -->
					<script type=\"text/javascript\">
						ipsmenu.register( \"post-member-{$data['pid']}\", '', 'popmenubutton-new', 'popmenubutton-new-out' );
					</script>
				") : ("
					<span class=\"normalname\">{$author['_members_display_name']}</span>
				")) . "			
			<!--<span class=\"normalname\">{$data['author_name']}</span>-->
			</td>
			<td class=\"post_head\" width=\"100%\"><span class='postdetails'>{$this->ipsclass->lang['rp_postedon']} {$data['post_date']}</span></td>
		</tr>
		<tr>
			<td class=\"{$data['class2']} post_left\" valign='top'>
				<span class=\"postdetails\">
					" . (($author['id'] AND $author['avatar']) ? ("
						<a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\" title=\"{$this->ipsclass->lang['dd_view_profile']}\">{$author['avatar']}</a><br /><br />
					") : ("
	        			{$author['avatar']}<br /><br />
					")) . "
					{$author['title']}<br />
					{$author['member_rank_img']}<br /><br />
					{$author['member_group']}<br />
					{$author['member_posts']}<br />
					{$author['member_joined']}<br />
					{$author['member_location']}
					{$author['member_number']}<br /><br />
				
					{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
				</span><br />
        		<img src=\"{$this->ipsclass->vars['img_url']}/spacer.gif\" alt=\"\" width=\"160\" height=\"1\" />
        	</td>
        	<td class=\"{$data['classposts']}\" width=\"100%\" id='post-main-{$data['pid']}' valign='top'><div class=\"postcolor\" id='post-{$data['pid']}' style='height:200px;overflow:auto'>{$data['post']} <!--IBF.ATTACHMENT_{$data['pid']}--></div></td>
        </tr>
        <tr>
        	<td class=\"formbuttonrow\">&nbsp;</td>
        	<td class=\"formbuttonrow\" style='text-align: left'>
        		{$this->ipsclass->lang['rp_forum']} <a href=\"{$this->ipsclass->base_url}showforum={$data['forum_id']}\">{$data['forum_name']}</a>
        		&middot; {$this->ipsclass->lang['rp_post']} <a href=\"{$this->ipsclass->base_url}act=findpost&amp;hl={$data['keywords']}&amp;pid={$data['pid']}\" class=\"linkthru\">#{$data['pid']}</a>
        		&middot; {$this->ipsclass->lang['rp_replies']} <b>{$data['topic_posts']}</b>
        		&middot; {$this->ipsclass->lang['rp_hits']} <b>{$data['views']}</b>
        	</td>
  		</tr>
  	</table>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:RenderRow:desc::trigger:>
//===========================================================================
function RenderRow($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- Begin Topic Entry {$data['tid']} -->
	<tr>
		<td align=\"center\" class=\"{$data['class1']}\">{$data['folder_img']}</td>
		<td align=\"center\" width=\"3%\" class=\"{$data['class2']}\">{$data['topic_icon']}</td>
		<td class=\"{$data['class1']}\">
			<table class='ipbtable' cellspacing=\"0\">
				<tr>
" . (($data['go_new_post'] != '') ? ("
<td valign=\"middle\">{$data['go_new_post']}</td>
") : ("")) . "
					<td width=\"100%\">
					<div style='float:right'>{$data['_rate_img']}</div>
					<div>{$data['prefix']} {$data['attach_img']}<a href=\"{$this->ipsclass->base_url}showtopic={$data['tid']}&amp;hl={$data['keywords']}\">{$data['title']}</a>  {$data['PAGES']}</div>
					</td>
				</tr>
			</table>
			<span class=\"desc\">{$data['description']}</span>
		</td>
		<td class=\"{$data['class1']}\" width=\"15%\"><span class=\"forumdesc\"><a href=\"{$this->ipsclass->base_url}showforum={$data['forum_id']}\" title=\"{$data['forum_full_name']}\">{$data['forum_name']}</a></span></td>
		<td align=\"center\" class=\"{$data['class2']}\" width='10%'>{$data['starter']}</td>
		<td align=\"center\" class=\"{$data['classposts']}\">{$data['posts']}</td>
		<td align=\"center\" class=\"{$data['class2']}\">{$data['views']}</td>
		<td class=\"{$data['class2']}\"><span class=\"desc\">{$data['last_post']}<br /><a href=\"{$this->ipsclass->base_url}showtopic={$data['tid']}&amp;view=getlastpost\">{$data['last_text']}</a> <b>{$data['last_poster']}</b></span></td>
	</tr>
<!-- End Topic Entry {$data['tid']} -->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:result_simple_header:desc::trigger:>
//===========================================================================
function result_simple_header($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type='text/javascript' src='jscripts/ipb_topic.js'></script>
<div class=\"plainborder\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['search_results']}</div>
	<div class=\"subtitle\">
		<div class=\"pagelinks\">{$this->ipsclass->lang['g_searched_for']} <b>{$data['keyword']}</b></div>
		<div align=\"right\">
			{$this->ipsclass->lang['g_results']} <b>{$data['start']} - {$data['end']}</b> {$this->ipsclass->lang['g_of_about']} <b>{$data['matches']}</b>.
			{$this->ipsclass->lang['g_search_took']} <b>{$data['ex_time']}</b> {$this->ipsclass->lang['g_seconds']}
		</div>
	</div>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:search_error_page:desc::trigger:>
//===========================================================================
function search_error_page($keywords="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['search_results']}</div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<th><b>{$this->ipsclass->lang['you_search_for']}</b> {$keywords}</th>
		</tr>
		<tr>
			<td class=\"row1\">{$this->ipsclass->lang['no_results_so_there_ha_ha']}<br /><br /><b><a href=\"{$this->ipsclass->base_url}act=search\">{$this->ipsclass->lang['search_again']}</a></b></td>
		</tr>
		<tr>
			<td class=\"catend\"><!-- no content --></td>
		</tr>
	</table>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:simple_form:desc::trigger:>
//===========================================================================
function simple_form($forums="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\">
<!--
function go_gadget_advanced(){
	window.location = \"{$this->ipsclass->js_base_url}act=Search&mode=adv&f={$this->ipsclass->input['f']}\";
}
function win_pop(){
	window.open(\"{$this->ipsclass->js_base_url}act=Search&CODE=explain\",\"WIN\",\"width=400,height=300,resizable=yes,scrollbars=yes\"); 
}
-->
</script>
<form action=\"{$this->ipsclass->base_url}act=Search&amp;CODE=simpleresults&amp;mode=simple\" method=\"post\" name=\"sForm\">
$hidden_fields
	<div class=\"borderwrap\">
		<div class=\"maintitle\"  align=\"center\">{$this->ipsclass->lang['search_options']}</div>
		<div class=\"subtitle\" align=\"center\">{$this->ipsclass->lang['key_search']}</div>
		<div class=\"tablepad\" align=\"center\">
			<input type=\"text\" maxlength=\"100\" size=\"40\" id=\"keywords\" name=\"keywords\" /><br />
			<label for=\"keywords\">{$this->ipsclass->lang['keysearch_text']}</label> <!--IBF.BOOLEAN_EXPLAIN-->
		</div>
		<div class=\"subtitle\" align=\"center\">{$this->ipsclass->lang['search_where']}</div>
		<div class=\"tablepad\" align=\"center\">
			{$forums}<br /><br />
			<b>{$this->ipsclass->lang['sf_show_me']}</b>
			<input type=\"radio\" name=\"sortby\" value=\"relevant\" id=\"sortby_one\" class=\"radiobutton\" />
			<label for=\"sortby_one\">{$this->ipsclass->lang['sf_most_r_f']}</label>&nbsp;
			<input type=\"radio\" name=\"sortby\" value=\"date\" id=\"sortby_two\" checked=\"checked\" class=\"radiobutton\" />
			<label for=\"sortby_two\">{$this->ipsclass->lang['sf_most_date']}</label>
		</div>
		<div class=\"formbuttonrow\" align=\"center\">
			<input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['do_search']}\" />&nbsp;
			<input class='button' type=\"button\" value=\"{$this->ipsclass->lang['so_more_opts']}\" onclick=\"go_gadget_advanced()\" />
		</div>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:start:desc::trigger:>
//===========================================================================
function start($data="",$extra="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src=\"jscripts/ipb_forum.js\"></script>
<div>{$data['SHOW_PAGES']} $extra</div>
<br />
<div class=\"borderwrap\">
	<div class=\"maintitle\">
		<div style=\"float: left;\">{$this->ipsclass->lang['your_results']}</div>
		<div align=\"right\"><a href=\"{$this->ipsclass->base_url}act=Login&amp;CODE=05\">{$this->ipsclass->lang['mark_search_as_read']}</a></div>
	</div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<th colspan=\"2\">&nbsp;</th>
			<th>{$this->ipsclass->lang['h_topic_title']}</th>
			<th align=\"center\">{$this->ipsclass->lang['h_forum_name']}</th>
			<th align=\"center\">{$this->ipsclass->lang['h_topic_starter']}</th>
			<th align=\"center\">{$this->ipsclass->lang['h_replies']}</th>
			<th align=\"center\">{$this->ipsclass->lang['h_hits']}</th>
			<th>{$this->ipsclass->lang['h_last_action']}</th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:start_as_post:desc::trigger:>
//===========================================================================
function start_as_post($data="",$extra="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div>{$data['SHOW_PAGES']} $extra</div>
<script type='text/javascript' src='jscripts/ipb_topic.js'></script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topic_rating_image:desc::trigger:>
//===========================================================================
function topic_rating_image($rating_id='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src='{$this->ipsclass->vars['img_url']}/rating_{$rating_id}_mini.gif' border='0' alt='{$rating_id}' />&nbsp;";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_level_rating:desc::trigger:>
//===========================================================================
function warn_level_rating($id="",$level="",$min=0,$max=10) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&lt;&nbsp;$min ( <a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')\">{$level}</a> ) $max&nbsp;&gt;";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_level_warn:desc::trigger:>
//===========================================================================
function warn_level_warn($id="",$percent="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['tt_warn']} (<a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')\">{$percent}</a>%)";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xmlout_gnp_row:desc::trigger:>
//===========================================================================
function xmlout_gnp_row($tid="",$mini_title="",$real_title="",$date="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='popupmenu-item'>
 <table width='100%'>
 	<tr>
 		<td style='padding:2px;'><a style='font-size:10px' href='{$this->ipsclass->base_url}showtopic={$tid}' onclick='locationjump(\"showtopic={$tid}\");' title='$real_title'>{$mini_title}</a></td>
 		<td style='padding:2px;' align='right'>
 		  <span style='font-size:10px' class='desc'><em>({$date})</em></span>
  			<a href='{$this->ipsclass->base_url}showtopic={$tid}&amp;view=getnewpost' onclick='locationjump(\"showtopic={$tid}&amp;view=getnewpost\");'><img src='{$this->ipsclass->vars['img_url']}/lastpost.gif' alt='' border='0' /></a>
  		</td>
  	</tr>
  </table>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xmlout_gnp_wrapper:desc::trigger:>
//===========================================================================
function xmlout_gnp_wrapper($html="",$previous="",$next="",$st="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='pp-contentbox-back'>
	<div class='pp-contentbox-entry-noheight' style='padding:0px'>
	  <div style='padding:1px;padding-bottom:2px;'>
	   $html
	  </div>
	  " . (($st OR $next) ? ("
	   <div class='darkrow3' style='padding:6px' align='center'>
		" . (($st > 0) ? ("
		&laquo; <a style='font-size:10px' href='#' onclick='return xml_show_new_posts(\"{$previous}\");'>{$this->ipsclass->lang['tpl_next']}</a>
		") : ("")) . "
		  &nbsp; &nbsp;  &nbsp; &nbsp;
		" . (($next > 0) ? ("
		<a style='font-size:10px' href='#' onclick='return xml_show_new_posts(\"{$next}\");'>{$this->ipsclass->lang['tpl_prev']}</a> &raquo;
		") : ("")) . "
	  </div>
	 ") : ("")) . "
	</div>
</div>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
Form,RenderPostRow,result_simple_header,search_error_page,simple_form,start
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>