<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_mlist_3 {

 var $ipsclass;
//===========================================================================
// <ips:member_group:desc::trigger:>
//===========================================================================
function member_group($title="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_group']} $title";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_email:desc::trigger:>
//===========================================================================
function member_icon_email($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=Mail&amp;CODE=00&amp;MID={$id}\"><{P_EMAIL}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_msg:desc::trigger:>
//===========================================================================
function member_icon_msg($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=04&amp;MID={$id}\"><{P_MSG}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_profile:desc::trigger:>
//===========================================================================
function member_icon_profile($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}showuser={$id}\"><{P_PROFILE}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_vcard:desc::trigger:>
//===========================================================================
function member_icon_vcard($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=Profile&amp;CODE=showcard&amp;MID={$id}','AddressCard','600','300','0','1','1','1')\" title=\"{$this->ipsclass->lang['ac_title']}\"><{P_CARD}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_joined:desc::trigger:>
//===========================================================================
function member_joined($date="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_joined']} $date";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_list_show:desc::trigger:>
//===========================================================================
function member_list_show($members="",$pages="",$quickjump="",$checked="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- SEARCH FORM -->
<form action=\"{$this->ipsclass->base_url}act=members\" method=\"post\">
	<div class=\"borderwrap\">
		<div class=\"maintitle\" style='height:20px'>
			<div style=\"float: right;\"><input type=\"button\" class=\"button\" value=\"{$this->ipsclass->lang['toggle_more']}\" onclick=\"toggleview('mlist');\" /></div>
			<div style='padding-top:4px'>{$this->ipsclass->lang['title_search']}</div>
		</div>
		<div class=\"tablepad\" align=\"center\">
			<table class='ipbtable' cellspacing=\"0\">
				<tr>
					<td width=\"35%\" valign=\"top\">
						<fieldset style='height:45px'>
						<legend><b>{$this->ipsclass->lang['s_name']}</b></legend>
							<select name=\"name_box\">
								<option value=\"begins\">{$this->ipsclass->lang['s_begins']}</option>
								<option value=\"contains\">{$this->ipsclass->lang['s_contains']}</option>
							</select>&nbsp;&nbsp;<input type=\"text\" size=\"15\" name=\"name\" value=\"{$this->ipsclass->input['name']}\" />
						</fieldset>
					</td>
					<td width=\"25%\" valign=\"top\">
						<fieldset style='height:45px'>
						<legend><b>{$this->ipsclass->lang['member_photo']}</b></legend>
							<input class='checkbox' type=\"checkbox\" value=\"1\" name=\"photoonly\" $checked /> {$this->ipsclass->lang['photo_only']}
						</fieldset>
					</td>
					<td width=\"15%\" valign=\"top\">
						<fieldset style='height:45px'>
						<legend><b>{$this->ipsclass->lang['m_gender_s']}</b></legend>
							<select name='pp_gender'>
								" . ((! $this->ipsclass->input['pp_gender'] OR $this->ipsclass->input['pp_gender'] == 'any') ? ("
									<option value='any' selected='selected'>{$this->ipsclass->lang['m_gender_a']}</option>
								") : ("
									<option value='any'>{$this->ipsclass->lang['m_gender_a']}</option>
								")) . "
								" . (($this->ipsclass->input['pp_gender'] == 'male') ? ("
									<option value='male' selected='selected'>{$this->ipsclass->lang['m_gender_m']}</option>
								") : ("
									<option value='male'>{$this->ipsclass->lang['m_gender_m']}</option>
								")) . "
								" . (($this->ipsclass->input['pp_gender'] == 'female') ? ("
									<option value='female' selected='selected'>{$this->ipsclass->lang['m_gender_f']}</option>
								") : ("
									<option value='female'>{$this->ipsclass->lang['m_gender_f']}</option>
								")) . "
							</select>
						</fieldset>
					</td>
					" . (($this->ipsclass->vars['pp_allow_member_rate']) ? ("
					<td width=\"25%\" valign=\"top\">
						<fieldset style='height:45px'>
						<legend><b>{$this->ipsclass->lang['m_rating']}</b></legend>
							{$this->ipsclass->lang['m_rating_morethan']}
							<select name='pp_rating_real'>
								" . ((! $this->ipsclass->input['pp_rating_real']) ? ("
									<option value='0' selected='selected'>0</option>
								") : ("
									<option value='0'>0</option>
								")) . "
								" . (($this->ipsclass->input['pp_rating_real'] == 1) ? ("
									<option value='1' selected='selected'>1</option>
								") : ("
									<option value='1'>1</option>
								")) . "
								" . (($this->ipsclass->input['pp_rating_real'] == 2) ? ("
									<option value='2' selected='selected'>2</option>
								") : ("
									<option value='2'>2</option>
								")) . "
								" . (($this->ipsclass->input['pp_rating_real'] == 3) ? ("
									<option value='3' selected='selected'>3</option>
								") : ("
									<option value='3'>3</option>
								")) . "
								" . (($this->ipsclass->input['pp_rating_real'] == 4) ? ("
									<option value='4' selected='selected'>4</option>
								") : ("
									<option value='4'>4</option>
								")) . "
							</select>
						</fieldset>
					</td>
					") : ("")) . "
				</tr>
			</table>
			<!-- START HIDE -->
	<div style=\"display: none;\" id=\"mlist\">
		<table class='ipbtable' cellspacing=\"0\">
			<tr>
				
				<td width=\"50%\" valign=\"top\">
					<fieldset>
					<legend><b>{$this->ipsclass->lang['s_homepage']}</b></legend>
						<input type=\"text\" size=\"50\" name=\"homepage\" value=\"{$this->ipsclass->input['homepage']}\" />
					</fieldset>
				</td>
				<td width=\"50%\" valign=\"top\">
					<fieldset>
						<legend><b>{$this->ipsclass->lang['s_signature']}</b></legend>
							<input type=\"text\" size=\"50\" name=\"signature\" value=\"{$this->ipsclass->input['signature']}\" />
					</fieldset>
				</td>
			</tr>
			<tr>
				<td width=\"50%\" valign=\"top\">
					<fieldset>
					<legend><b>{$this->ipsclass->lang['title_messengers']}</b></legend>
						<table class='ipbtable' cellspacing=\"0\">
							<tr>
								<td width=\"60%\">{$this->ipsclass->lang['s_aim']}</td>
								<td width=\"40%\"><input type=\"text\" size=\"20\" name=\"aim\" value=\"{$this->ipsclass->input['aim']}\" /></td>
							</tr>
							<tr>
								<td width=\"60%\">{$this->ipsclass->lang['s_yahoo']}</td>
								<td width=\"40%\"><input type=\"text\" size=\"20\" name=\"yahoo\" value=\"{$this->ipsclass->input['yahoo']}\" /></td>
							</tr>
							<tr>
								<td width=\"60%\">{$this->ipsclass->lang['s_icq']}</td>
								<td width=\"40%\"><input type=\"text\" size=\"20\" name=\"icq\" value=\"{$this->ipsclass->input['icq']}\" /></td>
							</tr>
							<tr>
								<td width=\"60%\">{$this->ipsclass->lang['s_msn']}</td>
								<td width=\"40%\"><input type=\"text\" size=\"20\" name=\"msn\" value=\"{$this->ipsclass->input['msn']}\" /></td>
							</tr>
						</table>
					</fieldset>
				</td>
				<td width=\"50%\" valign=\"top\">
					<fieldset>
					<legend><b>{$this->ipsclass->lang['title_date']}</b></legend>
						<table class='ipbtable' cellspacing=\"0\">
							<tr>
								<td width=\"30%\">{$this->ipsclass->lang['s_posts']}</td>
								<td width=\"70%\">
									<select class=\"dropdown\" name=\"posts_ltmt\">
										<option value=\"lt\">{$this->ipsclass->lang['s_lessthan']}</option>
										<option value=\"mt\">{$this->ipsclass->lang['s_morethan']}</option>
									</select>
									&nbsp;<input type=\"text\" size=\"15\" name=\"posts\" value=\"{$this->ipsclass->input['posts']}\" />
								</td>
							</tr>
							<tr>
								<td width=\"30%\">{$this->ipsclass->lang['s_joined']}</td>
								<td width=\"70%\">
									<select class=\"dropdown\" name=\"joined_ltmt\">
										<option value=\"lt\">{$this->ipsclass->lang['s_lessthan']}</option>
										<option value=\"mt\">{$this->ipsclass->lang['s_morethan']}</option>
									</select>
									&nbsp;<input type=\"text\" size=\"10\" name=\"joined\" value=\"{$this->ipsclass->input['joined']}\" /> <span class=\"desc\">{$this->ipsclass->lang['s_dateformat']}</span>
								</td>
							</tr>
							<tr>
								<td width=\"30%\">{$this->ipsclass->lang['s_lastpost']}</td>
								<td width=\"70%\">
									<select class=\"dropdown\" name=\"lastpost_ltmt\">
										<option value=\"lt\">{$this->ipsclass->lang['s_lessthan']}</option>
										<option value=\"mt\">{$this->ipsclass->lang['s_morethan']}</option>
									</select>
									&nbsp;<input type=\"text\" size=\"10\" name=\"lastpost\" value=\"{$this->ipsclass->input['lastpost']}\" /> <span class=\"desc\">{$this->ipsclass->lang['s_dateformat']}</span>
								</td>
							</tr>
							<tr>
								<td width=\"30%\">{$this->ipsclass->lang['s_lastvisit']}</td>
								<td width=\"70%\">
									<select class=\"dropdown\" name=\"lastvisit_ltmt\">
										<option value=\"lt\">{$this->ipsclass->lang['s_lessthan']}</option>
										<option value=\"mt\">{$this->ipsclass->lang['s_morethan']}</option>
									</select>
									&nbsp;<input type=\"text\" size=\"10\" name=\"lastvisit\" value=\"{$this->ipsclass->input['lastvisit']}\" /> <span class=\"desc\">{$this->ipsclass->lang['s_dateformat']}</span>
								</td>
							</tr>
						</table>
					</fieldset>
				</td>
			</tr>
		</table>
		<!--CUSTOM_FIELDS-->
	</div>
		<!-- END HIDE -->
	</div>
		<div align=\"center\" class=\"formbuttonrow\">{$this->ipsclass->lang['sorting_text']}&nbsp;<input type=\"submit\" value=\"{$this->ipsclass->lang['sort_submit']}\" class=\"button\" /></div>
	</div>
</form>
<!--FORM-->
<br />
<div>{$pages}</div>
<br />
<div class=\"borderwrap\">
	<div class=\"maintitle\" style='height:20px'>
		<div style=\"float: right;\">
			<form name=\"quickjumpform\" action=\"{$this->ipsclass->base_url}act=members\" method=\"post\">
				<input type=\"submit\" name=\"qjbutton\" value=\"{$this->ipsclass->lang['button_quickjump']}\" class=\"button\" />
				<select name=\"quickjump\">
					{$quickjump}
				</select>
			</form>
		</div>
		<div style='padding-top:3px'>{$this->ipsclass->lang['page_title']}</div>
	</div>
	
	<div id='pp-iframe-wrap' class='pp-contentbox-back'>
	<table class='ipbtable' cellspacing=\"1\">
	<tr>
	" . ((is_array( $members ) and count( $members )) ? ("
		".$this->__foreach_loop__id_491a6170dcecf($members,$pages,$quickjump,$checked)."
		</tr>
	") : ("
		<tr>
			<td class=\"row2\" colspan=\"7\" align=\"center\">{$this->ipsclass->lang['no_results']}</td>
		</tr>
	")) . "
	</table>
	</div>
</div>
<br />
<div>$pages</div>";
//--endhtml--//
return $IPBHTML;
}


//===========================================================================
// Foreach loop function
//===========================================================================

function __foreach_loop__id_491a6170dcecf($members="",$pages="",$quickjump="",$checked="")
{
	$_ips___x_retval = '';
	
	foreach( $members as $member )
	{
		
		$_ips___x_retval .= "
			<!-- Entry for {$member['members_display_name']} -->
			" . (($member['_new_row']) ? ("
				</tr>
				<tr>
			") : ("")) . "
			" . (($member['_blank']) ? ("
				<td valign='top' width='25%'>&nbsp;</td>
			") : ("
				<td class='pp-contentbox-entry-noheight' valign='top' width='20%'>
					<div id=\"post-member-{$member['id']}\" class='popmenubutton-new-out' style='height:36px; margin-bottom:3px'>
						<div class='pp-image-mini-wrap-floatright' style='margin-right:10px'><img src='{$member['pp_mini_photo']}' width='{$member['pp_mini_width']}' height='{$member['pp_mini_height']}' alt='' /></div>
						<div style='margin-top:4px'>
							{$member['_pp_gender_image']}<strong><a href=\"{$this->ipsclass->base_url}showuser={$member['id']}\">{$member['members_display_name_short']}</a></strong>
							" . (($this->ipsclass->vars['pp_allow_member_rate']) ? ("
								<div style='margin-left:15px;'>
									<img src=\"{$this->ipsclass->vars['img_url']}/rating_{$member['_pp_rating_real']}_mini.gif\" alt='{$this->ipsclass->lang['rating_prefix']}: {$member['_pp_rating_real']}' style='vertical-align:middle' border='0' />
								</div>
							") : ("")) . "
						</div>
					</div>
					<!-- member menu -->
					<div class='popupmenu-new' id='post-member-{$member['id']}_menu' style='display:none;width:230px;'>
						<div class='popupmenu-item-last'>
							" . (($member['members_display_name_short'] != $member['_members_display_name']) ? ("
								<div class='popupmenu-item'><strong>{$member['members_display_name']}</strong></div>
							") : ("")) . "
							<div class='pp-image-thumb-wrap-floatright'><img src='{$member['pp_thumb_photo']}' width='{$member['pp_thumb_width']}' height='{$member['pp_thumb_height']}' alt='' /></div>
							<div class='popupmenu-item'>
								{$member['_pp_gender_image']} <a href=\"{$this->ipsclass->base_url}showuser={$member['id']}\">{$this->ipsclass->lang['m_view_profile']}</a>
							</div>
							" . (($this->ipsclass->member['id']) ? ("
								<div class='popupmenu-item'>
									" . ((in_array( $member['id'], array_keys( $this->ipsclass->member['_cache']['friends'] ) )) ? ("
										<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_remove_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=remove&amp;member_id={$member['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['m_remove_friend']}</a>
									") : ("
										<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_add_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=add&amp;member_id={$member['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['m_add_friend']}</a>
									")) . "
								</div>
								<div class='popupmenu-item'>
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/send_pm_small.png' alt='' border='0' /> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=4&amp;MID={$member['id']}\">{$this->ipsclass->lang['m_send_message']}</a>
								</div>
								<div class='popupmenu-item'>
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=gettopicsuser&amp;mid={$member['id']}'>{$this->ipsclass->lang['dd_find_topics']}</a>
								</div>		
							") : ("")) . "
							<div class='popupmenu-item-last'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=getalluser&amp;mid={$member['id']}'>{$this->ipsclass->lang['m_find_posts']}</a>
							</div>
						</div>
					</div>
					<!-- member menu -->
					<script type=\"text/javascript\">
						ipsmenu.register( \"post-member-{$member['id']}\", '', 'popmenubutton-new', 'popmenubutton-new-out' );
					</script>
				
					<strong>{$member['member_rank_img']}</strong>
					<div class='pp-tiny-text'>
						{$member['_pp_online_image']}{$member['_last_active']}
						<br />{$member['group']}
						<br /><b>{$this->ipsclass->lang['member_joined']}:</b> {$member['joined']}
						<br /><b>{$this->ipsclass->lang['member_posts']}:</b> {$member['posts']}
						<br /><b>{$this->ipsclass->lang['m_views']}:</b> {$member['_pp_profile_views']}
					</div>
				</td>
			")) . "
			<!-- End of Entry -->
		";
	}
	
	return $_ips___x_retval;
}

//===========================================================================
// <ips:member_location:desc::trigger:>
//===========================================================================
function member_location($location="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_location']} $location<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_number:desc::trigger:>
//===========================================================================
function member_number($number="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['member_no']} $number";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_posts:desc::trigger:>
//===========================================================================
function member_posts($posts="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_posts']} $posts";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_rank_img:desc::trigger:>
//===========================================================================
function member_rank_img($filename="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"$filename\" alt=\"{$this->ipsclass->lang['group_icon']}\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mlist_custom_field_dropdown:desc::trigger:>
//===========================================================================
function mlist_custom_field_dropdown($name="",$options="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<select name=\"$name\">
	<option value=\"\" selected=\"selected\">{$this->ipsclass->lang['s_any']}</option>
	$options
</select>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mlist_custom_field_entry:desc::trigger:>
//===========================================================================
function mlist_custom_field_entry($title="",$content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td valign=\"top\"><b>$title</b></td>
	<td>$content</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mlist_custom_field_textinput:desc::trigger:>
//===========================================================================
function mlist_custom_field_textinput($name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<input type=\"text\" size=\"50\" name=\"$name\" value=\"\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mlist_custom_field_wrap:desc::trigger:>
//===========================================================================
function mlist_custom_field_wrap($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div>
	<fieldset>
 	<legend><b>{$this->ipsclass->lang['title_options']}</b></legend>
 		<table class='ipbtable' cellspacing=\"0\">
 			<tr>
 				<td>$data</td>
 			</tr>
		</table>
	</fieldset>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mlist_quick_jump_entry:desc::trigger:>
//===========================================================================
function mlist_quick_jump_entry($letter="",$selected="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<option value=\"$letter\"{$selected}>$letter</option>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_level_rating:desc::trigger:>
//===========================================================================
function warn_level_rating($id="",$level="",$min=0,$max=10) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&lt;&nbsp;$min ( <a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')\">{$level}</a> ) $max&nbsp;&gt;";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_level_warn:desc::trigger:>
//===========================================================================
function warn_level_warn($id="",$percent="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['tt_warn']} (<a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')\">{$percent}</a>%)";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
member_list_show
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>