<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_buddy_3 {

 var $ipsclass;
//===========================================================================
// <ips:append_view:desc::trigger:>
//===========================================================================
function append_view($url="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "( <b><a href=\"javascript:redirect_to('$url', 0)\">{$this->ipsclass->lang['view_link']}</a></b> )";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:buddy_js:desc::trigger:>
//===========================================================================
function buddy_js() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script language='javascript' type=\"text/javascript\">
<!--
 function redirect_to(where, closewin)
 {
 	opener.location= '{$this->ipsclass->base_url}' + where;
 	
 	if (closewin == 1)
 	{
 		self.close();
 	}
 }
 
 function check_form(helpform)
 {
 	opener.name = \"ibfmain\";
 
 	if (helpform == 1) {
 		document.theForm2.target = 'ibfmain';
 	} else {
 		document.theForm.target = 'ibfmain';
 	}
 	
 	return true;
 }
 
 function shrink()
 {
 	window.resizeTo('200','75');
 }
 
 function expand()
 {
 	window.resizeTo('200','450');
 }
 
 
-->
 </script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:build_away_msg:desc::trigger:>
//===========================================================================
function build_away_msg() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['new_posts']}
<br />
{$this->ipsclass->lang['my_replies']}";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:closelink:desc::trigger:>
//===========================================================================
function closelink() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<p><a href=\"javascript:window.location=window.location;\">{$this->ipsclass->lang['refresh']}</a> / <a href=\"javascript:self.close();\">{$this->ipsclass->lang['close_win']}</a></p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:login:desc::trigger:>
//===========================================================================
function login() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}act=Login&amp;CODE=01&amp;CookieDate=1&amp;buddy=1\" method=\"post\" name=\"theForm\" onSubmit=\"return check_form();\">
	<div class=\"borderwrap\">
		<h3>{$this->ipsclass->lang['page_title']}</h3>
		<div class=\"formsubtitle\" align=\"center\">{$this->ipsclass->lang['log_in_needed']}</div>
			<p>{$this->ipsclass->lang['no_guests']}</p>
			<div class=\"formsubtitle\" align=\"center\">{$this->ipsclass->lang['log_in']}</div>
			<div class=\"fieldwrap\">
				<h4>{$this->ipsclass->lang['lin_name']}</h4>
				<input type=\"text\" name=\"UserName\" />
				<h4>{$this->ipsclass->lang['lin_pass']}</h4>
				<input type=\"password\" name=\"PassWord\" />
				<input type=\"submit\" value=\"{$this->ipsclass->lang['log_in']}\" class=\"button\" />
			</div>
			<p>{$this->ipsclass->lang['reg_text']}<br /><a href=\"javascript:redirect_to('&amp;act=Reg', 1);\">{$this->ipsclass->lang['reg_link']}</a></p>
	<div align=\"center\"><!--CLOSE.LINK--></div>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:main:desc::trigger:>
//===========================================================================
function main($away_text="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<h3>{$this->ipsclass->lang['page_title']}</h3>
	<div class=\"formsubtitle\">{$this->ipsclass->lang['while_away']}</div>
	<p>{$away_text}</p>
	<div class=\"formsubtitle\">{$this->ipsclass->lang['show_me']}</div>
	<p><a href=\"javascript:redirect_to('&amp;act=Stats&amp;CODE=leaders',0)\">{$this->ipsclass->lang['sm_forum_leaders']}</a><br /><a href=\"javascript:redirect_to('&amp;act=Stats',0)\">{$this->ipsclass->lang['sm_today_posters']}</a><br /><a href=\"javascript:redirect_to('&amp;act=Members&amp;max_results=10&amp;sort_key=posts&amp;sort_order=desc',0)\">{$this->ipsclass->lang['sm_all_posters']}</a><br /><a href=\"javascript:redirect_to('&amp;act=Search&amp;CODE=lastten',0)\">{$this->ipsclass->lang['sm_my_last_posts']}</a></p>
	<div class=\"formsubtitle\" align=\"center\">{$this->ipsclass->lang['search_forums']}</div>
	<div align=\"center\">
		<form action=\"{$this->ipsclass->base_url}act=Search&amp;CODE=01&amp;forums=all&amp;cat_forum=forum&amp;joinname=1&amp;search_in=posts&amp;result_type=topics\" method=\"post\" name=\"theForm\" onsubmit=\"return check_form();\">
			<input type=\"text\" size=\"17\" name=\"keywords\" />&nbsp;<input class=\"gobutton\" type=\"image\" src=\"{$this->ipsclass->vars['img_url']}/login-button.gif\" value=\"{$this->ipsclass->lang['go']}\" />
		</form>
	</div>
	<div class=\"formsubtitle\" align=\"center\">{$this->ipsclass->lang['search_help']}</div>
	<div align=\"center\">
		<form action=\"{$this->ipsclass->base_url}act=Help&amp;CODE=02\" method=\"post\" name=\"theForm2\" onsubmit=\"return check_form(1);\">
			<input type=\"text\" size=\"17\" name=\"search_q\" />&nbsp;<input class=\"gobutton\" type=\"image\" src=\"{$this->ipsclass->vars['img_url']}/login-button.gif\" value=\"{$this->ipsclass->lang['go']}\" />
		</form>
	</div>
	<div><!--CLOSE.LINK--></div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xml_nonewpms:desc::trigger:>
//===========================================================================
function xml_nonewpms() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='pp-contentbox-back'>
	<div class='pp-contentbox-entry-noheight'>
		{$this->ipsclass->lang['nonew_pms_myass']}
	</div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xml_search:desc::trigger:>
//===========================================================================
function xml_search() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='pp-contentbox-back'>
	<div class='pp-contentbox-entry-noheight'>
		<strong>{$this->ipsclass->lang['search_forums']}</strong>
	  	<input type=\"text\" onmouseover='this.focus()' size=\"17\" id='myass-search-input' name=\"keywords\" onkeydown=\"if(event.keyCode == 13){xml_myassistant_search();}\" />
	  	<input class=\"gobutton\" onclick='xml_myassistant_search()' type=\"image\" src=\"{$this->ipsclass->vars['img_url']}/login-button.gif\" value=\"{$this->ipsclass->lang['go']}\" />
	  	<div id='myass-search-message'></div>
	</div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xml_showme:desc::trigger:>
//===========================================================================
function xml_showme() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='pp-contentbox-back'>
	<div class='pp-contentbox-entry-noheight'>
	 <div class='mya-fieldwrap'>
	 <strong>{$this->ipsclass->lang['legend_forum']}</strong><br />
		&nbsp;&middot; <a href=\"{$this->ipsclass->base_url}act=Stats&amp;CODE=leaders\">{$this->ipsclass->lang['sm_forum_leaders']}</a>
	 </div>
	<br />
	 <div class='mya-fieldwrap'>
	 <strong>{$this->ipsclass->lang['legend_post']}</strong><br />
		&nbsp;&middot; <a href=\"{$this->ipsclass->base_url}act=Stats\">{$this->ipsclass->lang['sm_today_posters']}</a>
		<br />&nbsp;&middot; <a href=\"{$this->ipsclass->base_url}act=Members&amp;max_results=10&amp;sort_key=posts&amp;sort_order=desc\">{$this->ipsclass->lang['sm_all_posters']}</a>
		<br />&nbsp;&middot; <a href=\"{$this->ipsclass->base_url}act=Search&amp;CODE=lastten\">{$this->ipsclass->lang['sm_my_last_posts']}</a>
	 </div>
	</div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xml_tabs:desc::trigger:>
//===========================================================================
function xml_tabs($onoff="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='pp-tabwrap' style='margin-left:1px'>
   <div class='{$onoff['info']}'><a href='#' onclick='xml_myassistant_init(\"info\");return false;'>{$this->ipsclass->lang['tab_info']}</a></div>
   <div class='{$onoff['posts']}'><a href='#' onclick='xml_myassistant_init(\"posts\");return false;'>{$this->ipsclass->lang['tab_posts']}</a></div>
   <div class='{$onoff['search']}'><a href='#' onclick='xml_myassistant_init(\"search\");return false;'>{$this->ipsclass->lang['tab_search']}</a></div>
	" . (($this->ipsclass->member['members_disable_pm'] == 0 AND $this->ipsclass->member['g_use_pm'] == 1) ? ("
		<div class='{$onoff['pms']}'><a href='#' onclick='xml_myassistant_init(\"pms\");return false;'>{$this->ipsclass->lang['tab_pms']}</a></div>
	") : ("")) . "
	" . (($this->ipsclass->member['new_msg'] >= 1 AND $this->ipsclass->member['members_disable_pm'] == 0 AND $this->ipsclass->member['g_use_pm'] == 1) ? ("
		<div class='{$onoff['newpms']}'><a href='#' onclick='xml_myassistant_init(\"newpms\");return false;'>{$this->ipsclass->lang['tab_newpms']} ({$this->ipsclass->member['new_msg']})</a></div>
	") : ("")) . "
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xml_wrap:desc::trigger:>
//===========================================================================
function xml_wrap($content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='mya-back'>
 {$content}
</div>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>