<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_user_3 {

 var $ipsclass;
//===========================================================================
// <ips:img_view_top:desc::trigger:>
//===========================================================================
function img_view_top($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type='text/javascript' src='jscripts/ipb_topic.js'></script>
<table class=\"ipbtable\" cellspacing='0'>
	<tr>
		<td style='padding-left:0px;' nowrap=\"nowrap\">{$info['SHOW_PAGES']}</td>
		<td style='padding-right:0px;' align=\"right\">{$info['upload']}&nbsp;{$info['media']}&nbsp;{$info['multi_upload_button']}&nbsp;{$info['slideshow']}
		" . (($this->ipsclass->member['id']==$info['member_id'] and $this->ipsclass->input['op'] == 'view_album') ? ("
		 <a href='{$this->ipsclass->base_url}automodule=gallery&amp;req=albums&amp;op=addnew'><{GALLERY_NEW_ALBUM}></a>
		") : ("")) . "
		</td>
	</tr>
</table>
<div class='borderwrap'>
	<div class=\"maintitle\">{$info['where']}</div>
	<div class=\"subtitle\" style=\"text-align:left;\">{$info['description']}</div>
	
	<table class='ipbtable' cellspacing='0'>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_bar:desc::trigger:>
//===========================================================================
function user_bar($info="",$base_url='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class=\"ipbtable\" cellspacing='0'>
	<tr>
		<td class=\"nopad\" valign=\"top\" width=\"24%\">
			<div class=\"borderwrap\">
				<div class=\"maintitle\">{$info['name']}</div>
                         
				<div class=\"subtitle\">{$this->ipsclass->lang['user_stats']}</div>
				<p>
					&middot; <b>{$this->ipsclass->lang['total_imgs']}</b> {$info['total_images']}<br />
					&middot; <b>{$this->ipsclass->lang['total_comments']}</b> {$info['total_comments']}<br />
					&middot; <b>{$this->ipsclass->lang['dp_used']}</b> {$info['total_diskspace']}<br /> <i><!-- TOTAL_ALLOWED --></i>
					{$info['pub_albums']}
				</p>
				<!-- PRIVATE_ALBUMS -->
				<!-- CONTROLS -->
			</div>
		</td>
		<td width=\"1%\" class=\"nopad\">&nbsp;</td>
		<td class=\"nopad\" valign=\"top\" width=\"75%\">
		" . (($this->ipsclass->member['id']==$info['member_id'] and $this->ipsclass->input['op'] != 'view_album') ? ("
		 <div align='right'><a href='{$this->ipsclass->base_url}automodule=gallery&amp;req=albums&amp;op=addnew'><{GALLERY_NEW_ALBUM}></a></div>
		") : ("")) . "";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_bar_header:desc::trigger:>
//===========================================================================
function user_bar_header($text='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"subtitle\">{$text}</div>
				<p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_bar_public_albums:desc::trigger:>
//===========================================================================
function user_bar_public_albums($albums="",$mid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</p>
				<div class=\"subtitle\">{$this->ipsclass->lang['user_pub_albums']}</div>
				<p>
					&middot; <a href=\"{$this->ipsclass->base_url}automodule=gallery&amp;req=user&amp;user={$mid}&amp;op=ipbimages\"><b>{$this->ipsclass->lang['where_all_ipb']}</b></a><br />
					{$albums}";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:user_view_top_cat:desc::trigger:>
//===========================================================================
function user_view_top_cat($info='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class=\"ipbtable\">
	<tr>
		<td style='padding-left:0px;' nowrap=\"nowrap\" width=\"20%\">{$info['SHOW_PAGES']}</td>
		<td style='padding-right:0px;' align=\"right\">{$info['upload']}&nbsp;{$info['slideshow']}</td>
	</tr>
</table>
	
<div class='borderwrap'>
	<div class=\"maintitle\">{$this->ipsclass->lang['where_all']}</div>
   
	<table class='ipbtable' cellspacing='0'>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
img_view_top,user_bar,user_bar_header,user_bar_public_albums,user_view_top_cat
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>