<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_blog_post_3 {

 var $ipsclass;
//===========================================================================
// <ips:cblockname_fields:desc::trigger:>
//===========================================================================
function cblockname_fields($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
 	<td class='row1' style='width: 20%; text-align: right'>
		<strong>{$this->ipsclass->lang['blog_cblock_name']}</strong>
 	</td>
	<td class='row2'>
		<input type=\"text\" size=\"50\" maxlength=\"50\" name=\"CBlockTitle\" value=\"{$data['TITLE']}\" tabindex=\"1\" class=\"forminput\" />
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:entry_albums:desc::trigger:>
//===========================================================================
function entry_albums($albums="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
 	<td class='row1' style='width: 20%; text-align: right'>
		<strong>{$this->ipsclass->lang['entry_albums']}</strong>
 	</td>
	<td class='row2'>
		{$albums} <a href=\"{$this->ipsclass->base_url}automodule=gallery&amp;cmd=albums&amp;op=addnew\" target=\"_blank\">{$this->ipsclass->lang['entry_add_album']}</a>
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:entrytitle_fields:desc::trigger:>
//===========================================================================
function entrytitle_fields($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='subtitle' colspan='2'>Entry Details</td>
</tr>
<tr>
 	<td class='row1' style='width: 20%; text-align: right'>
		<strong>{$this->ipsclass->lang['entry_title']}</strong>
 	</td>
	<td class='row2'>
		<input type=\"text\" size=\"50\" maxlength=\"150\" name=\"EntryTitle\" value=\"{$data['TITLE']}\" tabindex=\"1\" class=\"forminput\" />
	</td>
</tr>
<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['entry_category']}</strong>
	</td>
	<td class='row2'>
		<select class='forminput' name='EntryCategory' tabindex=\"2\">{$data['CATEGORIES']}</select></span>
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_options:desc::trigger:>
//===========================================================================
function mod_options($jump="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
 	<td class='row1' style='width: 20%; text-align: right'>
		<strong>{$this->ipsclass->lang['blog_mod_options']}</strong>
 	</td>
	<td class='row2'>
		&nbsp;{$jump}</select>
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
cblockname_fields,entry_albums,entrytitle_fields,mod_options
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>