<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_msg_3 {

 var $ipsclass;
//===========================================================================
// <ips:address_add:desc::trigger:>
//===========================================================================
function address_add($mem_to_add="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src='jscripts/ipb_xhr_findnames.js'></script>
<div id='ipb-get-members' style='border:1px solid #000; background:#FFF; padding:2px;position:absolute;width:192px;display:none;z-index:1'></div>
<form action=\"{$this->ipsclass->base_url}\" method=\"post\" id=\"postingform\">
<input type=\"hidden\" name=\"act\" value=\"Msg\" />
<input type=\"hidden\" name=\"CODE\" value=\"09\" />
	<div class=\"subtitle\">{$this->ipsclass->lang['member_add']}</div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td class='row1' valign=\"middle\">{$this->ipsclass->lang['enter_a_name']}<br /><input type=\"text\" id='mem_name' name=\"mem_name\" size=\"30\" maxlength=\"40\" value=\"$mem_to_add\" /></td>
			<td class='row2' valign=\"middle\">{$this->ipsclass->lang['enter_desc']}<br /><input type=\"text\" name=\"mem_desc\" size=\"40\" maxlength=\"60\" value=\"\" /></td>
			<!--<td valign=\"middle\">{$this->ipsclass->lang['allow_msg']}<br /><select name=\"allow_msg\"><option value=\"yes\" selected=\"selected\">{$this->ipsclass->lang['yes']}</option><option value=\"no\">{$this->ipsclass->lang['no']}</option></select></td>-->
		</tr>
	</table>
	<div class=\"formbuttonrow\" align=\"center\"><input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['submit_address']}\" /></div>
</form>
<script type=\"text/javascript\">
// INIT find names
init_js( 'postingform', 'mem_name', 'get-member-names');
// Run main loop
setTimeout( 'main_loop()', 10 );
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:address_edit:desc::trigger:>
//===========================================================================
function address_edit($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}\" method=\"post\">
<input type=\"hidden\" name=\"act\" value=\"Msg\" />
<input type=\"hidden\" name=\"CODE\" value=\"12\" />
<input type=\"hidden\" name=\"MID\" value=\"{$data[MEMBER]['contact_id']}\"  />
	<div class=\"subtitle\">{$this->ipsclass->lang['member_edit']}</div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td class='row1' valign=\"middle\"><b>{$data[MEMBER]['contact_name']}</b></td>
			<td class='row2' valign=\"middle\">{$this->ipsclass->lang['enter_desc']}<br /><input type=\"text\" name=\"mem_desc\" size=\"30\" maxlength=\"60\" value=\"{$data[MEMBER]['contact_desc']}\" /></td>
			<!--<td valign=\"middle\">{$this->ipsclass->lang['allow_msg']}<br />{$data[SELECT]}</td>-->
		</tr>
	</table>
	<div class=\"formbuttonrow\" align=\"center\"><input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['submit_address_edit']}\" /></div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Address_header:desc::trigger:>
//===========================================================================
function Address_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"subtitle\">{$this->ipsclass->lang['address_current']}</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Address_none:desc::trigger:>
//===========================================================================
function Address_none() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<p class=\"pcen\">{$this->ipsclass->lang['address_none']}</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Address_table_header:desc::trigger:>
//===========================================================================
function Address_table_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
	<div class=\"borderwrapm\">
		<table class='ipbtable' cellspacing=\"0\">
			<tr>
				<th><b>{$this->ipsclass->lang['member_name']}</b></th>
				<th width=\"60%\"><b>{$this->ipsclass->lang['enter_block']}</b></th>
			</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:archive_complete:desc::trigger:>
//===========================================================================
function archive_complete() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\">{$this->ipsclass->lang['arc_comp_title']}</div>
	<p>{$this->ipsclass->lang['arc_complete']}</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:archive_form:desc::trigger:>
//===========================================================================
function archive_form($jump_html="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}\" method=\"post\">
<input type=\"hidden\" name=\"act\" value=\"Msg\" />
<input type=\"hidden\" name=\"CODE\" value=\"15\" />
	
<div class=\"subtitle\">{$this->ipsclass->lang['archive_title']}</div>
	<p>{$this->ipsclass->lang['archive_text']}</p>
		<table class='ipbtable' cellspacing=\"0\">
			<tr>
				<td class='row1'><b>{$this->ipsclass->lang['arc_folders']}</b></td>
				<td class='row2'>$jump_html</td>
			</tr>
			<tr>
				<td class='row1'><b>{$this->ipsclass->lang['arc_dateline']}</b></td>
				<td class='row2' valign=\"middle\">
					<select name=\"dateline\">
						<option value=\"1\">1</option>
						<option value=\"7\">7</option>
						<option value=\"30\" selected=\"selected\">30</option>
						<option value=\"90\">90</option>
						<option value=\"365\">365</option>
						<option value=\"all\">{$this->ipsclass->lang['arc_alldays']}</option>
					</select>
						&nbsp;&nbsp;{$this->ipsclass->lang['arc_days']}
					<select name=\"oldnew\">
						<option value=\"newer\" selected=\"selected\">{$this->ipsclass->lang['arch_new']}</option>
						<option value=\"older\">{$this->ipsclass->lang['arch_old']}</option>
					</select>
				</td>
			</tr>
			<tr>
				<td class='row1'><b>{$this->ipsclass->lang['arc_max']}</b></td>
				<td class='row2' valign=\"middle\"><select name=\"number\"><option value=\"5\">5</option><option value=\"10\">10</option><option value=\"20\" selected=\"selected\">20</option><option value=\"30\">30</option><option value=\"40\">40</option><option value=\"50\">50</option></select></td>
			</tr>
			<tr>
				<td class='row1'><b>{$this->ipsclass->lang['arc_delete']}</b></td>
				<td class='row2' valign=\"middle\"><select name=\"delete\"><option value=\"yes\">{$this->ipsclass->lang['arc_yes']}</option><option value=\"no\" selected=\"selected\">{$this->ipsclass->lang['arc_no']}</option></select></td>
			</tr>
			<tr>
				<td class='row1'><b>{$this->ipsclass->lang['arc_type']}</b></td>
				<td class='row2' valign=\"middle\"><select name=\"type\"><option value=\"xls\" selected=\"selected\">{$this->ipsclass->lang['arc_xls']}</option><option value=\"html\">{$this->ipsclass->lang['arc_html']}</option></select></td>
			</tr>
		</table>
		<div class=\"formbuttonrow\" align=\"center\"><input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['arc_submit']}\" /></div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:archive_html_entry:desc::trigger:>
//===========================================================================
function archive_html_entry($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrapm\">
	<div class=\"maintitle\">{$this->ipsclass->lang['pm_textbit']}{$info['msg_title']}</div>
	<div class=\"tablefill\"><div class=\"postcolor\">{$info['msg_content']}</div></div>
	<div class=\"formsubtitle\">{$this->ipsclass->lang['sentby_textbit']}<b>{$info['msg_sender']}</b> {$this->ipsclass->lang['on_textbit']} {$info['msg_date']}</div>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:archive_html_entry_sent:desc::trigger:>
//===========================================================================
function archive_html_entry_sent($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrapm\">
	<div class=\"maintitle\">{$this->ipsclass->lang['pm_textbit']}{$info['msg_title']}</div>
	<div class=\"tablefill\"><div class=\"postcolor\">{$info['msg_content']}</div></div>
	<div class=\"formsubtitle\">{$this->ipsclass->lang['sentto_textbit']}<b>{$info['msg_sender']}</b> {$this->ipsclass->lang['on_textbit']} {$info['msg_date']}</div>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:archive_html_footer:desc::trigger:>
//===========================================================================
function archive_html_footer() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</div>
</body>
</html>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:archive_html_header:desc::trigger:>
//===========================================================================
function archive_html_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<html>
<head>
<meta http-equiv=\"content-type\" content=\"text/html; charset={$this->ipsclass->vars['gb_char_set']}\" />
	<title>{$this->ipsclass->lang['pma_title']}</title>
	<style type=\"text/css\">
		html{
			overflow-x: auto;
		}
		
		body{
			background-color: #fff;
			color: #000;
			font-family: Verdana, Tahoma, Arial, sans-serif;
			font-size: 11px;
			margin:0px;
			padding:0px;
			text-align:center;
		   }
		   
		a:link, a:visited, a:active{
			color: #000;
			text-decoration: underline;
		}
		
		a:hover{
			color: #465584;
			text-decoration:underline;
		}
		
		img{
			border: 0;
			vertical-align: middle;
		}
				
		#ipbwrapper{
			margin: 0 auto 0 auto;
			text-align: left;
			width: 95%;
		}
		
		.post1{
			background-color: #F5F9FD;
		}
		
		.post2{
			background-color: #EEF2F7;
		}
	
		/* Common elements */
		.row1{
			background-color: #F5F9FD;
		}
		
		.row1{
			background-color: #DFE6EF;
		}
		
		.row3{
			background-color: #EEF2F7;
		}
		
		.row2{
			background-color: #E4EAF2;
		}
	
		/* tableborders gives the white column / row lines effect */
		.plainborder{
			background-color: #F5F9FD
			border: 1px solid #345487;
		}
		
		.tableborder{
			background-color: #FFF;
			border: 1px solid #345487;
			margin: 0;
			padding: 0;
		}
		
		.tablefill{
			background-color: #F5F9FD;
			border: 1px solid #345487;
			padding: 6px;
		}
		
		.tablepad{
			background-color: #F5F9FD;
			padding:6px;
		}
		
		.tablebasic{
			border: 0;
			margin: 0;
			padding: 0;
			width:100%;
		}
	
		.pformstrip{
			background-color: #D1DCEB;
			color: #3A4F6C;
			font-weight: bold;
			margin-top:1px
			padding:7px;
		}
		
		#QUOTE{
			background-color: #FAFCFE;
			border: 1px solid #000;
			color: #465584;
			font-family: Verdana, Arial;
			font-size: 11px;
			padding: 2px;
		}
		
		#CODE{
			background-color: #FAFCFE;
			border: 1px solid #000;
			color: #465584;
			font-family: Courier, Courier New, Verdana, Arial;
			font-size: 11px;
			padding: 2px;
		}
		/* Main table top (dark blue gradient by default) */
		.maintitle{
			background-color: #D1DCEB;
			background-image: url({$this->ipsclass->vars['board_url']}/style_images/<#IMG_DIR#>/tile_back.gif);
			color: #FFF;
			font-weight: bold;
			padding:8px 0px 8px 5px;
			vertical-align:middle;
		}
		
		.maintitle a:link, .maintitle  a:visited, .maintitle  a:active{
			color: #fff;
			text-decoration: none;
		}
		
		.maintitle a:hover{
			text-decoration: underline;
		}
		
		/* Topic View elements */
		.signature{
			color: #339;
			font-size: 10px;
			line-height:150%;
		}
		
		.postdetails{
			font-size: 10px;
		}
		
		.postcolor{
			font-size: 12px;
			line-height: 160%;
		}
	</style>
</head>
<body>
 <div id=\"ipbwrapper\">";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:cp_end:desc::trigger:>
//===========================================================================
function cp_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</div>
		</td>
	</tr>
</table>
	<!-- end main CP area -->
	<br style=\"clear: both;\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:empty_folder_footer:desc::trigger:>
//===========================================================================
function empty_folder_footer() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table>
			<div class=\"formbuttonrow\" align=\"center\"><input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['fd_continue']}\" /></div>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:empty_folder_header:desc::trigger:>
//===========================================================================
function empty_folder_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}\" method=\"post\">
<input type=\"hidden\" name=\"act\" value=\"Msg\" />
<input type=\"hidden\" name=\"CODE\" value=\"dofolderdelete\" />
<input type=\"hidden\" name=\"md5check\" value=\"{$this->ipsclass->md5_check}\" />
	<div class=\"subtitle\">{$this->ipsclass->lang['mi_prune_msg']}</div>
	<p>{$this->ipsclass->lang['fd_text']}</p>
	<div class=\"borderwrapm\">
		<table class='ipbtable' cellspacing=\"0\">
			<tr>
				<th>{$this->ipsclass->lang['fd_name']}</th>
				<th>{$this->ipsclass->lang['fd_count']}</th>
				<th>{$this->ipsclass->lang['fd_empty']}</th>
			</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:empty_folder_row:desc::trigger:>
//===========================================================================
function empty_folder_row($real="",$id="",$cnt="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
				<td class=\"row1\"><b>$real</b></td>
				<td class=\"row2\" align=\"center\">$cnt</td>
				<td class=\"row1\" align=\"center\"><input type=\"checkbox\" class=\"checkbox\" name=\"its_$id\" value=\"1\" /></td>
			</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:empty_folder_save_unread:desc::trigger:>
//===========================================================================
function empty_folder_save_unread() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
				<td class=\"formsubtitle\" colspan=\"3\" align=\"center\"><input type=\"checkbox\" class=\"checkbox\" name=\"save_unread\" value=\"1\" checked=\"checked\" /> <b>{$this->ipsclass->lang['fd_save_unread']}</b></td>
			</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:end_address_table:desc::trigger:>
//===========================================================================
function end_address_table() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table>
	</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:end_inbox:desc::trigger:>
//===========================================================================
function end_inbox($vdi_html="",$amount_info="",$pages="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
				<td align=\"right\" colspan=\"5\" class=\"formbuttonrow\">
					<input class='button' type=\"submit\" name=\"move\" value=\"{$this->ipsclass->lang['move_button']}\" /> $vdi_html {$this->ipsclass->lang['move_or_delete']} <input type=\"submit\" class='button' name=\"delete\" value=\"{$this->ipsclass->lang['delete_button']}\" /> {$this->ipsclass->lang['selected_msg']}
				</td>
			</tr>
		</table>
	</div>
</form>
<div style=\"padding: 5px;\">
	<div class=\"wrapmini\"><{M_READ}>&nbsp;{$this->ipsclass->lang['icon_read']}<br /><{M_UNREAD}>&nbsp;{$this->ipsclass->lang['icon_unread']}</div>
	<div align=\"right\">$pages<br /><i>$amount_info</i></div>
        <div style='clear: both'></div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:forum_jump:desc::trigger:>
//===========================================================================
function forum_jump($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
<div align=\"right\" class=\"row1\" style=\"padding: 5px;\">{$data}</div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:inbox_row:desc::trigger:>
//===========================================================================
function inbox_row($msg="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr id=\"{$msg['mt_id']}\">
			<td align=\"center\" valign=\"middle\" class=\"row1\">{$msg['icon']}</td>
			<td class=\"row2\">{$msg['attach_img']}&nbsp;<a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=03&amp;VID={$msg['mt_vid_folder']}&amp;MSID={$msg['mt_id']}\">{$msg['mt_title']}</a></td>
			<td class=\"row1\">{$msg['from_name']}</td>
			<td class=\"row2\">{$msg['date']}</td>
			<td align=\"center\" class=\"row1\"><input type=\"hidden\" name=\"{$msg['mt_id']}\" value=\"{$msg['mt_read']}\" /><input class='checkbox' type=\"checkbox\" name=\"msgid_{$msg['mt_id']}\" value=\"yes\" onclick=\"cca(this);\" /></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:inbox_table_header:desc::trigger:>
//===========================================================================
function inbox_table_header($dirname="",$info="",$vdi_html="",$pages="",$curvid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- inbox folder -->
<div class=\"subtitle\">$dirname</div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td valign=\"middle\">
				<!-- LEFT -->
				<table cellspacing=\"1\" style=\"width:250px\" class=\"inbox\">
					<tr>
						<td class=\"row1\" colspan=\"3\">{$info['full_messenger']}</td>
					</tr>
					<tr>
						<td valign=\"middle\" class=\"row1\" colspan=\"3\" nowrap='nowrap'><{BAR_LEFT}><img src=\"{$this->ipsclass->vars['img_url']}/bar.gif\" width=\"{$info['img_width']}\" height=\"15\" align=\"middle\" alt=\"\" /><{BAR_RIGHT}></td>
					</tr>
					<tr>
						<td class=\"row1\" width=\"33%\" valign=\"middle\">0%</td>
						<td class=\"row1\" width=\"33%\" align=\"center\" valign=\"middle\">50%</td>
						<td class=\"row1\" width=\"33%\" align=\"right\" valign=\"middle\">100%</td>
					</tr>
				</table>
			</td>
			
			<!-- RIGHT -->
			<td align=\"right\" valign=\"bottom\">
				$pages<br /><br />
				<a href=\"javascript:select_read()\">{$this->ipsclass->lang['pmpc_mark_read']}</a> :: <a href=\"javascript:unselect_all()\">{$this->ipsclass->lang['pmpc_unmark_all']}</a><br /><br />
				<form action=\"{$this->ipsclass->base_url}CODE=01&amp;act=Msg\" name=\"jump\" method=\"post\">
					<b>{$this->ipsclass->lang['goto_folder']}: </b>&nbsp; $vdi_html 
					<input class='button' type=\"submit\" name=\"submit\" value=\"{$this->ipsclass->lang['goto_submit']}\" />
				</form>
			</td>
		</tr>
	</table>
<!-- INBOX TABLE -->
  
<form action=\"{$this->ipsclass->base_url}CODE=06&amp;act=Msg\" name=\"mutliact\" method=\"post\">
<input type=\"hidden\" name=\"curvid\" value=\"$curvid\" />
<input type=\"hidden\" name=\"sort\" value=\"{$this->ipsclass->input['sort']}\" />
<input type=\"hidden\" name=\"st\" value=\"{$this->ipsclass->input['st']}\" />
<div class=\"borderwrapm\">
	<table class='ipbtable' cellspacing=\"0\" cellpadding='0'>
		<tr>
			<th width=\"5%\" style='padding:3px'>&nbsp;</th>
			<th width=\"35%\" style='padding:3px'><a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=01&amp;VID={$info['vid']}&amp;sort=title&amp;st={$this->ipsclass->input['st']}\"><b>{$this->ipsclass->lang['message_title']}</b></a></th>
			<th width=\"30%\" style='padding:3px'><a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=01&amp;VID={$info['vid']}&amp;sort=name&amp;st={$this->ipsclass->input['st']}\"><b>{$this->ipsclass->lang['message_from']}</b></a></th>
			<th width=\"25%\" style='padding:3px'><a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=01&amp;VID={$info['vid']}&amp;sort={$info['date_order']}&amp;st={$this->ipsclass->input['st']}\"><b>{$this->ipsclass->lang['message_date']}</b></a></th>
			<th align=\"center\" style='text-align:center;padding:3px' width=\"5%\"><input name=\"allbox\" class='checkbox' type=\"checkbox\" value=\"Check All\" onclick=\"InboxCheckAll();\" /></th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mass_pm_box:desc::trigger:>
//===========================================================================
function mass_pm_box($names="",$checkbox="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td class='row1' style='text-align: right; vertical-align: top'>
			<strong>{$this->ipsclass->lang['carbon_copy_title']}</strong><br /><span class='desc'>{$this->ipsclass->lang['carbon_copy_desc']}</div>
		</td>
		<td class='row2'>
			<textarea name=\"carbon_copy\" rows=\"5\" cols=\"40\" tabindex=\"2\">$names</textarea><br />
			&nbsp;<input type=\"button\" class=\"button\" name=\"findusers\" onclick=\"find_users()\" value=\"{$this->ipsclass->lang['find_user_names']}\" />
			<br /><input class='checkbox' type=\"checkbox\" name=\"mt_hide_cc\" value=\"1\" {$checkbox}/>&nbsp;<strong>{$this->ipsclass->lang['cc_hide_users']}</strong>
		</td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_group:desc::trigger:>
//===========================================================================
function member_group($title="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_group']} $title";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_email:desc::trigger:>
//===========================================================================
function member_icon_email($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=Mail&amp;CODE=00&amp;MID={$id}\"><{P_EMAIL}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_msg:desc::trigger:>
//===========================================================================
function member_icon_msg($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=04&amp;MID={$id}\"><{P_MSG}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_profile:desc::trigger:>
//===========================================================================
function member_icon_profile($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}showuser={$id}\"><{P_PROFILE}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_icon_vcard:desc::trigger:>
//===========================================================================
function member_icon_vcard($id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=Profile&amp;CODE=showcard&amp;MID={$id}','AddressCard','600','300','0','1','1','1')\" title=\"{$this->ipsclass->lang['ac_title']}\"><{P_CARD}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_joined:desc::trigger:>
//===========================================================================
function member_joined($date="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_joined']} $date";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_location:desc::trigger:>
//===========================================================================
function member_location($location="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_location']} $location<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_number:desc::trigger:>
//===========================================================================
function member_number($number="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['member_no']} $number";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_posts:desc::trigger:>
//===========================================================================
function member_posts($posts="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['m_posts']} $posts";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:member_rank_img:desc::trigger:>
//===========================================================================
function member_rank_img($filename="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"$filename\" alt=\"{$this->ipsclass->lang['group_icon']}\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Menu_bar:desc::trigger:>
//===========================================================================
function Menu_bar($component_html="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--
TABLE TO FIX IE/6 ISSUE
The one where 23% margin + 100% table = 123% in IE6 o_O
-->
<script type=\"text/javascript\" src=\"jscripts/ipb_pm.js\"></script>
<script type=\"text/javascript\" src=\"jscripts/ipb_usercp.js\"></script>
<table class='ipbtable' cellspacing=\"0\">
	<tr>
		<td valign=\"top\" class=\"nopad\" width=\"25%\">
			<div id=\"ucpmenu\">
			<div class=\"maintitle\">{$this->ipsclass->lang['tt_menu']}</div>
	 		<!-- Messenger Links -->
" . (($this->ipsclass->member['g_use_pm'] == 1 AND $this->ipsclass->member['members_disable_pm'] == 0) ? ("
<div class=\"formsubtitle\">{$this->ipsclass->lang['m_messenger']}</div>
			<p>
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=04\"><b>{$this->ipsclass->lang['mess_new']}</b></a><br />
				<!--IBF.FOLDER_LINKS-->
				&nbsp;&nbsp; <{MSG_FOLDER}>&nbsp;<a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=20\">{$this->ipsclass->lang['mess_saved']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=delete\">{$this->ipsclass->lang['mi_prune_msg']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=07\">{$this->ipsclass->lang['mess_folders']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=02\">{$this->ipsclass->lang['mess_contact']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=14\">{$this->ipsclass->lang['mess_archive']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=30\">{$this->ipsclass->lang['mess_tracker']}</a><br />
			</p>
	 	<!-- End Messenger -->
") : ("")) . "
" . (($component_html != "") ? ("
$component_html
") : ("")) . "
        
		<!-- Topic Tracker -->
			<div class=\"formsubtitle\">{$this->ipsclass->lang['m_tracker']}</div>
			<p>
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=26\">{$this->ipsclass->lang['m_view_subs']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=50\">{$this->ipsclass->lang['m_view_forum']}</a><br />
			</p>
		<!-- Profile -->
			<div class=\"formsubtitle\">{$this->ipsclass->lang['m_personal']}</div>
			<p>
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=01\">{$this->ipsclass->lang['m_contact_info']}</a><br />
				" . ((! $this->ipsclass->vars['pp_show_classic']) ? ("
					<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=personal_portal_form\">{$this->ipsclass->lang['m_personal_portal']}</a><br />
				") : ("")) . "
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=22\">{$this->ipsclass->lang['m_sig_info']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=24\">{$this->ipsclass->lang['m_avatar_info']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=photo\">{$this->ipsclass->lang['m_change_photo']}</a><br />
				" . (($this->ipsclass->vars['auth_allow_dnames'] == 1 AND $this->ipsclass->member['g_dname_changes'] > 0) ? ("
					<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=dname_start\">{$this->ipsclass->lang['m_dname_change']}</a>
				") : ("")) . "
			</p>
		<!-- Options -->
			<div class=\"formsubtitle\">{$this->ipsclass->lang['m_options']}</div>
			<p>
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=paysubs&amp;CODE=index\">{$this->ipsclass->lang['new_sub_link']}</a><br />
				<!--IBF.OPTION_LINKS-->
				" . (($this->ipsclass->member['g_attach_max'] != -1) ? ("
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=attach\">{$this->ipsclass->lang['m_attach']}</a><br />
				") : ("")) . "
				" . ((! $this->ipsclass->vars['pp_show_classic']) ? ("
					<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=manage_friends\">{$this->ipsclass->lang['m_manage_friends']}</a><br />
				") : ("")) . "
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=ignore\">{$this->ipsclass->lang['m_ignore_users']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=02\">{$this->ipsclass->lang['m_email_opt']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=04\">{$this->ipsclass->lang['m_board_opt']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=08\">{$this->ipsclass->lang['m_email_change']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=28\">{$this->ipsclass->lang['m_passy_opt']}</a>
			</p>
			" . (($this->ipsclass->member['g_is_supmod'] == 1) ? ("
			<div class=\"formsubtitle\">{$this->ipsclass->lang['menu_title_mod']}</div>
			<p>
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=iptool\">{$this->ipsclass->lang['menu_ipsearch']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=memtool\">{$this->ipsclass->lang['menu_memsearch']}</a><br />
				<{ITEM_START}> <a href=\"{$this->ipsclass->base_url}act=UserCP&amp;CODE=announce_start\">{$this->ipsclass->lang['menu_announcements']}</a>
			</p>
			") : ("")) . "
		</div>
		</td>
		<td class=\"nopad\" width=\"1%\"><!-- --></td>
		<!-- Start main CP area -->
		<td valign=\"top\" class=\"nopad\" width=\"75%\">
			<div id=\"ucpcontent\">
			<div class=\"maintitle\">{$this->ipsclass->lang['welcome']}</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:menu_bar_msg_folder_link:desc::trigger:>
//===========================================================================
function menu_bar_msg_folder_link($id="",$real="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&nbsp;&nbsp; <{MSG_FOLDER}>&nbsp;<a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=01&amp;VID=$id\">$real</a><br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:menu_bar_new_category:desc::trigger:>
//===========================================================================
function menu_bar_new_category($title="",$content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\">{$title}</div>
			<p>
				$content
			</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:menu_bar_new_link:desc::trigger:>
//===========================================================================
function menu_bar_new_link($url="",$name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<{ITEM_START}> <a href=\"$url\">$name</a><br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:No_msg_inbox:desc::trigger:>
//===========================================================================
function No_msg_inbox() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row1\" colspan=\"5\" align=\"center\"><b>{$this->ipsclass->lang['inbox_no_msg']}</b></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:pm_errors:desc::trigger:>
//===========================================================================
function pm_errors($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--<div class=\"formsubtitle\">{$this->ipsclass->lang['err_errors']}</div>-->
	<div class=\"errorwrap\"><h4>{$this->ipsclass->lang['err_errors']}</h4><p>$data<br /><br />{$this->ipsclass->lang['pme_none_sent']}</p></div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:postbox_wrap:desc::trigger:>
//===========================================================================
function postbox_wrap($editor_html="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='row1' style='text-align: right; vertical-align: top'>
		<strong>{$this->ipsclass->lang['pro_message']}</strong>
	</td>
	<td class='row2'>
		{$editor_html}
	</td>
</tr>
<!--UPLOAD FIELD-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:prefs_add_dirs:desc::trigger:>
//===========================================================================
function prefs_add_dirs() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"subtitle\">{$this->ipsclass->lang['prefs_new']}</div>
	<p>{$this->ipsclass->lang['prefs_text_b']}</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:prefs_footer:desc::trigger:>
//===========================================================================
function prefs_footer() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formbuttonrow\" align=\"center\"><input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['prefs_submit']}\" /></div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:prefs_header:desc::trigger:>
//===========================================================================
function prefs_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}\" method=\"post\">
<input type=\"hidden\" name=\"act\" value=\"Msg\" />
<input type=\"hidden\" name=\"CODE\" value=\"08\" />
	<div class=\"subtitle\">{$this->ipsclass->lang['prefs_current']}</div>
	<p>{$this->ipsclass->lang['prefs_text_a']}</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:prefs_row:desc::trigger:>
//===========================================================================
function prefs_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<p><input type=\"text\" name=\"{$data['ID']}\" value=\"{$data['REAL']}\" />{$data['EXTRA']}</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:preview:desc::trigger:>
//===========================================================================
function preview($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"subtitle\">{$this->ipsclass->lang['pm_preview']}</div>
	<p>$data</p>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:render_address_row:desc::trigger:>
//===========================================================================
function render_address_row($entry="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class=\"row1\" valign=\"middle\">
		<a href=\"{$this->ipsclass->base_url}act=Profile&amp;CODE=03&amp;MID={$entry['contact_id']}\"><b>{$entry['contact_name']}</b></a>
		" . (($entry['contact_desc']) ? ("
			&nbsp; &nbsp;[ {$entry['contact_desc']} ]
		") : ("")) . "
	</td>
	<td class=\"row2\" valign=\"middle\">[ <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=11&amp;MID={$entry['contact_id']}\">{$this->ipsclass->lang['edit']}</a> ] :: [ <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=10&amp;MID={$entry['contact_id']}\">{$this->ipsclass->lang['delete']}</a> ]&nbsp;&nbsp;( {$entry['text']} )</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Render_msg:desc::trigger:>
//===========================================================================
function Render_msg($post="",$author="",$jump="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src=\"jscripts/ipb_topic.js\"></script>
<div class=\"subtitle\">{$post['mt_title']}</div>
		<table class='ipbtable' cellspacing=\"0\">
			<tr>
				<td valign=\"middle\" class=\"post_head\">
				" . (($author['id']) ? ("
					<div id=\"post-member-{$author['id']}\" class='popmenubutton-new-out'>
						<span class=\"normalname\">{$author['_pp_online_image']}<a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\">{$author['members_display_name_short']}</a></span>
					</div>
					<!-- member menu -->
					<div class='popupmenu-new' id='post-member-{$author['id']}_menu' style='display:none;width:230px'>
						<div class='popupmenu-item-last'>
							" . (($author['members_display_name_short'] != $author['members_display_name']) ? ("
								<div class='popupmenu-item'><strong>{$author['members_display_name']}</strong></div>
							") : ("")) . "
							<div style='float:right'>
								<div class='pp-image-thumb-wrap'>
									<img src='{$author['pp_thumb_photo']}' width='{$author['pp_thumb_width']}' height='{$author['pp_thumb_height']}' />
								</div>
								" . (($this->ipsclass->vars['pp_allow_member_rate']) ? ("
									<div style='margin-top:5px;margin-left:6px;'>
										<img src=\"{$this->ipsclass->vars['img_url']}/rating_{$author['_pp_rating_real']}_mini.gif\" alt='Rating: {$author['_pp_rating_real']}' style='vertical-align:middle' border='0' />
									</div>
								") : ("")) . "
							</div>
							<div class='popupmenu-item'>
								{$author['_pp_gender_image']} <a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\">{$this->ipsclass->lang['dd_view_profile']}</a>
							</div>
							" . (($this->ipsclass->member['id']) ? ("
								<div class='popupmenu-item'>
									" . ((in_array( $author['id'], array_keys( $this->ipsclass->member['_cache']['friends'] ) )) ? ("
										<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_remove_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=remove&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['dd_remove_friend']}</a>
									") : ("
										<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_add_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=add&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>{$this->ipsclass->lang['dd_add_friend']}</a>
									")) . "
								</div>
								<div class='popupmenu-item'>
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/send_pm_small.png' alt='' border='0' /> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=4&amp;MID={$author['id']}\">{$this->ipsclass->lang['dd_send_pm']}</a>
								</div>
								<div class='popupmenu-item'>
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_remove_small.png' alt='' border='0' /> <a href=\"{$this->ipsclass->base_url}CODE=02&amp;act=Msg&amp;MID={$author['id']}\">{$this->ipsclass->lang['dd_add_to_block']}</a>
								</div>
							") : ("")) . "
							<div class='popupmenu-item'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/send_pm_small.png' alt='' border='0' /> <a href=\"{$this->ipsclass->base_url}CODE=04&amp;act=Msg&amp;MSID={$post['mt_id']}&amp;MID={$author['id']}&amp;fwd=1\">{$this->ipsclass->lang['dd_forward_pm']}</a>
							</div>
							<div class='popupmenu-item'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=gettopicsuser&amp;mid={$author['id']}'>{$this->ipsclass->lang['dd_find_topics']}</a>
							</div>									
							<div class='popupmenu-item-last'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=getalluser&amp;mid={$author['id']}'>{$this->ipsclass->lang['dd_find_posts']}</a>
							</div>
						</div>
					</div>
					<!-- member menu -->
					<script type=\"text/javascript\">
						ipsmenu.register( \"post-member-{$author['id']}\", '', 'popmenubutton-new', 'popmenubutton-new-out' );
					</script>
				") : ("
					{$author['members_display_name']}
				")) . "
				</td>
				<td class=\"post_head\" valign=\"middle\">
					<!-- POSTED DATE DIV -->
						<span class=\"postdetails\"><b>{$post['mt_title']}</b>, {$post['msg_date']}</span>
				</td>
			</tr>
			<tr>
				<td valign=\"top\" class=\"post1 post_left\">
					<span class=\"postdetails\">
						" . (($author['id'] AND $author['avatar']) ? ("
							<a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\" title=\"{$this->ipsclass->lang['dd_view_profile']}\">{$author['avatar']}</a><br /><br />
						") : ("
		        			{$author['avatar']}<br /><br />
						")) . "
						{$author['title']}<br />
						{$author['member_rank_img']}<br /><br />
						{$author['member_group']}<br />
						{$author['member_posts']}<br />
						{$author['member_number']}<br />
						{$author['member_joined']}<br /><br />
						{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
					</span>
					<br />
					<!--$ author[field_1]-->
					<img src=\"{$this->ipsclass->vars['img_url']}/spacer.gif\" alt=\"\" width=\"160\" height=\"1\" /><br /> 
				</td>
				<td width=\"100%\" valign=\"top\" class=\"post1\">
					{$post['show_cc_users']}
					<div class=\"postcolor\">
						{$post['msg_post']}
						<!--IBF.ATTACHMENT_{$post['msg_id']}-->
					</div>
					{$author['signature']}
				</td>
			</tr>
			<tr>
				<td class=\"darkrow3\">
					" . (($post['_ip_address'] != '') ? ("
						{$this->ipsclass->lang['msg_ip_address']} {$post['_ip_address']}
					") : ("")) . "
				</td>
				<td class=\"darkrow3\" nowrap=\"nowrap\">
					<div align=\"right\">
						<a href=\"{$this->ipsclass->base_url}CODE=05&amp;act=Msg&amp;MSID={$post['mt_id']}&amp;VID={$author['VID']}\"><{P_DELETE}></a>
						<a href=\"{$this->ipsclass->base_url}CODE=04&amp;act=Msg&amp;MID={$author['id']}&amp;MSID={$post['mt_id']}\"><{P_QUOTE}></a>
					</div>
				</td>
			</tr>
			<tr>
				<td colspan='2' class='catend'></td>
			</tr>
		</table>	
		<div class='formbuttonrow' align='right'>
			<form action=\"{$this->ipsclass->base_url}\" name=\"jump\" method=\"post\">
			<input type=\"hidden\" name=\"act\" value=\"Msg\" />
			<input type=\"hidden\" name=\"CODE\" value=\"01\" />
				{$this->ipsclass->lang['goto_folder']}:&nbsp; {$jump}
			<input type=\"submit\" class=\"button\" value=\"{$this->ipsclass->lang['goto_submit']}\" />
			</form>
		</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:render_msg_show_cc:desc::trigger:>
//===========================================================================
function render_msg_show_cc($cc_users="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<b>CC:</b> $cc_users
		<hr noshade=\"noshade\" size=\"1\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Send_form:desc::trigger:>
//===========================================================================
function Send_form($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src='jscripts/ipb_xhr_findnames.js'></script>
<script type=\"text/javascript\">
<!--
	function find_users(){
		url = \"index.{$this->ipsclass->vars['php_ext']}?act=legends&CODE=finduser_one&s={$this->ipsclass->session_id}&entry=textarea&name=carbon_copy&sep=line\";
		window.open(url,\"FindUsers\",\"width=400,height=250,resizable=yes,scrollbars=yes\"); 
	}
-->
</script>
<form id='postingform' style='display:block' action=\"{$this->ipsclass->base_url}act=msg\" method=\"post\" name=\"REPLIER\" {$data['form_extra']} onsubmit=\"return ValidateForm(1);\">
<input type=\"hidden\" name=\"removeattachid\" value=\"0\" />
<input type=\"hidden\" name=\"OID\"  value=\"{$data['OID']}\" />
<input type=\"hidden\" name=\"act\" value=\"Msg\" />
<input type=\"hidden\" name=\"CODE\" value=\"04\" />
<input type=\"hidden\" name=\"MODE\" value=\"01\" />
<input type=\"hidden\" name=\"attach_post_key\" value=\"{$data['attach_post_key']}\" />
<input type=\"hidden\" name=\"auth_key\" value=\"{$this->ipsclass->md5_check}\" />
{$data['upload']}
<div id='ipb-get-members' style='border:1px solid #000; background:#FFF; padding:2px;position:absolute;width:210px;display:none;z-index:1'></div>
<table width='100%' class='ipbtable' cellpadding='0' cellspacing='0'>
	<tr>
		<td class='subtitle' colspan='2'>{$this->ipsclass->lang['pro_recips']}</td>
	</tr>
	<tr>
		<td class='row1' style='text-align: right; width: 20%'>
			<strong>{$this->ipsclass->lang['to_whom']}</strong>
		</td>
		<td class='row2'>
			<input type=\"text\" id='entered_name' name=\"entered_name\" size=\"30\" autocomplete='off' style='width:210px' value=\"{$data['N_ENTER']}\" tabindex=\"1\" /> &nbsp; {$data['CONTACTS']}
		</td>
	</tr>
	<!--IBF.MASS_PM_BOX-->
	<tr>
		<td class='subtitle' colspan='2'>{$this->ipsclass->lang['pro_details']}</td>
	</tr>
	<tr>
		<td class='row1' style='text-align: right'>
			<strong>{$this->ipsclass->lang['msg_title']}</strong>
		</td>
		<td class='row2'>
			<input type=\"text\" name=\"msg_title\" size=\"40\" tabindex=\"3\" maxlength=\"40\" value=\"{$data['O_TITLE']}\" />
		</td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:send_form_footer:desc::trigger:>
//===========================================================================
function send_form_footer($default=array()) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='subtitle' colspan='2'>{$this->ipsclass->lang['msg_options']}</td>
</tr>
<tr>
	<td class='row1'>&nbsp;</td>
	<td class='row2'>
		<input class='checkbox' type=\"checkbox\" name=\"add_sent\" value=\"yes\" {$default['add_sent']}/>&nbsp;<b>{$this->ipsclass->lang['auto_sent_add']}</b>
		 <br />
		<input class='checkbox' type=\"checkbox\" name=\"add_tracking\" value=\"1\" {$default['add_tracking']}/>&nbsp;<b>{$this->ipsclass->lang['vm_track_msg']}</b>
	</td>
</tr>
<tr>
	<td class='formbuttonrow' colspan='2' style='text-align: center'>
		<input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['submit_send']}\" tabindex=\"10\" accesskey=\"s\" />
		<input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['pm_pre_button']}\" tabindex=\"11\" name=\"preview\" />
		<input class='button' type=\"submit\" value=\"{$this->ipsclass->lang['pms_send_later']}\" tabindex=\"12\" name=\"save\" />
	</td>
</tr>
</table>
<script type=\"text/javascript\">
	// INIT find names
	init_js( 'postingform', 'entered_name');
	// Run main loop
	setTimeout( 'main_loop()', 10 );
</script>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_attachment_title:desc::trigger:>
//===========================================================================
function show_attachment_title($title="",$data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<div>
	<strong><span class=\"edit\">$title</span></strong>
	<div>
		$data
	</div>
</div>
<div>&nbsp;</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Show_attachments:desc::trigger:>
//===========================================================================
function Show_attachments($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}act=attach&amp;type={$data['type']}&amp;id={$data['attach_id']}\" title=\"{$this->ipsclass->lang['attach_dl']}\" target=\"_blank\"><img src=\"{$this->ipsclass->vars['mime_img']}/{$data['mime_image']}\" alt=\"{$this->ipsclass->lang['attached_file']}\" /></a>
&nbsp;<a href=\"{$this->ipsclass->base_url}act=attach&amp;type={$data['type']}&amp;id={$data['attach_id']}\" title=\"{$this->ipsclass->lang['attach_dl']}\" target=\"_blank\">{$data['attach_file']}</a> ( {$data['file_size']} )
<span class=\"desc\">{$this->ipsclass->lang['attach_hits']}: {$data['attach_hits']}</span><br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Show_attachments_img:desc::trigger:>
//===========================================================================
function Show_attachments_img($file_name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<img src=\"{$this->ipsclass->vars['upload_url']}/$file_name\" class='linked-image' alt=\"{$this->ipsclass->lang['pic_attach']}\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Show_attachments_img_thumb:desc::trigger:>
//===========================================================================
function Show_attachments_img_thumb($data=array()) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "" . ((!$data['notinline']) ? ("
 <br />
") : ("")) . "
<table style='width:auto;display:inline;' id='ipb-attach-table-{$data['_attach_id']}' cellspacing='0' cellpadding='0'>
<tr>
 <td>
	<div id='ipb-attach-div-{$data['_attach_id']}'>
		<div id='ipb-attach-ct-{$data['_attach_id']}'></div>
		<a id='ipb-attach-url-{$data['_attach_id']}' href=\"{$this->ipsclass->base_url}act=attach&amp;type={$data['type']}&amp;id={$data['attach_id']}\" title=\"{$data['location']} - {$this->ipsclass->lang['attach_size']} {$data['file_size']}, {$this->ipsclass->lang['attach_ahits']} {$data['attach_hits']}\" target=\"_blank\"><img src=\"{$this->ipsclass->vars['upload_url']}/{$data['t_location']}\" id='ipb-attach-img-{$data['_attach_id']}' style='width:{$data['t_width']};height:{$data['t_height']}' class='attach' width=\"{$data['t_width']}\" height=\"{$data['t_height']}\" alt=\"{$this->ipsclass->lang['pic_attach']}\" /></a>
		<div id='ipb-attach-cb-{$data['_attach_id']}' style='margin:0px'></div>
	</div>
 </td>
</tr>
</table>
<script type='text/javascript'>
//<![CDATA[
	fix_linked_image_sizes_attach_thumb( \"{$data['_attach_id']}\", parseInt(\"{$data['o_width']}\"), parseInt(\"{$data['o_height']}\"), \"{$data['file_size']}\" );
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:trackread_end:desc::trigger:>
//===========================================================================
function trackread_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td align=\"right\" colspan=\"5\" class=\"formbuttonrow\"><input class='button' type=\"submit\" name=\"endtrack\" value=\"{$this->ipsclass->lang['tk_untrack_button']}\" /> {$this->ipsclass->lang['selected_msg']}</td>
		</tr>
	</table>
</div>
</form>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:trackread_row:desc::trigger:>
//===========================================================================
function trackread_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class=\"row1\" valign=\"middle\" align='center'>{$data['icon']}</td>
	<td class=\"row2\">{$data['mt_title']}</td>
	<td class=\"row1\"><a href=\"{$this->ipsclass->base_url}showuser={$data['memid']}\">{$data['to_name']}</a></td>
	<td class=\"row2\">{$data['date']}</td>
	<td class=\"row1\" align='center'><input class='checkbox' type=\"checkbox\" name=\"msgid_{$data['mt_id']}\" value=\"yes\" onclick=\"CheckCheckAll(document.trackread);\" /></td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:trackread_table_header:desc::trigger:>
//===========================================================================
function trackread_table_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}CODE=31&amp;act=Msg\" name=\"trackread\" method=\"post\">
<div class=\"subtitle\">{$this->ipsclass->lang['tk_read_messages']}</div>
<p>{$this->ipsclass->lang['tk_read_desc']}</p>
<div class=\"borderwrapm\">
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<th width=\"5%\">&nbsp;</th>
			<th width=\"30%\"><b>{$this->ipsclass->lang['message_title']}</b></th>
			<th width=\"30%\"><b>{$this->ipsclass->lang['pms_message_to']}</b></th>
			<th width=\"20%\"><b>{$this->ipsclass->lang['tk_read_date']}</b></th>
			<th align=\"center\" width=\"5%\" style='padding:1px;text-align:center'><input name=\"allbox\" class='checkbox' type=\"checkbox\" value=\"Check All\" onclick=\"CheckAll(document.trackread);\" /></th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:trackUNread_end:desc::trigger:>
//===========================================================================
function trackUNread_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td align=\"right\" colspan=\"5\" class=\"formbuttonrow\"><input class='button' type=\"submit\" name=\"delete\" value=\"{$this->ipsclass->lang['delete_button']}\" /> {$this->ipsclass->lang['selected_msg']}</td>
		</tr>
	</table>
</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:trackUNread_row:desc::trigger:>
//===========================================================================
function trackUNread_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row1\" valign=\"middle\" align='center'>{$data['icon']}</td>
			<td class=\"row2\">{$data['mt_title']}</td>
			<td class=\"row1\"><a href=\"{$this->ipsclass->base_url}showuser={$data['memid']}\">{$data['to_name']}</a></td>
			<td class=\"row2\">{$data['date']}</td>
			<td class=\"row1\" align='center'><input class='checkbox' type=\"checkbox\" name=\"msgid_{$data['mt_id']}\" value=\"yes\" onclick=\"CheckCheckAll(document.trackunread);\" /></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:trackUNread_table_header:desc::trigger:>
//===========================================================================
function trackUNread_table_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}CODE=32&amp;act=Msg\" name=\"trackunread\" method=\"post\">
<div class=\"subtitle\">{$this->ipsclass->lang['tk_unread_messages']}</div>
<p>{$this->ipsclass->lang['tk_unread_desc']}</p>
<div class=\"borderwrapm\">
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<th width=\"5%\">&nbsp;</th>
			<th width=\"30%\"><b>{$this->ipsclass->lang['message_title']}</b></th>
			<th width=\"30%\"><b>{$this->ipsclass->lang['pms_message_to']}</b></th>
			<th width=\"20%\"><b>{$this->ipsclass->lang['tk_unread_date']}</b></th>
			<th align=\"center\" width=\"5%\" style='padding:1px;text-align:center'><input name=\"allbox\" class='checkbox' type=\"checkbox\" value=\"Check All\" onclick=\"CheckAll(document.trackunread);\" /></th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:unsent_empty_row:desc::trigger:>
//===========================================================================
function unsent_empty_row() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row1\" colspan=\"6\" align=\"center\"><b>{$this->ipsclass->lang['inbox_no_msg']}</b></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:unsent_end:desc::trigger:>
//===========================================================================
function unsent_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td align=\"center\" nowrap=\"nowrap\" colspan=\"6\" class=\"formbuttonrow\"><input class='button' type=\"submit\" name=\"delete\" value=\"{$this->ipsclass->lang['delete_button']}\" /> {$this->ipsclass->lang['selected_msg']}</td>
		</tr>
	</table>
</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:unsent_row:desc::trigger:>
//===========================================================================
function unsent_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row1\" valign=\"middle\">{$data['msg']['icon']}</td>
			<td class=\"row2\">{$data['msg']['attach_img']}&nbsp;<a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=21&amp;MSID={$data['msg']['mt_id']}\">{$data['msg']['mt_title']}</a></td>
			<td class=\"row1\">{$data['msg']['from_name']}</td>
			<td class=\"row2\">{$data['msg']['date']}</td>
			<td class=\"row1\" align=\"center\">{$data['msg']['cc_users']}</td>
			<td class=\"row2\"><input class='checkbox' type=\"checkbox\" name=\"msgid_{$data['msg']['mt_id']}\" value=\"yes\" /></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:unsent_table_header:desc::trigger:>
//===========================================================================
function unsent_table_header() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}CODE=06&amp;act=Msg&amp;saved=1\" name=\"mutliact\" method=\"post\">
<div class=\"subtitle\">{$this->ipsclass->lang['pms_saved_title']}</div>
<br />
<div class=\"borderwrapm\">
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<th width=\"5%\">&nbsp;</th>
			<th width=\"30%\"><b>{$this->ipsclass->lang['message_title']}</b></th>
			<th width=\"30%\"><b>{$this->ipsclass->lang['pms_message_to']}</b></th>
			<th width=\"20%\"><b>{$this->ipsclass->lang['pms_saved_date']}</b></th>
			<th width=\"10%\"><b>{$this->ipsclass->lang['pms_cc_users']}</b></th>
			<th align=\"center\" width=\"5%\" style='padding:1px;text-align:center'><input name=\"allbox\" class='checkbox' type=\"checkbox\" value=\"Check All\" onclick=\"CheckAll(document.mutliact);\" /></th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_level_rating:desc::trigger:>
//===========================================================================
function warn_level_rating($id="",$level="",$min=0,$max=10) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&lt;&nbsp;$min ( <a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')\">{$level}</a> ) $max&nbsp;&gt;";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_level_warn:desc::trigger:>
//===========================================================================
function warn_level_warn($id="",$percent="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "{$this->ipsclass->lang['tt_warn']} (<a href=\"javascript:PopUp('{$this->ipsclass->base_url}act=warn&amp;mid={$id}&amp;CODE=view','Pager','500','450','0','1','1','1')\">{$percent}</a>%)";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xmlout_msgs_none:desc::trigger:>
//===========================================================================
function xmlout_msgs_none() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='pp-contentbox-back'>
	<div class='pp-contentbox-entry-noheight' align='center'>
  			<span style='font-size:10px' class='desc'><em>({$this->ipsclass->lang['xml_no_pms']})</em></span>
	</div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xmlout_msgs_row:desc::trigger:>
//===========================================================================
function xmlout_msgs_row($msg="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='popupmenu-item'>
 <div class='pp-contentbox-entry-noheight'>
 <div style='float:left'>{$msg['icon']} <a href=\"#\" onclick='locationjump(\"act=msg&amp;CODE=03&amp;VID={$msg['mt_vid_folder']}&amp;MSID={$msg['mt_id']}\");' title='{$msg['mt_title']} ({$msg['from_name']})'>{$msg['_mini']}</a></div>
 <div align='right'>
  <span style='font-size:10px' class='desc'><em>({$msg['date']})</em></span>
 </div>
 </div>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:xmlout_msgs_wrapper:desc::trigger:>
//===========================================================================
function xmlout_msgs_wrapper($content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='pp-contentbox-back'>
	<div style='border: 1px solid #888888; padding:0px;'>
  	<div style='border: 1px solid #EEF2F7'>
	   {$content}
	</div>
	<div align='center' style='padding:6px;font-weight:bold' class='darkrow3'><a href='#' onclick='locationjump(\"act=msg&amp;CODE=01\");'>{$this->ipsclass->lang['xml_go_inbox']}</a> &raquo;</div>
	</div>
</div>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
address_add,address_edit,Address_header,Address_table_header,archive_form,empty_folder_footer,empty_folder_header,empty_folder_row,empty_folder_save_unread,end_inbox,inbox_row,inbox_table_header,mass_pm_box,postbox_wrap,prefs_add_dirs,prefs_footer,prefs_header,preview,render_address_row,Render_msg,Send_form,send_form_footer,trackread_row,trackread_table_header,trackUNread_row,trackUNread_table_header,unsent_end,unsent_row,unsent_table_header
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>