<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_blog_cblocks_3 {

 var $ipsclass;
//===========================================================================
// <ips:mini_cal_day_bit:desc::trigger:>
//===========================================================================
function mini_cal_day_bit($day="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<th width=\"14%\" class=\"subtitle\">$day</td>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mini_cal_mini_wrap:desc::trigger:>
//===========================================================================
function mini_cal_mini_wrap($content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table width='100%' cellspacing=\"0\">
		<tr>
			{$content}
		</tr>
	</table>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
mini_cal_day_bit,mini_cal_mini_wrap
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>