<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_search_3 {

 var $ipsclass;
//===========================================================================
// <ips:no_results:desc::trigger:>
//===========================================================================
function no_results() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['search_results']}</div>
	
	<table class=\"ipbtable\" cellspacing='0'>
		<tr>
			<td class=\"row1\" align=\"center\">{$this->ipsclass->lang['no_results']}</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:search_row:desc::trigger:>
//===========================================================================
function search_row($info="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row1\" align=\"center\">
       			<table class='ipbtable' cellspacing='0'>
         			<tr>
         				<td align=\"center\">{$info['image']}</td>
             			<td valign=\"top\" width=\"70%\">
             				<i>{$info['stuff']}<br />
             				{$this->ipsclass->lang['postedby']} {$info['user']}
             			</td>
             		</tr>
       			</table>
       		</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:search_top:desc::trigger:>
//===========================================================================
function search_top($page_links="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class='ipbtable'>
	<tr>
		<td style='padding-left:0px;' width=\"100%\" nowrap=\"nowrap\">{$page_links}</td>
	</tr>
</table>
<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['search_results']}</div>
	
	<table class=\"ipbtable\" cellspacing='0'>
		<tr>
			<th width=\"100%\">&nbsp;</th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
no_results,search_row,search_top
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>