<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_post_3 {

 var $ipsclass;
//===========================================================================
// <ips:add_edit_box:desc::trigger:>
//===========================================================================
function add_edit_box($checked="",$show_reason=0,$post_edit_reason='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['edit_ops']}</strong>
		" . (($show_reason) ? ("
			<br /><br />
			{$this->ipsclass->lang['reason_for_edit']}
		") : ("")) . "			
	</td>
	<td class='row2'>
		<input type=\"checkbox\" name=\"add_edit\" value=\"1\" $checked class=\"checkbox\" />&nbsp;{$this->ipsclass->lang['append_edit']}
		" . (($show_reason) ? ("
			<br /><br />
			<input type=\"input\" name=\"post_edit_reason\" value=\"{$post_edit_reason}\" size='40' maxlength='250' />
		") : ("")) . "
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:attach_current_item:desc::trigger:>
//===========================================================================
function attach_current_item($id="",$name="",$human_size="",$mime_image="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "parent.ipsattach.add_current_item( '{$id}', '{$name}', '{$human_size}', '{$mime_image}' );";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:attach_wrapper:desc::trigger:>
//===========================================================================
function attach_wrapper($current_items="",$attach_rel_module="",$attach_rel_id="",$attach_post_key="",$attach_stats="",$msg='',$is_error=0,$extra_url='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type='text/javascript'>
//<![CDATA[
// Populate menu
parent.ipsattach.current_items   = new Array();
{$current_items}
// Set up vars
parent.ipsattach.can_upload      = parseInt(\"{$attach_stats['allow_uploads']}\");
parent.ipsattach.status_msg      = \"{$msg}\";
parent.ipsattach.status_is_error = parseInt(\"{$is_error}\");
//]]>
</script>
<form id='mainform' enctype='multipart/form-data' action='{$this->ipsclass->base_url}&amp;act=attach&amp;code=attach_upload_process&amp;attach_rel_module={$attach_rel_module}&amp;attach_rel_id={$attach_rel_id}&amp;attach_post_key={$attach_post_key}{$extra_url}' method='POST'>
<input type='hidden' name='MAX_FILE_SIZE' value='100000000' />
<div style='padding:8px 2px 0px 2px;'>
	<table cellpadding='0' cellspacing='0' border='0' width='100%'>
	<tr>
	  <td width='10%' nowrap='nowrap'><strong>{$this->ipsclass->lang['attach_select_file']}</strong></td>
	  <td width='90%' align='right' valign='bottom'><input type='file' id='ipb-file-upload-box' size='30' onblur='parent.ipsattach.has_upload_pending=this.value;' name='FILE_UPLOAD' /> <input class='input-ok-content' style='margin:0px;padding:2px' type='submit' value='{$this->ipsclass->lang['attach_but_upload']}' /></td>
	</tr>
	</table>
	<table cellpadding='0' cellspacing='0' border='0' width='100%'>
	<tr>
	 <td width='90%'><div class='desc'>{$this->ipsclass->lang['attach_space_used']} <strong>{$attach_stats['space_used_human']}</strong> {$this->ipsclass->lang['attach_space_of']} <strong>{$attach_stats['total_space_allowed_human']}</strong></div></td>
	 <td nowrap='nowrap' width='10%' align='right'>{$this->ipsclass->lang['max_single_attach']}: <strong>{$attach_stats['max_single_upload_human']}</strong></td>
	</tr>
	</table>
</div>
</form>
<script type='text/javascript'>
//<![CDATA[
// Add form's onsubmit handler
document.getElementById('mainform').onsubmit = function (e) { parent.ipsattach.iframe_on_un_load(); return true; }
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:bot_antispam_gd:desc::trigger:>
//===========================================================================
function bot_antispam_gd($imgid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<input type=\"hidden\" name=\"imgid\" id='regid' value=\"{$imgid}\" />
<img id='gd-antispam' src=\"{$this->ipsclass->base_url}act=Post&amp;CODE=image&amp;rc={$imgid}\" alt=\"{$this->ipsclass->lang['alt_loadingimg']}\" title=\"{$this->ipsclass->lang['gbl_gd_reload']}\" />
<script type='text/javascript'>
	init_gd_image();
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:bot_antispam_gif:desc::trigger:>
//===========================================================================
function bot_antispam_gif($imgid="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<input type=\"hidden\" name=\"imgid\" value=\"{$imgid}\" />
					<img src=\"{$this->ipsclass->base_url}act=Post&amp;CODE=image&amp;rc={$imgid}&amp;p=1\" alt=\"Code Bit\" />
					&nbsp;<img src=\"{$this->ipsclass->base_url}act=Post&amp;CODE=image&amp;rc={$imgid}&amp;p=2\" alt=\"{$this->ipsclass->lang['alt_codebit']}\" />
					&nbsp;<img src=\"{$this->ipsclass->base_url}act=Post&amp;CODE=image&amp;rc={$imgid}&amp;p=3\" alt=\"{$this->ipsclass->lang['alt_codebit']}\" />
					&nbsp;<img src=\"{$this->ipsclass->base_url}act=Post&amp;CODE=image&amp;rc={$imgid}&amp;p=4\" alt=\"{$this->ipsclass->lang['alt_codebit']}\" />
					&nbsp;<img src=\"{$this->ipsclass->base_url}act=Post&amp;CODE=image&amp;rc={$imgid}&amp;p=5\" alt=\"{$this->ipsclass->lang['alt_codebit']}\" />
					&nbsp;<img src=\"{$this->ipsclass->base_url}act=Post&amp;CODE=image&amp;rc={$imgid}&amp;p=6\" alt=\"{$this->ipsclass->lang['alt_codebit']}\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:EndForm:desc::trigger:>
//===========================================================================
function EndForm($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td class=\"formbuttonrow\" colspan=\"2\">
			<input type=\"submit\" name=\"dosubmit\" value=\"$data\" tabindex=\"7\" class=\"button\" accesskey=\"s\"  />&nbsp;
			<input type=\"submit\" name=\"preview\" value=\"{$this->ipsclass->lang['button_preview']}\" tabindex=\"8\" class=\"button\" />
		</td>
	</tr>
</table>
</div>
</form>
<br style=\"clear: all;\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:errors:desc::trigger:>
//===========================================================================
function errors($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
  <div class=\"formsubtitle\">{$this->ipsclass->lang['errors_found']}</div>
  <div class=\"tablepad\"><span class=\"postcolor\">$data</span></div>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:get_box_alreadytrack:desc::trigger:>
//===========================================================================
function get_box_alreadytrack() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
{$this->ipsclass->lang['already_sub']}";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:get_box_enableemo:desc::trigger:>
//===========================================================================
function get_box_enableemo($checked="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<input type=\"checkbox\" name=\"enableemo\" class=\"checkbox\" value=\"yes\" $checked />&nbsp;{$this->ipsclass->lang['enable_emo']}";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:get_box_enablesig:desc::trigger:>
//===========================================================================
function get_box_enablesig($checked="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<input type=\"checkbox\" name=\"enablesig\" class=\"checkbox\" value=\"yes\" $checked />&nbsp;{$this->ipsclass->lang['enable_sig']}";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:get_box_enabletrack:desc::trigger:>
//===========================================================================
function get_box_enabletrack($checked="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<input type=\"checkbox\" name=\"enabletrack\" class=\"checkbox\" value=\"1\" $checked />&nbsp;{$this->ipsclass->lang['enable_track']}";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:get_box_html:desc::trigger:>
//===========================================================================
function get_box_html($selected="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "&nbsp;<select name=\"post_htmlstatus\" class=\"dropdown\">
	<option value=\"0\"{$selected[0]}>{$this->ipsclass->lang['pp_nohtml']}</option>
	<option value=\"1\"{$selected[1]}>{$this->ipsclass->lang['pp_html1']}</option>
	<option value=\"2\"{$selected[2]}>{$this->ipsclass->lang['pp_html2']}</option>
</select>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:guest_captcha:desc::trigger:>
//===========================================================================
function guest_captcha() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='row1' align=\"right\" width='20%'>
	 <strong>{$this->ipsclass->lang['guest_captcha']}</strong>
	</td>
	<td class='row2' align=\"left\" width='80%'>
	 <table>
	 	<tr>
	 		<td width='40%'>
	 			<input type=\"text\" size=\"50\" maxlength=\"10\" name=\"captcha\" value=\"\" class=\"textinput\" /><br />
	 			{$this->ipsclass->lang['captcha_explain']}
	 		</td>
	 		<td><!--CAPTCHA.IMAGE--></td>
	 	</tr>
	 </table>
	</td>
   </tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:inline_edit_quick_box:desc::trigger:>
//===========================================================================
function inline_edit_quick_box($post="",$pid=0,$error_msg="",$show_reason=0,$post_edit_reason='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form id='quick-edit-form-$pid' style='display:block'>
" . (($error_msg != "") ? ("
<div class='input-warn-content'>{$error_msg}</div>
") : ("")) . "
<div id='{$pid}-controls' align='center' style='width:95%;padding:6px; margin:0 auto 0 auto' class=\"rte-buttonbar\">
	<table cellpadding=\"2\" cellspacing=\"0\" width='100%'>
	<tr>
	 <td width='1%' align='left' nowrap='nowrap'>
	  <table cellpadding='0' cellspacing='0' width='100%'>
	   <tr>
	     <td><div class=\"rte-normal\" id=\"{$pid}_cmd_bold\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-bold.png\"  alt=\"{$this->ipsclass->lang['js_tt_bold']}\" title=\"{$this->ipsclass->lang['js_tt_bold']}\"></div></td>
	     <td><div class=\"rte-normal\" id=\"{$pid}_cmd_italic\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-italic.png\"  alt=\"{$this->ipsclass->lang['js_tt_italic']}\" title=\"{$this->ipsclass->lang['js_tt_italic']}\" ></div></td>
	     <td><div class=\"rte-normal\" id=\"{$pid}_cmd_underline\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-underlined.png\" alt=\"{$this->ipsclass->lang['js_tt_underline']}\" title=\"{$this->ipsclass->lang['js_tt_underline']}\" ></div></td>
	   	 <td><div class=\"rte-normal\" id=\"{$pid}_cmd_createlink\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-link-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_link']}\" title=\"{$this->ipsclass->lang['js_rte_lite_link']}\"></div></td>
		 <td><div class=\"rte-normal\" id=\"{$pid}_cmd_insertimage\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-image-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_img']}\" title=\"{$this->ipsclass->lang['js_rte_lite_img']}\"></div></td>
		 <td><div class=\"rte-normal\" id=\"{$pid}_cmd_emoticon\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-emo-button.png\"  alt=\"{$this->ipsclass->lang['js_tt_emoticons']}\" title=\"{$this->ipsclass->lang['js_tt_emoticons']}\"></div></td>
	     <td><div class=\"rte-normal\" id=\"{$pid}_cmd_ipb_quote\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-quote-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_quote']}\" title=\"{$this->ipsclass->lang['js_rte_lite_quote']}\"></div></td>
		 <td><div class=\"rte-normal\" id=\"{$pid}_cmd_ipb_code\"><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-code-button.png\"  alt=\"{$this->ipsclass->lang['js_rte_lite_code']}\" title=\"{$this->ipsclass->lang['js_rte_lite_code']}\"></div></td>
	</tr>
	  </table>
	 </td>
	 <td width='98%'>&nbsp;</td>
	 <td width='1%' align='right' nowrap='nowrap'>
		<table cellpadding='0' cellspacing='0' width='100%'>
           <tr>
               	<td>
				   <div class=\"rte-normal\" id=\"{$pid}_resize_up\" style='padding:0px;margin:0px;'><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-resize-up.gif\"  alt=\"\" /></div>
				   <div class=\"rte-normal\" id=\"{$pid}_resize_down\" style='padding:0px;margin:0px;padding-top:1px'><img src=\"style_images/<#IMG_DIR#>/folder_editor_images/rte-resize-down.gif\"  alt=\"\" title=\"\" /></div>
			   </td>
           </tr>
          </table>
	 </td>
	</tr>
	</table>
   <div style='padding-bottom:8px'>
    	<textarea style='margin:0px;padding:4px;width:98%' name='Post' tabindex='1' id='{$pid}_textarea' class='rte-iframe' cols='80' rows='15'>{$post}</textarea>
   </div>
   <div style='height:30px'>
	   <div style='float:right;'>
	     <div class='rte-menu-button' style='width:110px;font-size:10px;padding-right:2px;text-align:left'><a href='#' style='text-decoration:none' onclick='ajax_fulleditor_for_edit( $pid ); return false'><img src='style_images/<#IMG_DIR#>/folder_editor_images/rte-redo.png' style='vertical-align:middle;padding-bottom:2px' alt='' /> {$this->ipsclass->lang['qe_full_edit']}</a></div>
	   </div>
	   <div style='float:right;margin-right:4px;'>
	     <div class='rte-menu-button' style='width:100px;font-size:10px;padding-right:2px;text-align:left'><a href='#' style='text-decoration:none' onclick='ajax_cancel_for_edit( $pid ); return false'><img src='style_images/<#IMG_DIR#>/folder_editor_images/rte-error.png' style='vertical-align:middle;padding-bottom:2px' alt='' /> {$this->ipsclass->lang['qe_cancel_edit']}</a></div>
	   </div>
	   <div style='float:right;margin-right:4px;'>
		 <div class='rte-menu-button' tabindex='2' onkeydown='if (event.keyCode == 13) { ajax_save_for_edit( $pid ); return false; }'  style='width:108px;font-size:10px;padding-right:2px;text-align:left'><a href='#' style='text-decoration:none' onclick='ajax_save_for_edit( $pid ); return false'><img src='style_images/<#IMG_DIR#>/folder_editor_images/rte-ok.png' style='vertical-align:middle;padding-bottom:2px' alt='' /> {$this->ipsclass->lang['qe_complete_edit']}</a></div>
	   </div>
		" . (($show_reason) ? ("
			<div style='text-align:left'>
				{$this->ipsclass->lang['reason_for_edit']}: <input type='text' size='35' maxlength='250' id='post_edit_reason' name='post_edit_reason' value='$post_edit_reason' />
			</div>
		") : ("")) . "
   </div>
</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_options:desc::trigger:>
//===========================================================================
function mod_options($jump="",$can_set_open_time="",$can_set_close_time="",$mytimes=array()) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--start-->
" . (($jump != "") ? ("
<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['mod_options']}</strong>
	</td>
	<td class='row2'>
		&nbsp;{$jump}</select>
	</td>
</tr>
") : ("")) . "
<!--middle-->
" . (($can_set_open_time == 1) ? ("
<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['mod_open_time']}</strong><br />
		<span class='desc'>{$this->ipsclass->lang['post_optional']}</span>
	</td>
	<td class='row2'>
		<span class='desc'>{$this->ipsclass->lang['mod_date_format']}</span> &nbsp; <input type='text' size='11' name='open_time_date' value='{$mytimes['open_date']}' /> &nbsp; <span class='desc'>{$this->ipsclass->lang['mod_time_format']}</span> &nbsp; <input type='text' size='5' name='open_time_time' value='{$mytimes['open_time']}' />
	</td>
</tr>
") : ("")) . "

" . (($can_set_close_time == 1) ? ("
<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['mod_close_time']}</strong><br />
		<span class='desc'>{$this->ipsclass->lang['post_optional']}</span>
	</td>
	<td class='row2'>
		<span class='desc'>{$this->ipsclass->lang['mod_date_format']}</span> &nbsp; <input type='text' size='11' name='close_time_date' value='{$mytimes['close_date']}' /> &nbsp; <span class='desc'>{$this->ipsclass->lang['mod_time_format']}</span> &nbsp; <input type='text' size='5' name='close_time_time' value='{$mytimes['close_time']}' /></span>
	</td>
</tr>
") : ("")) . "
<!--end-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:nameField_reg:desc::trigger:>
//===========================================================================
function nameField_reg() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!-- REG NAME -->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:nameField_unreg:desc::trigger:>
//===========================================================================
function nameField_unreg($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='subtitle' colspan='2'>Name</td>
</tr>
<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['guest_name']}</strong>
	</td>
	<td class='row2'>
		<input type=\"text\" size=\"50\" maxlength=\"40\" name=\"UserName\" value=\"$data\" class=\"textinput\" />
	</td>
</tr>
<!--GUEST.CAPTCHA-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:poll_box:desc::trigger:>
//===========================================================================
function poll_box($max_poll_questions="",$max_poll_choices="",$poll_questions="",$poll_choices="",$poll_votes="",$show_open="",$poll_question="",$is_mod=0,$poll_multi="",$poll_only='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src=\"jscripts/ipb_poll.js\"></script>
 <script type=\"text/javascript\">
  var showfullonload     = parseInt(\"{$show_open}\");
  var is_mod             = parseInt(\"{$is_mod}\");
  
  // Questions
  var poll_questions     =
  {
{$poll_questions}
  };
  
  var poll_choices       = 
  {
{$poll_choices}
  };
  
  var poll_votes       = 
  {
{$poll_votes}
  };
  var poll_multi       = 
  {
{$poll_multi}
  };
  
  // Setting elements
  var max_poll_questions = parseInt(\"{$max_poll_questions}\");
  var max_poll_choices   = parseInt(\"{$max_poll_choices}\");
  
  // HTML elements
  var html_add_question     = \"[<a href='#' title='{$this->ipsclass->lang['poll_tt_add_question']}' style='color:green;font-weight:bold' onclick='return poll_add_question()'>{$this->ipsclass->lang['poll_tt_add_question']}</a>]\";
  var html_add_choice       = \"<li>&nbsp;[<a href='#' title='{$this->ipsclass->lang['poll_tt_add_choice']}' style='color:green;font-weight:bold' onclick='return poll_add_choice(\"+'\"'+'<%1>'+'\"'+\")'>{$this->ipsclass->lang['poll_tt_add_choice']}</a>]</li>\";
  var html_question_box     = \"<input type='text' id='question_<%1>' name='question[<%1>]' size='50' class='input' value='<%2>' /> [<a href='#' title='{$this->ipsclass->lang['poll_tt_remove_question']}' style='color:red;font-weight:bold' onclick='return poll_remove_question(\"+'\"'+'<%1>'+'\"'+\")'>X</a>]<br /><input class='checkbox' type='checkbox' id='multi_<%1>' name='multi[<%1>]' value='1' <%3> /><span class='forumdesc'>{$this->ipsclass->lang['poll_multichoice']}</span>\";
  var html_votes_box        = \"&nbsp;<input type='text' id='votes_<%1>_<%2>' name='votes[<%1>_<%2>]' size='5' class='input' value='<%3>' />\";
  var html_choice_box       = \"<li><input type='text' id='choice_<%1>_<%2>' name='choice[<%1>_<%2>]' size='35' class='input' value='<%3>' /><%4> [<a href='#' title='{$this->ipsclass->lang['poll_tt_remove_choice']}' style='color:red;font-weight:bold' onclick='return poll_remove_choice(\"+'\"'+'<%1>_<%2>'+'\"'+\")'>X</a>]</li>\";
  var html_choice_wrap      = \"<ol><%1></ol>\";
  var html_question_wrap    = \"<div><%1></div>\";
  var html_stat_wrap        = \"<br /><div><%1></div>\";
  
  // Lang elements
  var js_lang_confirm    = \"{$this->ipsclass->lang['poll_tt_confirm']}\";
  var poll_stat_lang     = \"{$this->ipsclass->lang['poll_tt_stat_lang']}\";
 </script>

<tr>
        <td class='subtitle' colspan='2'>{$this->ipsclass->lang['pro_poll']}</td>
</tr>
<tr>
	<td class='row1' style='text-align: right; vertical-align: top'>
		<strong>{$this->ipsclass->lang['poll_fs_options']}</strong>
	</td>
	<td class='row2'>
		<div id='poll-box-closed' style='display: none'>
			<a href='#' onclick='show_poll_form(); return false;'>{$this->ipsclass->lang['poll_manage_link']}</a>
		</div>
		<div id='poll-box-open' style='display: none'>
			<fieldset>
		     	<legend><strong>{$this->ipsclass->lang['poll_fs_title']}</strong></legend>
		     	<input type='text' size='40' class='input' name='poll_question' value='{$poll_question}' />
		    </fieldset>
		" . (($this->ipsclass->vars['ipb_poll_only']==1) ? ("
			<fieldset>
		     	<legend><strong>{$this->ipsclass->lang['poll_only_title']}</strong></legend>
		     	<input class='checkbox' type='checkbox' name='poll_only' value='1' {$poll_only} /> <span class='forumdesc'>{$this->ipsclass->lang['poll_only_desc']}<span>
		    </fieldset>
		") : ("")) . "
		    <!-- MAIN POLL AREA -->
		    <fieldset>
		     	<legend><strong>{$this->ipsclass->lang['poll_fs_content']}</strong></legend>
		      	<div id='poll-box-main'>

		     	</div>
		    </fieldset>
		    <!-- MAIN POLL AREA -->
		    <br />
		    <a href='#' onclick='close_poll_form(); return false;'>{$this->ipsclass->lang['poll_fs_close']}</a>
		    <div id='poll-box-stat'></div>
		</div>
	</td>
</tr>
<!-- INIT DIVS -->
 <script type=\"text/javascript\">
  poll_init_state();
 </script>
 <!--/ INIT DIVS -->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:poll_end_form:desc::trigger:>
//===========================================================================
function poll_end_form($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td class=\"formbuttonrow\" colspan=\"2\"><input type=\"submit\" name=\"submit\" value=\"$data\" tabindex=\"4\" class=\"button\" accesskey=\"s\" />&nbsp;</td>
	</tr>
</table>
</form>
<br style=\"clear: all;\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:poll_options:desc::trigger:>
//===========================================================================
function poll_options() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
<input type=\"checkbox\" size=\"40\" value=\"1\" name=\"allow_disc\" class=\"checkbox\" />&nbsp;{$this->ipsclass->lang['poll_only']}";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:postbox_wrap:desc::trigger:>
//===========================================================================
function postbox_wrap($editor_html="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='subtitle' colspan='2'>{$this->ipsclass->lang['pro_post']}</td>
</tr>
<tr>
	<td class='row2' colspan='2'>
		" . (($this->ipsclass->browser['browser'] == 'ie' AND $this->ipsclass->browser['version'] >= 7.0) ? ("
			<div>
		") : ("
			<div>
		")) . "			 				
				{$editor_html}
				<!--UPLOAD FIELD-->
			</div>
	</td>
</tr>
<tr>
	<td class='subtitle' colspan='2'>{$this->ipsclass->lang['pro_postops']}</td>
</tr>
<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['po_options']}</strong>
	</td>
	<td class='row2'>
		<!--IBF.HTML-->
		<!--IBF.EMO-->
		<!--IBF.SIG-->
		<!--IBF.TRACK-->
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:PostIcons:desc::trigger:>
//===========================================================================
function PostIcons() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['post_icon']}</strong><br />
		<span class='desc'>{$this->ipsclass->lang['post_optional']}</span>
	</td>
	<td class='row2'>
		<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"1\" />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon1.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"2\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon2.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"3\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon3.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"4\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon4.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"5\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon5.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"6\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon6.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"7\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon7.gif\"  align='middle' alt='' /><br />
		  <input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"8\" />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon8.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"9\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon9.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"10\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon10.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"11\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon11.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"12\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon12.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"13\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon13.gif\"  align='middle' alt='' />&nbsp;&nbsp;&nbsp;<input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"14\"  />&nbsp;&nbsp;<img src=\"{$this->ipsclass->vars['img_url']}/folder_post_icons/icon14.gif\"  align='middle' alt='' /><br />
	      <input type=\"radio\" class=\"radiobutton\" name=\"iconid\" value=\"0\" checked=\"checked\" />&nbsp;&nbsp;{$this->ipsclass->lang['picons_none']}
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:preview:desc::trigger:>
//===========================================================================
function preview($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src=\"jscripts/ipb_topic.js\"></script>
<div class=\"borderwrap\">
	<div class=\"subtitle\">{$this->ipsclass->lang['post_preview']}</div>
	<div class=\"row1\" style='padding-bottom:1px;'>
		<div class=\"postcolor\" style='padding:4px;'>$data</div>
	</div>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:table_structure:desc::trigger:>
//===========================================================================
function table_structure() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--FORUM RULES--><br />
<!--START TABLE-->
<!--NAME FIELDS-->
<!--TOPIC TITLE-->
<!--POLL BOX-->
<!--POST BOX-->
<!--MOD OPTIONS-->
<!--POST ICONS-->
<!--END TABLE-->";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:table_top:desc::trigger:>
//===========================================================================
function table_top($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
<table cellspacing=\"0\" class='ipbtable'>
<tr>
	<td class=\"maintitle\" colspan=\"2\">$data</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:TopicSummary_body:desc::trigger:>
//===========================================================================
function TopicSummary_body($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td class=\"post_head\" valign=\"top\" width=\"20%\"><b>{$data['author']}</b></td>
		<td class=\"post_head\" valign=\"top\" width=\"80%\">{$this->ipsclass->lang['posted_on']} {$data['date']}</td>
	</tr>
	<tr>
		<td class=\"post1 post_left\" valign=\"top\" width=\"20%\">&nbsp;</td>
		<td class=\"post1\" valign=\"top\" width=\"80%\"><span class=\"postcolor\">{$data['post']}</span></td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topicsummary_body_hidden:desc::trigger:>
//===========================================================================
function topicsummary_body_hidden($data=array()) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td class=\"post_head\" valign=\"top\" width=\"20%\"><b>{$data['author']}</b></td>
		<td class=\"post_head\" valign=\"top\" width=\"80%\">{$this->ipsclass->lang['posted_on']} {$data['date']}</td>
	</tr>
	<tr>
		<td class=\"post1 post_left\" valign=\"top\" width=\"20%\">&nbsp;</td>
		<td class=\"post1\" valign=\"top\" width=\"80%\"><span class=\"postcolor\">{$this->ipsclass->lang['ignore_first_line']} {$data['members_display_name']}.</span></td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:TopicSummary_bottom:desc::trigger:>
//===========================================================================
function TopicSummary_bottom() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td class=\"formbuttonrow\" colspan=\"2\"><a href=\"javascript:PopUp('index.{$this->ipsclass->vars['php_ext']}?act=ST&amp;f={$this->ipsclass->input['f']}&amp;t={$this->ipsclass->input['t']}','TopicSummary',700,450,1,1)\">{$this->ipsclass->lang['review_topic']}</a></td>
	</tr>
	<tr>
		<td class=\"catend\" colspan=\"2\"><!-- no content --></td>
	</tr>
</table>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:TopicSummary_top:desc::trigger:>
//===========================================================================
function TopicSummary_top() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src=\"jscripts/ipb_topic.js\"></script>
<br />
<div class=\"borderwrap\">
  <div class=\"maintitle\">{$this->ipsclass->lang['last_posts']}</div>
  <table class='ipbtable' cellspacing=\"0\">";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topictitle_fields:desc::trigger:>
//===========================================================================
function topictitle_fields($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='subtitle' colspan='2'>Topic Details</td>
</tr>
<tr>
 	<td class='row1' style='width: 20%; text-align: right'>
		<strong>{$this->ipsclass->lang['topic_title']}</strong>
 	</td>
	<td class='row2'>
		<input type=\"text\" size=\"50\" maxlength=\"{$this->ipsclass->vars['topic_title_max_len']}\" name=\"TopicTitle\" value=\"{$data['TITLE']}\" tabindex=\"1\" />
	</td>
</tr>
<tr>
	<td class='row1' style='text-align: right'>
		<strong>{$this->ipsclass->lang['topic_desc']}</strong>
	</td>
	<td class='row2'>
		<input type=\"text\" size=\"50\" maxlength=\"70\" name=\"TopicDesc\" value=\"{$data['DESC']}\" tabindex=\"2\" />
		<span class='desc'>{$this->ipsclass->lang['post_optional']}</span>
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:Upload_field:desc::trigger:>
//===========================================================================
function Upload_field($post_key="",$type="",$id="",$forum_id=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class='subtitle' colspan='2'>{$this->ipsclass->lang['pro_attach']}</td>
</tr>
<tr>
	<td class='row2' colspan='2'>
		

		<script type=\"text/javascript\" src='jscripts/ips_attach.js'></script>
	
		<!-- ATTACH -->
		 <div id='ips-attach-div-parent' class='attach-parentdiv' style='display:none;clear:both'>
		 	<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style='padding:0px'>
			 <tr>
			  <td width='1%' style='padding:0px' nowrap='nowrap'><img class=\"ipd\" src=\"{$this->ipsclass->vars['img_url']}/folder_attach_images/attach_logo.png\"  border=\"0\" alt=\"\" /> <strong>{$this->ipsclass->lang['attach_header']}</strong></td>
			  <td width='99%' style='padding:0px' align='right'>
				<div class='attach-menubutton' id='ips-attach-menu' style='margin-right:2px;width:293px;'>
					<table cellpadding=\"0\" cellspacing=\"0\" border=\"0\" style='padding:0px'>
					<tr>
						<td style='padding:0px'><div style='width:265px;text-align:left;font-size:10px;'>{$this->ipsclass->lang['attach_manage_current']} <span id='ips-attach-menu-text'>(0)</span></div></td>
						<td style='padding:0px' align='right'><img class=\"ipd\" src=\"{$this->ipsclass->vars['img_url']}/folder_editor_images/icon_open.gif\"  border=\"0\" alt=\"\" /></td>
					</tr>
					</table>
				</div>
			  </td>
			 </tr>
			 </table>
		 	 <div id='ips-attach-div-iframe' style='height:67px;width:100%;text-align:center'></div>
			 <div id='ips-attach-div-status' style='height:20px;width:100%;text-align:left;font-weight:bold'></div>
		 </div>
		 <!-- ATTACH -->
		 <!-- Status DIV -->
		 <div id=\"ips-attach-message\" style='display:none;z-index:999;' class='attach-messagediv'>
			<br />
			<br />
			<img class=\"ipd\" src=\"{$this->ipsclass->vars['img_url']}/folder_attach_images/attach_wait.gif\"  border=\"0\" alt=\"\" />
			<br />
			<br />
			<span class='attach-msg-span' id='ips-attach-message-span'>&nbsp;</span><br clear='all' /><br />
		 </div>
			<script type=\"text/javascript\">
			//<![CDATA[
			// INIT and such
			ipsattach.iframe_init_url    = \"{$this->ipsclass->base_url}&act=attach&code=attach_upload_show&attach_rel_module={$type}&attach_rel_id={$id}&attach_post_key={$post_key}&--ff--forum_id=$forum_id\";
			ipsattach.iframe_remove_url  = \"{$this->ipsclass->base_url}&act=attach&code=attach_upload_remove&attach_rel_module={$type}&attach_rel_id={$id}&attach_post_key={$post_key}&--ff--forum_id=$forum_id\";
			ipsattach.iframe_classname   = 'attach-iframe';
			ipsattach.images_url         = ipb_skin_url;
			ipsattach.lang =
			{
				'no_items'            : '{$this->ipsclass->lang['attach_js__no_items']}',
				'uploading_file'      : '{$this->ipsclass->lang['attach_js__uploading']}',
				'init_progress'       : '{$this->ipsclass->lang['attach_js__init']}',
				'upload_ok'           : \"{$this->ipsclass->lang['attach_js__upload_success']}\",
				'upload_failed'       : \"{$this->ipsclass->lang['attach_js__upload_fail']}\",
				'upload_too_big'      : \"{$this->ipsclass->lang['attach_js__upload_fail1']}\",
				'invalid_mime_type'   : \"{$this->ipsclass->lang['attach_js__upload_fail2']}\",
				'no_upload_dir'       : \"{$this->ipsclass->lang['attach_js__upload_fail3']}\",
				'no_upload_dir_perms' : \"{$this->ipsclass->lang['attach_js__upload_fail4']}\",
				'upload_no_file' 	  : \"{$this->ipsclass->lang['attach_js__upload_fail5']}\",
				'ready'               : \"{$this->ipsclass->lang['attach_js__ready']}\",
				'attach_remove'       : \"{$this->ipsclass->lang['attach_js__delete']}\",
				'attach_insert'       : \"{$this->ipsclass->lang['attach_js__insert']}\",
				'remove_warn'	 	  : \"{$this->ipsclass->lang['attach_js__confirm']}\",
				'attach_removed'      : \"{$this->ipsclass->lang['attach_js__isremoved']}\",
				'attach_removal'      : \"{$this->ipsclass->lang['attach_js__removing']}\"
			};
			ipsattach.init();
			ipsattach.show_attach_box();
			//]]>
			</script>
	</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:uploadbox_entry:desc::trigger:>
//===========================================================================
function uploadbox_entry($attach="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td width=\"1%\"><img src=\"{$this->ipsclass->vars['mime_img']}/{$attach['image']}\" alt=\"\" /></td>
		<td width=\"35%\"><b>{$attach['attach_file']}</b></td>
		<td width=\"20%\">({$attach['size']})</td>
		<td width=\"10%\"><input type=\"submit\" name=\"removeattach_{$attach['attach_id']}\" class=\"codebuttons\" onclick=\"removeattach({$attach['attach_id']})\" value=\"{$this->ipsclass->lang['attach_remove']}\" /></a>
		<td width=\"10%\"><input type=\"button\" name=\"id{$attach['attach_id']}\" class=\"codebuttons\" onclick=\"insert_attach_to_textarea({$attach['attach_id']})\" value=\"{$this->ipsclass->lang['attach_button']}\" title=\"{$this->ipsclass->lang['attach_button_title']}\" /></a>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:uploadbox_tableend:desc::trigger:>
//===========================================================================
function uploadbox_tableend($spaceleft="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</tr>
</table>
<i>$spaceleft</i>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:uploadbox_tabletop:desc::trigger:>
//===========================================================================
function uploadbox_tabletop() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
  <div class='borderwrap' style='padding:4px;width:70%;margin-left:4px'>
  	<table class='ipbtable' cellspacing=\"0\">";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
add_edit_box,guest_captcha,mod_options,nameField_unreg,poll_box,postbox_wrap,PostIcons,preview,table_top,TopicSummary_body,topicsummary_body_hidden,TopicSummary_top,topictitle_fields,Upload_field
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>