<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_blog_show_3 {

 var $ipsclass;
//===========================================================================
// <ips:blog_show_comment:desc::trigger:>
//===========================================================================
function blog_show_comment($comment="",$author="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<!--Begin Comment Number {$comment['comment_id']}-->
<table class='ipbtable' cellspacing=\"0\">
	<tr>
		<td valign=\"middle\" class=\"post_head\" width=\"1%\">
			<a name=\"comment{$comment['comment_id']}\"></a>
			" . (($author['id']) ? ("
				<div id=\"comment-member-{$comment['comment_id']}\" class='popmenubutton-new-out'>
					<span class=\"{$comment['name_css']}\">{$author['_pp_online_image']}<a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\">{$author['members_display_name']}</a></span>
				</div>
				<!-- member menu -->
				<div class='popupmenu-new' id='comment-member-{$comment['comment_id']}_menu' style='display:none;width:210px'>
					<div class='popupmenu-item-last'>
						<div style='float:right'>
							<div class='pp-image-thumb-wrap'>
								<img src='{$author['pp_thumb_photo']}' width='{$author['pp_thumb_width']}' height='{$author['pp_thumb_height']}' />
							</div>
							" . (($this->ipsclass->vars['pp_allow_member_rate']) ? ("
								<div style='margin-top:5px;margin-left:6px;'>
									<img src=\"{$this->ipsclass->vars['img_url']}/rating_{$author['_pp_rating_real']}_mini.gif\" alt='Rating: {$author['_pp_rating_real']}' style='vertical-align:middle' border='0' />
								</div>
							") : ("")) . "
						</div>
						<div class='popupmenu-item'>
							{$author['_pp_gender_image']} <a href=\"{$this->ipsclass->base_url}showuser={$author['id']}\">View Public Profile</a>
						</div>
						" . (($this->ipsclass->member['id']) ? ("
							<div class='popupmenu-item'>
								" . ((in_array( $author['id'], array_keys( $this->ipsclass->member['_cache']['friends'] ) )) ? ("
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_remove_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=remove&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>Remove Friend</a>
								") : ("
									<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/friend_add_small.png' alt='' border='0' /> <a href=\"#\" onclick='friends_pop(\"&amp;do=add&amp;member_id={$author['id']}&amp;md5check={$this->ipsclass->md5_check}\"); return false'>Add as Friend</a>
								")) . "
							</div>
							<div class='popupmenu-item'>
								<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/send_pm_small.png' alt='' border='0' /> <a href=\"{$this->ipsclass->base_url}act=Msg&amp;CODE=4&amp;MID={$author['id']}\">Send Message</a>
							</div>
						") : ("")) . "
						<div class='popupmenu-item-last'>
							<img src='{$this->ipsclass->vars['img_url']}/folder_profile_portal/find_posts.png' alt='' border='0' /> <a href='{$this->ipsclass->base_url}act=Search&amp;CODE=getalluser&amp;mid={$author['id']}'>Find Member's Posts</a>
						</div>
					</div>
				</div>
				<!-- member menu -->
				<script type=\"text/javascript\">
					ipsmenu.register( \"comment-member-{$comment['comment_id']}\", '', 'popmenubutton-new', 'popmenubutton-new-out' );
				</script>
			") : ("
				<span class=\"{$comment['name_css']}\">{$author['_members_display_name']}</span>
			")) . "
			
		</td>
		<td class=\"post_head\" valign=\"middle\" width=\"99%\">
			<!-- POSTED DATE DIV -->
			<div style=\"float: left;\">
				<span class=\"postdetails\"><img src='{$this->ipsclass->vars['img_url']}/to_post_off.gif' alt='post' border='0' style='padding-bottom:2px' /> {$comment['comment_date']}</span>
			</div>
			<!-- REPORT / DELETE / EDIT / QUOTE DIV -->
			<div align=\"right\">
				<span class=\"postdetails\">{$comment['ip_address']} {$this->ipsclass->lang['comment_link']}
					<a title=\"{$this->ipsclass->lang['tt_link']}\" href=\"#\" onclick=\"link_to_comment({$comment['comment_id']}); return false;\">#{$comment['comment_count']}</a></span>
			</div>
		</td>
	</tr>
	<tr>
		<td valign=\"top\" class=\"{$comment['post_css']} post_left\">
        	<span class=\"postdetails\">
        		{$author['avatar']}<br /><br />
        		{$author['title']}<br />
        		{$author['member_rank_img']}<br /><br />
        		{$author['member_group']}<br />
        		{$author['member_posts']}<br />
        		{$author['member_joined']}<br />
        		{$author['member_location']}
        		{$author['member_number']}<br />
				" . (($author['custom_fields'] != "") ? ("
					{$author['custom_fields']}
				") : ("")) . "
				<br />
        		{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
        	</span><br />
        	<img src=\"{$this->ipsclass->vars['img_url']}/spacer.gif\" alt=\"\" width=\"160\" height=\"1\" /><br />
       </td>
       <td width=\"100%\" valign=\"top\" class=\"{$comment['post_css']}\" id='comment-main-{$comment['comment_id']}'>
			<!-- THE COMMENT {$comment['comment_id']} -->
			<div class=\"postcolor\" id='comment-{$comment['comment_id']}'>{$comment['comment_text']}</div>
				{$comment['signature']}
			<!-- THE COMMENT -->
		</td>
	</tr>
	<tr>
		<td class=\"formbuttonrow\" nowrap=\"nowrap\">
			<div style='text-align:left'><a href=\"javascript:scroll(0,0);\"><{P_UP}></a>{$comment['report_link']}</div>
		</td>
		<td class=\"formbuttonrow\" nowrap=\"nowrap\">
         	<div align=\"right\">
         		{$comment['approve_button']}{$comment['delete_button']}{$comment['edit_button']}{$comment['mquote_button']}{$comment['reply_button']}
         	</div>
         </td>
	</tr><tr>
	<td class=\"catend\" colspan=\"2\"><!-- no content --></td>
</tr>
</table>
<script type='text/javascript'>
//<![CDATA[
if ( ajax_loaded && use_enhanced_js )
{
menu_build_menu( 'edit-but-{$comment['comment_id']}',
	new Array(  img_item + \" <a title='{$this->ipsclass->lang['edit_full_desc']}' href='{$this->ipsclass->vars['blog_url']}req=editcomment&amp;eid={$comment['entry_id']}&amp;cid={$comment['comment_id']}&amp;st={$this->ipsclass->input['st']}'>{$this->ipsclass->lang['edit_full_title']}</a>\",
				img_item + \" <a href='#' title='{$this->ipsclass->lang['edit_quick_desc']}' onclick='return ajax_prep_for_edit({$comment['entry_id']},{$comment['comment_id']}, event);'>{$this->ipsclass->lang['edit_quick_title']}</a>\" ) );
}
//]]>
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:blog_show_entry:desc::trigger:>
//===========================================================================
function blog_show_entry($entry="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class='maintitle'>
	<div style=\"float:right;\"><a href=\"{$this->ipsclass->base_url}showuser={$entry['entry_author_id']}\">{$entry['entry_author_name']}</a></div>
		<p>{$entry['icon']}&nbsp;<a href=\"{$this->ipsclass->vars['blog_url']}showentry={$entry['entry_id']}\"><b>{$entry['entry_name']}</b></a></p>
	</div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td class=\"post_head\" valign=\"top\">
" . (($entry['entry_category']) ? ("
<!-- CATEGORY DIV -->
				<div style=\"float:right;\">
&nbsp;|&nbsp;<span class=\"postdetails\">{$this->ipsclass->lang['entry_category_in']} <a href=\"{$this->ipsclass->vars['blog_url']}&amp;cat={$entry['category_id']}\">{$entry['entry_category']}</a></span>
				</div>
") : ("")) . "
				<div style=\"float:right;\">
					<span class=\"postdetails\">
						<a href=\"{$this->ipsclass->vars['blog_url']}&amp;req=sendentry&amp;eid={$entry['entry_id']}&amp;st={$this->ipsclass->input['st']}\">{$this->ipsclass->lang['entry_send']}</a>&nbsp;|&nbsp;<a href=\"{$this->ipsclass->vars['blog_url']}&amp;req=printentry&amp;eid={$entry['entry_id']}\">{$this->ipsclass->lang['entry_print']}</a>
					</span>
				</div>
				<!-- ENTRY DATE DIV -->
				<div align=\"left\">
					<span class=\"postdetails\"><img src='{$this->ipsclass->vars['img_url']}/to_post_off.gif' alt='entry' border='0' style='padding-bottom:2px' /> {$entry['entry_date']}</span>
				</div>
			</td>
		</tr>
	</table>
<!--ENTRY.POLL-->
	<div class='{$entry['css']}' style='padding:4px 4px 4px 4px'><div class='postcolor'>
" . (($entry['hide_private']) ? ("
<span style=\"color:#992A2A;\">{$this->ipsclass->lang['blog_private_entry']}<br /><br />
<a href=\"{$this->ipsclass->vars['blog_url']}showentry={$entry['entry_id']}&amp;showprivate=1\">{$this->ipsclass->lang['blog_show_privateentry']}</a></span>
") : ("
{$entry['entry']} <!--IBF.ATTACHMENT_{$entry['entry_id']}-->
")) . "
</div></div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td class=\"formbuttonrow\" nowrap=\"nowrap\">
				<div style='text-align:left'>
					<div style=\"float:right;\">
					<a title=\"{$this->ipsclass->lang['permalink_title']}\" href=\"#\" onclick=\"permalink_to_entry({$entry['entry_id']}); return false;\" >{$this->ipsclass->lang['permalink']}</a>&nbsp;|&nbsp;<a href=\"{$this->ipsclass->vars['blog_url']}showentry={$entry['entry_id']}#comments\">{$this->ipsclass->lang['entry_comments']} {$entry['entry_num_comments']}</a>
" . (($entry['new_comment']) ? ("
&nbsp;<a href=\"{$this->ipsclass->vars['blog_url']}showentry={$entry['entry_id']}&amp;show=newcomment\">{$entry['new_comment']}</a>
") : ("")) . "
" . (($entry['queued_comment']) ? ("
&nbsp;{$entry['queued_comment']}
") : ("")) . "
" . (($entry['allow_trackback']) ? ("
&nbsp;|&nbsp;<a href=\"{$this->ipsclass->vars['blog_url']}showentry={$entry['entry_id']}#trackbacks\">{$this->ipsclass->lang['entry_trackbacks']} {$entry['entry_trackbacks']}</a>
") : ("")) . "
					</div>
" . (($entry['eopt_autohide']) ? ("
<div id='modmenuopen_{$entry['entry_id']}' style='display:none;'>
") : ("")) . "
						{$entry['send_trackback']}{$entry['publish']}{$entry['lock']}{$entry['del_button']}{$entry['edit_button']}
" . (($entry['eopt_autohide']) ? ("
<a href=\"#\" onclick=\"ShowHide('modmenuopen_{$entry['entry_id']}','modmenuclosed_{$entry['entry_id']}'); return false;\"><{P_CLOSEEOPT}></a>
					</div>
					<div id='modmenuclosed_{$entry['entry_id']}'><a href=\"#\" onclick=\"ShowHide('modmenuopen_{$entry['entry_id']}','modmenuclosed_{$entry['entry_id']}'); return false;\"><{P_OPENEOPT}></a></div>
") : ("")) . "
				</div>
			</td>
		</tr>
	</table>
	<div class=\"catend\"><!-- no content --></div>
</div>
<!--
<rdf:RDF xmlns:rdf=\"http://www.w3.org/1999/02/22-rdf-syntax-ns#\"
         xmlns:dc=\"http://purl.org/dc/elements/1.1/\"
         xmlns:trackback=\"http://madskills.com/public/xml/rss/module/trackback/\">
<rdf:Description
    rdf:about=\"{$this->ipsclass->vars['blog_url']}showentry={$entry['entry_id']}\"
    dc:identifier=\"{$this->ipsclass->vars['blog_url']}showentry={$entry['entry_id']}\"
    dc:title=\"{$entry['entry_name']}\"
    trackback:ping=\"{$this->ipsclass->vars['blog_url']}req=trackback&eid={$entry['entry_id']}\" />
</rdf:RDF>
-->
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:entry_album:desc::trigger:>
//===========================================================================
function entry_album($album="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div align=\"right\" style=\"width:100%;\"><a href=\"{$this->ipsclass->base_url}automodule=gallery&amp;cmd=slideshow&amp;show=first&amp;mid={$album['member_id']}&amp;album={$album['album_id']}&amp;duration=5&amp;closewindow=1&amp;hfoff=1\" target=\"_blank\"><{A_SSBUTTON}></a></div>
<div class='thumbwrap'><table class='ipbtable' cellspacing=\"0\"><tr><!--ALBUM--></tr></table></div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:entry_album_thumb:desc::trigger:>
//===========================================================================
function entry_album_thumb($img="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<td class=\"gal_curr\" align=\"center\" width=\"{$img['col_width']}%\" valign=\"bottom\">{$img['img_link']}</td>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
blog_show_comment,blog_show_entry,entry_album,entry_album_thumb
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>