<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_bugtracker_3 {

 var $ipsclass;
//===========================================================================
// <ips:button_delete:desc::trigger:>
//===========================================================================
function button_delete($bug_entry_id="",$bug_title_id="",$product_id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"javascript:delete_post('{$this->ipsclass->base_url}autocom=bugtracker&amp;code=bug_entry_delete&amp;bug_entry_id={$bug_entry_id}&amp;bug_title_id={$bug_title_id}&amp;product_id={$product_id}&amp;st={$this->ipsclass->input['st']}&amp;auth_key={$this->ipsclass->md5_check}')\"><{P_DELETE}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:button_edit:desc::trigger:>
//===========================================================================
function button_edit($bug_entry_id="",$bug_title_id="",$product_id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<a href=\"{$this->ipsclass->base_url}autocom=bugtracker&amp;code=post_edit_bug&amp;bug_entry_id={$bug_entry_id}&amp;bug_title_id={$bug_title_id}&amp;product_id={$product_id}&amp;st={$this->ipsclass->input['st']}\"><{P_EDIT}></a>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:post_bug_form:desc::trigger:>
//===========================================================================
function post_bug_form($type="",$project="",$post="",$topic="",$can_manage="",$title="",$formbit="",$button="",$editor_html="",$status_dd="",$projects_dd="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action='{$this->ipsclass->base_url}autocom=bugtracker&amp;code={$formbit}&amp;product_id={$project['product_id']}&amp;bug_title_id={$topic['bug_title_id']}&amp;bug_entry_id={$post['bug_entry_id']}' method='post' name='REPLIER' onsubmit='return ValidateForm()'>
<input type='hidden' name='removeattachid' value='0' />
<div class='borderwrap'>
 <div class='maintitle'>{$title}</div>
 <table cellspacing=\"0\" class='ipbtable'>
" . (($type == "add" OR $( $type == 'edit' AND $can_manage == 1 )) ? ("
<tr>
	 <td colspan='2' align='center' class='bg1'>
	 <div style='width:100%;' align='center' class='borderwrap'>
	 <table cellpadding='0' cellspacing='0' width='100%' class='darkrow3'>
	   <tr>
		<td align=\"right\" width='20%'>
		 <strong>Bug Report Title</strong>
		</td>
		<td align=\"left\" width='80%'>
		 <input type=\"text\" size=\"50\" maxlength=\"300\" name=\"bug_title_title\" value=\"{$topic['bug_title_title']}\" tabindex=\"1\" class=\"forminput\" />
		</td>
	   </tr>
	  </table>
	 </div>
	 </td>
	</tr>
") : ("")) . "
" . (($type == "add" OR $( $type == 'edit' AND $can_manage == 1 ) OR $( $type == 'reply' AND $can_manage == 1 )) ? ("
<tr>
	 <td colspan='2' align='center' class='bg1'>
	 <div style='width:100%;' align='center' class='borderwrap'>
	 <table cellpadding='0' cellspacing='0' width='100%' class='darkrow3'>
	   <tr>
		<td align=\"right\" width='20%'>
		 <strong>Assign to Product</strong>
		</td>
		<td align=\"left\" width='80%'>
		 {$projects_dd}
		</td>
	   </tr>
	  </table>
	 </div>
	 </td>
	</tr>
") : ("")) . "
" . (($type == "add" OR $( $type == 'edit' AND $can_manage == 1 ) OR $( $type == 'reply' AND $can_manage == 1 )) ? ("
<tr>
	 <td colspan='2' align='center' class='bg1'>
	 <div style='width:100%;' align='center' class='borderwrap'>
	 <table cellpadding='0' cellspacing='0' width='100%' class='darkrow3'>
	   <tr>
		<td align=\"right\" width='20%'>
		 <strong>Assign Status</strong>
		</td>
		<td align=\"left\" width='80%'>
		 {$status_dd}
		</td>
	   </tr>
	  </table>
	 </div>
	 </td>
	</tr>
") : ("")) . "

	<tr>
	<td colspan='2' align='center' class='bg1'>
	<div align='center' class='borderwrap'>
	<table cellpadding='0' cellspacing='0' width='100%' class='darkrow3'>
	 <tr>
	  <td align='center' valign=\"top\">
	   {$editor_html}
	  </td>
	 </tr>
	</table>
	</div>
	</td>
   </tr>
  <tr>
	 <td class=\"formbuttonrow\" colspan=\"2\">
		 <input type=\"submit\" name=\"submit\" value=\"$button\" tabindex=\"7\" class=\"button\" accesskey=\"s\" />&nbsp;
	 </td>
 </tr>
</table>
</div>
</form>
<br style=\"clear: all;\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:project_dropdown_row:desc::trigger:>
//===========================================================================
function project_dropdown_row($name="",$value="",$selected='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<option value='$value'{$selected}>$name</option>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:project_dropdown_wrapper:desc::trigger:>
//===========================================================================
function project_dropdown_wrapper($name="",$content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<select name='$name'>$content</select>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_all_row:desc::trigger:>
//===========================================================================
function show_all_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
 <td class='row1' align='center'><{C_ON}></td>
 <td class='row1'><a href='{$this->ipsclass->base_url}autocom=bugtracker&amp;code=show_project&amp;product_id={$data['product_id']}'><strong>{$data['product_title']}</strong></a><div class='desc'>{$data['product_description']}</div></td>
 <td class='row2' align='center'>{$data['_total']}</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_all_wrapper:desc::trigger:>
//===========================================================================
function show_all_wrapper($content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class='borderwrap'>
 <div class='maintitle'>Bug Tracker</div>
 <table cellpadding='0' cellspacing='1' class='ipbtable'>
 <tr>
  <th width='1%'>&nbsp;</th>
  <th width='94%'>Project</th>
  <th width='5%' align='center'>Bugs</th>
 </tr>
 $content
 </table>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_bug_row:desc::trigger:>
//===========================================================================
function show_bug_row($author="",$post="",$buttons="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class='ipbtable' cellspacing=\"1\">
 <tr>
	 <td valign=\"middle\" class=\"row2\"><span class=\"normalname\">{$author['members_display_name']}</span></td>
	 <td class=\"row2\" valign=\"top\">
		 <!-- POSTED DATE DIV -->
		 <div class=\"row2\" style='float:left'>
			 <span class=\"postdetails\"><img src='{$this->ipsclass->vars['img_url']}/to_post_off.gif' alt='post' border='0' style='padding-bottom:2px' /> <b>Posted:</b> {$post['_date']}</span>
		 </div>
	 </td>
 </tr>
 <tr>
	 <td valign=\"top\" class=\"post1\">
		 <span class=\"postdetails\">
			{$author['avatar']}<br /><br />
			{$author['title']}<br />
			{$author['member_rank_img']}<br /><br />
			{$author['member_group']}<br />
			{$author['member_posts']}<br />
			{$author['member_joined']}<br />
			{$author['member_location']}
			{$author['member_number']}<br />
" . (($author['custom_fields'] != "") ? ("
{$author['custom_fields']}
") : ("")) . "

<br />
        		{$author['warn_text']} {$author['warn_minus']}{$author['warn_img']}{$author['warn_add']}
        	</span><br />
        	<img src=\"{$this->ipsclass->vars['img_url']}/spacer.gif\" alt=\"\" width=\"160\" height=\"1\" /><br /> 
       </td>
	 <td width=\"100%\" valign=\"top\" class=\"post1\">
		 <div class=\"postcolor\">
		  {$post['bug_entry_content']} 
		  <!--IBF.ATTACHMENT_{$post['bug_entry_id']}-->
		 </div>
		 {$post['signature']}
	 </td>
 </tr>
 <tr>
	 <td class=\"formbuttonrow\" nowrap=\"nowrap\">
			<div style='text-align:left'>{$author['online_status_indicator']}{$author['addresscard']}{$author['message_icon']}</div>
	 </td>
	 <td class=\"formbuttonrow\" nowrap=\"nowrap\">
		 <!-- PM / EMAIL / WWW / MSGR -->
		 <div style=\"float: left;\">
			 <a href=\"javascript:scroll(0,0);\"><{P_UP}></a>
		 </div>
		 <!-- REPORT / UP -->
		 <div align=\"right\">
			 {$buttons['delete']}{$buttons['edit']}
		 </div>
	  </td>
 </tr>
 <tr>
	<td class=\"catend\" colspan=\"2\">
	<!-- no content -->
	</td>
</tr>
</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_bug_wrapper:desc::trigger:>
//===========================================================================
function show_bug_wrapper($topic="",$content="",$pages="",$status_dd="",$can_manage="",$bug_cat_id="",$projects_dd="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\">
<!--
var ipb_lang_js_del_1  = \"Confirm deletion\";
var ipb_lang_js_del_2  = \"OK - no action taken\";
-->
</script>
<script type=\"text/javascript\" src=\"jscripts/ipb_topic.js\"></script>
<table class='ipbtable' cellspacing=\"0\">
<tr>
	<td style='padding-left:0px' width=\"40%\" valign=\"middle\" nowrap=\"nowrap\"><div>{$pages}</div></td>
	<td class='nopad' style='padding:0px 0px 5px 0px' align=\"right\" width=\"60%\" valign=\"middle\">
	  <a href=\"{$this->ipsclass->base_url}autocom=bugtracker&amp;code=post_reply_bug&amp;product_id={$topic['bug_title_product_id']}&amp;bug_title_id={$topic['bug_title_id']}&amp;bug_cat_id=$bug_cat_id\"><{A_REPLY}></a>
	  <a href=\"{$this->ipsclass->base_url}autocom=bugtracker&amp;code=post_new_bug&amp;product_id={$topic['bug_title_product_id']}&amp;bug_cat_id=$bug_cat_id\"><{A_POST}></a>
	</td>
</tr>
</table>
<div class='borderwrap'>
 <div class='maintitle'>Bug ID #{$topic['bug_title_id']}: {$topic['bug_title_title']}</div>
 $content
</div>
" . (($can_manage == 1) ? ("
<br />
<div class='borderwrap'>
<table class='darkrow1' style='padding:5px;width:100%' cellspacing=\"0\" cellpadding='0'>
<tr>
 <td align='left' nowrap='nowrap'>
 [ <a href=\"javascript:delete_post('{$this->ipsclass->base_url}autocom=bugtracker&amp;code=bug_topic_delete&amp;bug_title_id={$topic['bug_title_id']}&amp;product_id={$topic['bug_title_product_id']}')\">Delete Bug Report</a> ]
 </td>
 <td align='right'>
  <form action='{$this->ipsclass->base_url}autocom=bugtracker&amp;code=mod_move_status&amp;product_id={$topic['bug_title_product_id']}&amp;bug_title_id={$topic['bug_title_id']}&amp;bug_cat_id=$bug_cat_id' method='POST'>
	Move: {$projects_dd} {$status_dd} <input type='submit' value='Go' />
  </form>
 </td>
</tr>
</table>
</div>
") : ("")) . "

<br />
<table class='ipbtable' cellspacing=\"0\">
<tr>
	<td style='padding-left:0px' width=\"40%\" valign=\"middle\" nowrap=\"nowrap\"><div>{$pages}</div></td>
	<td class='nopad' style='padding:0px 0px 5px 0px' align=\"right\" width=\"60%\" valign=\"middle\">
	  <a href=\"{$this->ipsclass->base_url}autocom=bugtracker&amp;code=post_reply_bug&amp;product_id={$topic['bug_title_product_id']}&amp;bug_title_id={$topic['bug_title_id']}&amp;bug_cat_id=$bug_cat_id\"><{A_REPLY}></a>
	  <a href=\"{$this->ipsclass->base_url}autocom=bugtracker&amp;code=post_new_bug&amp;product_id={$topic['bug_title_product_id']}&amp;bug_cat_id=$bug_cat_id\"><{A_POST}></a>
	</td>
</tr>
</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_project_row:desc::trigger:>
//===========================================================================
function show_project_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
 <td class='row1' align='center'><{B_NORM}></td>
 <td class='row1'>
 	<a href='{$this->ipsclass->base_url}autocom=bugtracker&amp;code=show_bug&amp;bug_title_id={$data['bug_title_id']}&amp;bug_cat_id={$data['_bug_cat_id']}'>{$data['bug_title_title']}</a>
    <div class='desc'>Status: {$data['_bug_cat_name']}</div>	
 </td>
 <td class='row2' align='center'>{$data['_starter_link']}</td>
 <td class='row2' align='center'>{$data['bug_title_replies']}</td>
 <td class='row2' align='left'>{$data['_last_post']}<div class='desc'>By {$data['_last_link']}</div></td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_project_row_none:desc::trigger:>
//===========================================================================
function show_project_row_none() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
 <td class='row1' align='center' colspan='5'><strong>There are no bug reports to display</strong></td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:show_project_wrapper:desc::trigger:>
//===========================================================================
function show_project_wrapper($product="",$content="",$status_dd="",$pages="",$bug_cat_id="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class='ipbtable' cellspacing=\"0\">
	<tr>
		<td style='padding-left:0px' width=\"50%\" nowrap=\"nowrap\">{$pages}</td>
		<td class='nopad' style='padding:5px 0px 5px 0px' align=\"right\" width=\"50%\"><a href=\"{$this->ipsclass->base_url}autocom=bugtracker&amp;code=post_new_bug&amp;product_id={$product['product_id']}&amp;bug_cat_id=$bug_cat_id\"><{A_POST}></a></td>
	</tr>
</table>
<div class='borderwrap'>
 <div class='maintitle'>
  <table class='ipbtable' style='padding:0px' cellspacing=\"0\" cellpadding='0'>
	 <tr>
		 <td style='padding:0px' width=\"50%\" nowrap=\"nowrap\">Bug Tracker: {$product['product_title']}</td>
		 <td style='padding:0px' width='50%' align=\"right\">
		  <form action='{$this->ipsclass->base_url}autocom=bugtracker&amp;code=search_project&amp;product_id={$product['product_id']}' method='POST'>
		    <input type='text' size='20' name='keywords' value='Enter keywords....' onclick='this.value=\"\"' class='input'><input type='submit' value='Search Bugs' class='input' />
		  </form>
		 </td>
	 </tr>
  </table>
 </div>
 <table cellpadding='0' cellspacing='1' class='ipbtable'>
 <tr>
  <th width='1%'>&nbsp;</th>
  <th width='40%'>Title</th>
  <th width='14%' align='center'>Started</th>
  <th width='5%' align='center'>Replies</th>
  <th width='20%' align='left'>Last Post</th>
 </tr>
 $content
 <tr>
  <td class='darkrow1' style='padding:0px' colspan='5'>
   <table class='ipbtable' cellspacing=\"0\" cellpadding='0'>
   <tr>
    <td align='right'>
     <form action='{$this->ipsclass->base_url}autocom=bugtracker&amp;code=show_project&amp;product_id={$product['product_id']}' method='POST'>
       View: {$status_dd} <input type='submit' value='Go' />
     </form>
    </td>
   </tr>
  </table>
  </td>
 </tr>
 </table>
</div>
<table class='ipbtable' cellspacing=\"0\">
	<tr>
		<td style='padding-left:0px' width=\"50%\" nowrap=\"nowrap\">{$pages}</td>
		<td class='nopad' style='padding:5px 0px 5px 0px' align=\"right\" width=\"50%\"><a href=\"{$this->ipsclass->base_url}autocom=bugtracker&amp;code=post_new_bug&amp;product_id={$product['product_id']}\"><{A_POST}></a></td>
	</tr>
</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:status_dropdown_row:desc::trigger:>
//===========================================================================
function status_dropdown_row($name="",$value="",$selected='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<option value='$value'{$selected}>$name</option>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:status_dropdown_row_counted:desc::trigger:>
//===========================================================================
function status_dropdown_row_counted($name="",$value="",$count="",$selected='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<option value='$value'{$selected}>$name ($count Reports)</option>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:status_dropdown_wrapper:desc::trigger:>
//===========================================================================
function status_dropdown_wrapper($name="",$content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<select name='$name'>$content</select>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:status_dropdown_wrapper_counted:desc::trigger:>
//===========================================================================
function status_dropdown_wrapper_counted($name="",$content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<select name='$name'>$content</select>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>

</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>