<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_gallery_global_3 {

 var $ipsclass;
//===========================================================================
// <ips:generic_table_header:desc::trigger:>
//===========================================================================
function generic_table_header($data='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	" . (($data['open_div']==1) ? ("
	<div class='row2'>
	") : ("")) . "
	<div class=\"maintitle\">{$data['title']}</div>
	<table class=\"ipbtable\" cellspacing='0'>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
generic_table_header
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>