<?php
/*--------------------------------------------------*/
/* FILE GENERATED BY INVISION POWER BOARD           */
/* CACHE FILE: Skin set id: 3                     */
/* CACHE FILE: Generated: Wed, 12 Nov 2008 04:54:08 GMT */
/* DO NOT EDIT DIRECTLY - THE CHANGES WILL NOT BE   */
/* WRITTEN TO THE DATABASE AUTOMATICALLY            */
/*--------------------------------------------------*/

class skin_mod_3 {

 var $ipsclass;
//===========================================================================
// <ips:delete_js:desc::trigger:>
//===========================================================================
function delete_js() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script language=\"JavaScript\" type=\"text/javascript\">
	<!--
	function ValidateForm() {
		document.REPLIER.submit.disabled = true;
		return true;
	}
	-->
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:edit_user_form:desc::trigger:>
//===========================================================================
function edit_user_form($profile="",$custom_fields="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['cp_em_title']}: {$profile['members_display_name']}</div>
		<table class='ipbtable' cellspacing=\"0\">
			<tr>
				<td valign=\"top\" width=\"50%\" class='row2'>
					<fieldset>
					<legend><b>{$this->ipsclass->lang['cp_em_sub_main']}</b></legend>
						<table class='ipbtable' cellspacing=\"0\">
							<tr>
								<td width=\"40%\" class=\"row1\">{$this->ipsclass->lang['cp_remove_av']}</td>
								<td width=\"60%\" class=\"row1\">
									<select name=\"avatar\">
										<option value=\"0\">{$this->ipsclass->lang['no']}</option>
										<option value=\"1\">{$this->ipsclass->lang['yes']}</option>
									</select>
								</td>
							</tr>
							<tr>
								<td class=\"row1\">{$this->ipsclass->lang['cp_remove_photo']}</td>
								<td class=\"row1\">
									<select name=\"photo\">
										<option value=\"0\">{$this->ipsclass->lang['no']}</option>
										<option value=\"1\">{$this->ipsclass->lang['yes']}</option>
									</select>
								</td>
							</tr>
							<tr>
								<td class=\"row1\">{$this->ipsclass->lang['cp_edit_website']}</td>
								<td class=\"row1\"><input type=\"text\" size=\"35\" name=\"website\" value=\"{$profile['website']}\" /></td>
							</tr>
							<tr>
								<td class=\"row1\">{$this->ipsclass->lang['cp_edit_location']}</td>
								<td class=\"row1\"><input type=\"text\" size=\"35\" name=\"location\" value=\"{$profile['location']}\" /></td>
							</tr>
							<tr>
								<td class=\"row1\" valign=\"top\">{$this->ipsclass->lang['cp_edit_interests']}</td>
								<td class=\"row1\"><textarea cols=\"35\" rows=\"3\" name=\"interests\">{$profile['interests']}</textarea></td>
							</tr>
							<tr>
								<td class=\"row1\" valign=\"top\">{$this->ipsclass->lang['cp_edit_signature']}</td>
								<td class=\"row1\"><textarea cols=\"35\" rows=\"5\" name=\"signature\">{$profile['signature']}</textarea></td>
							</tr>
						</table>
					</fieldset>
				</td>
				<td valign=\"top\" width=\"50%\" class='row2'>
					<fieldset>
					<legend><b>{$this->ipsclass->lang['cp_em_sub_other']}</b></legend>
						<table class='ipbtable' cellspacing=\"0\">
							<tr>
								<td class=\"row1\" width=\"40%\">{$this->ipsclass->lang['cp_em_yahoo']}</td>
								<td class=\"row1\" width=\"60%\"><input type=\"text\" size=\"35\" name=\"yahoo\" value=\"{$profile['yahoo']}\" /></td>
							</tr>
							<tr>
								<td class=\"row1\">{$this->ipsclass->lang['cp_em_aim']}</td>
								<td class=\"row1\"><input type=\"text\" size=\"35\" name=\"aim_name\" value=\"{$profile['aim_name']}\" /></td>
							</tr>
							<tr>
								<td class=\"row1\">{$this->ipsclass->lang['cp_em_icq']}</td>
								<td class=\"row1\"><input type=\"text\" size=\"35\" name=\"icq_number\" value=\"{$profile['icq_number']}\" /></td>
							</tr>
							<tr>
								<td class=\"row1\">{$this->ipsclass->lang['cp_em_msn']}</td>
								<td class=\"row1\"><input type=\"text\" size=\"35\" name=\"msnname\" value=\"{$profile['msnname']}\" /></td>
							</tr>
" . (($custom_fields != "") ? ("
$custom_fields
") : ("")) . "
						</table>
					</fieldset>
				</td>
			</tr>
		</table>
		<div class=\"formsubtitle\" align=\"center\"><input type=\"submit\" class='button' value=\"{$this->ipsclass->lang['cp_em_submit']}\" /></div>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:end_form:desc::trigger:>
//===========================================================================
function end_form($action="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\" align=\"center\"><input type=\"submit\" class='button' name=\"submit\" value=\"$action\" /></div>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:field_dropdown:desc::trigger:>
//===========================================================================
function field_dropdown($name="",$options="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<select name=\"$name\">$options</select>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:field_entry:desc::trigger:>
//===========================================================================
function field_entry($title="",$desc="",$content="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td class=\"row1\" valign=\"top\"><b>$title</b><br />$desc</td>
		<td class=\"row1\">$content</td>
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:field_textarea:desc::trigger:>
//===========================================================================
function field_textarea($name="",$value="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<textarea cols=\"60\" rows=\"5\" wrap=\"soft\" name=\"$name\">$value</textarea>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:field_textinput:desc::trigger:>
//===========================================================================
function field_textinput($name="",$value="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<input type=\"text\" size=\"35\" name=\"$name\" value=\"$value\" />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:forum_jump:desc::trigger:>
//===========================================================================
function forum_jump($data="",$menu_extra="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
	<div align=\"right\">{$data}</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:merge_body:desc::trigger:>
//===========================================================================
function merge_body($title="",$desc="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class='ipbtable' cellspacing=\"1\">
		<tr>
			<td class=\"pformleftw\">{$this->ipsclass->lang['mt_new_title']}</td>
			<td class=\"pformright\"><input type=\"text\" size=\"40\" maxlength=\"250\" name=\"title\" value=\"$title\" /></td>
		</tr>
		<tr>
			<td class=\"pformleftw\">{$this->ipsclass->lang['mt_new_desc']}</td>
			<td class=\"pformright\"><input type=\"text\" size=\"40\" maxlength=\"250\" name=\"desc\" value=\"$desc\" /></td>
		</tr>
		<tr>
			<td class=\"pformleftw\">{$this->ipsclass->lang['mt_tid']}</td>
			<td class=\"pformright\"><input type=\"text\" size=\"40\" name=\"topic_url\" value=\"\" /></td>
		</tr>
	</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:merge_post_form:desc::trigger:>
//===========================================================================
function merge_post_form($post="",$pid="",$author="",$auth_key="",$upload="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form action=\"{$this->ipsclass->base_url}act=mod&amp;CODE=postchoice&amp;tact=merge&amp;checked=1\" method=\"post\">
	<input type=\"hidden\" name=\"act\" value=\"mod\" />
	<input type=\"hidden\" name=\"selectedpids\" value=\"{$this->ipsclass->input['selectedpids']}\" />
	<input type=\"hidden\" name=\"auth_key\" value=\"{$auth_key}\" />
	<input type=\"hidden\" name=\"t\" value=\"{$this->ipsclass->input['t']}\" />
	<input type=\"hidden\" name=\"f\" value=\"{$this->ipsclass->input['f']}\" />
	<input type=\"hidden\" name=\"st\" value=\"{$this->ipsclass->input['st']}\" />
	
		<div class=\"borderwrap\">
		<div class=\"maintitle\">{$this->ipsclass->lang['cm_title']}</div>
			<table class='ipbtable' cellspacing=\"1\">
				<tr>
					<td width=\"35%\" class=\"row2\"><b>{$this->ipsclass->lang['cm_post']}</b></td>
					<td width=\"65%\" class=\"row2\"><select name=\"postdate\" class=\"dropdown\">{$pid}</select></td>
				</tr>
				<tr>
					<td class=\"row2\"><b>{$this->ipsclass->lang['cm_author']}</b></td>
					<td class=\"row2\"><select name=\"postauthor\" class=\"dropdown\">{$author}</select></td>
				</tr>
				<tr>
					<td class=\"row2\" valign=\"top\"><b>{$this->ipsclass->lang['cm_text']}</b></td>
					<td class=\"row2\"><textarea cols=\"70\" rows=\"20\" name=\"Post\" class=\"textarea\">$post</textarea></td>
				</tr>
" . (($upload != "") ? ("
<tr>
					<td class=\"row2\" valign=\"top\"><b>{$this->ipsclass->lang['cm_attach']}</b><div class=\"desc\">{$this->ipsclass->lang['cm_attach2']}</div></td>
					<td class=\"row2\">
						<table class='ipbtable' cellspacing=\"1\">
							$upload
						</table>
					</td>
				</tr>
") : ("")) . "
			</table>
			<div class=\"formsubtitle\" align=\"center\"><input type=\"submit\" class='button' value=\"{$this->ipsclass->lang['cm_submit']}\" /></div>
		</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_exp:desc::trigger:>
//===========================================================================
function mod_exp($words="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\">$words</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_log_end:desc::trigger:>
//===========================================================================
function mod_log_end() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table>
</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_log_none:desc::trigger:>
//===========================================================================
function mod_log_none() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class=\"pformright\" colspan=\"3\" align=\"center\"><i>{$this->ipsclass->lang['ml_none']}</i></td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_log_row:desc::trigger:>
//===========================================================================
function mod_log_row($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class=\"pformright\">{$data['member']}</td>
	<td class=\"pformright\">{$data['action']}</td>
	<td class=\"pformright\">{$data['date']}</td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_log_start:desc::trigger:>
//===========================================================================
function mod_log_start() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
	<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['ml_title']}</div>
		<table class='ipbtable' cellspacing=\"1\">
			<tr>
				<td class=\"formsubtitle\" width=\"30%\"><b>{$this->ipsclass->lang['ml_name']}</b></td>
				<td class=\"formsubtitle\" width=\"50%\"><b>{$this->ipsclass->lang['ml_desc']}</b></td>
				<td class=\"formsubtitle\" width=\"20%\"><b>{$this->ipsclass->lang['ml_date']}</b></td>
			</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:mod_simple_page:desc::trigger:>
//===========================================================================
function mod_simple_page($title="",$msg="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">$title</div>
		<div class=\"tablepad\">
			$msg
			<br /><br />
			<div align=\"center\"><a href=\"#\" onclick=\"window.close();\">{$this->ipsclass->lang['cpp_close']}</a></div>
		</div>
	</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:move_checked_form_end:desc::trigger:>
//===========================================================================
function move_checked_form_end($jump_html="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table>
			<div align=\"center\" class=\"tablepad\"><b>{$this->ipsclass->lang['cp_tmove_to']}</b>&nbsp;&nbsp;<select name=\"df\">$jump_html</select></div>
			<div align=\"center\" class=\"formsubtitle\"><input type=\"submit\" class='button' value=\"{$this->ipsclass->lang['cp_tmove_end']}\" /></div>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:move_checked_form_entry:desc::trigger:>
//===========================================================================
function move_checked_form_entry($tid="",$title="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
	<td class=\"row1\" width=\"40%\" align=\"right\"><input class='checkbox' type=\"checkbox\" name=\"TID_$tid\" value=\"1\" checked=\"checked\" /></td>
	<td class=\"row1\" width=\"60%\"><b>$title</b></td>
</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:move_checked_form_start:desc::trigger:>
//===========================================================================
function move_checked_form_start($forum_name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['cp_tmove_start']} $forum_name</div>
		<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td class=\"formsubtitle\" colspan='2' align='center'><b>{$this->ipsclass->lang['leave_link']}</b>&nbsp; <select name=\"leave\"><option value=\"y\" selected=\"selected\">{$this->ipsclass->lang['yes']}</option><option value=\"n\">{$this->ipsclass->lang['no']}</option></select></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:move_form:desc::trigger:>
//===========================================================================
function move_form($jhtml="",$forum_name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class='ipbtable' cellspacing=\"1\">
		<tr>
			<td class=\"pformleftw\"><b>{$this->ipsclass->lang[move_from]} <b>$forum_name</b> {$this->ipsclass->lang[to]}</b></td>
			<td class=\"pformright\"><select name=\"move_id\">$jhtml</select></td>
		</tr>
		<tr>
			<td class=\"pformleftw\"><b>{$this->ipsclass->lang['leave_link']}</b></td>
			<td class=\"pformright\"><select name=\"leave\"><option value=\"y\" selected=\"selected\">{$this->ipsclass->lang['yes']}</option><option value=\"n\">{$this->ipsclass->lang['no']}</option></select></td>
		</tr>
	</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:move_post_body:desc::trigger:>
//===========================================================================
function move_post_body() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class='ipbtable' cellspacing=\"1\">
		<tr>
			<td class=\"row2\" width=\"40%\"><b>{$this->ipsclass->lang['cmp_topic']}</b><div class=\"desc\">{$this->ipsclass->lang['cmp_topic2']}</div></td>
			<td class=\"row2\" width=\"60%\"><input type=\"text\" size=\"50\" name=\"topic_url\" value=\"\" /></td>
		</tr>
	</table>
</div>
<br />
<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['st_post']}</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:prune_splash:desc::trigger:>
//===========================================================================
function prune_splash($forum="",$forums_html="",$select="",$auth_key="",$confirm_data="",$complete_html="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<script type=\"text/javascript\" src='jscripts/ipb_xhr_findnames.js'></script>
<div id='ipb-get-members' style='border:1px solid #000; background:#FFF; padding:2px;position:absolute;width:210px;display:none;z-index:1'></div>
<div class=\"borderwrap\" style='text-align:left'>
" . (($confirm_data['show'] == 1) ? ("
<div class=\"maintitle\">
	 <div>{$this->ipsclass->lang['mpt_confirm']}</div>
 </div>
 <div class=\"formsubtitle\">{$this->ipsclass->lang['cp_check_result']}</div>
	 <table class='ipbtable' cellspacing=\"0\">
		 <tr>
			 <td class=\"pformleftw\"><b>{$this->ipsclass->lang['cp_total_topics']}</b></td>
			 <td class=\"pformright\">{$confirm_data['tcount']}</td>
		 </tr>
		 <tr>
			 <td class=\"pformleftw\"><span>{$this->ipsclass->lang['cp_total_match']}</span></td>
			 <td class=\"pformright\"><span>{$confirm_data['count']}</span></td>
		 </tr>
	 </table>
	 
	 <form action=\"{$this->ipsclass->base_url}{$confirm_data['link']}\" method=\"post\">
		 <input type=\"hidden\" name=\"auth_key\" value=\"$auth_key\" />
		 <div class=\"formsubtitle\" align=\"center\"><input type=\"submit\" class='button' value=\"{$confirm_data['link_text']}\" /></div>
	 </form>
 </div>
") : ("")) . "
" . (($complete_html != '') ? ("
{$complete_html}
") : ("")) . "
<div class=\"maintitle\">{$this->ipsclass->lang['cp_prune']} {$forum['name']}</div>
<div class=\"formsubtitle\">{$this->ipsclass->lang['mpt_help']}</div>
<div class=\"tablepad\">{$this->ipsclass->lang['cp_prune_text']}</div>
<form name=\"ibform\" id='postingform' action=\"{$this->ipsclass->base_url}\" method=\"POST\">
	<input type=\"hidden\" name=\"s\" value=\"{$this->ipsclass->session_id}\" />
	<input type=\"hidden\" name=\"act\" value=\"mod\" />
	<input type=\"hidden\" name=\"CODE\" value=\"prune_start\" />
	<input type=\"hidden\" name=\"f\" value=\"{$forum['id']}\" />
	<input type=\"hidden\" name=\"auth_key\" value=\"$auth_key\" />
	<input type=\"hidden\" name=\"check\" value=\"1\" />
	
		<div class=\"formsubtitle\">{$this->ipsclass->lang['mpt_title']}</div>
		<div class=\"tablepad\">
		<fieldset>
		 <legend><strong>{$this->ipsclass->lang['cp_action']}</strong></legend>
		 <table class='ipbtable' cellspacing=\"0\" cellpadding='4'>
		 <tr>
		  <td>{$this->ipsclass->lang['cp_prune_action2']}</td>
		  <td><select name=\"df\">$forums_html</select></td>
		 </tr>
		 <tr>
		  <td width='35%'>{$this->ipsclass->lang['cp_per_go']}</td>
		  <td width='65%'><input type=\"text\" size=\"5\" name=\"pergo\" value=\"{$this->ipsclass->input['pergo']}\" /></td>
		 </tr>
		 </table>
		  
		</fieldset>
		
		<br />
		<fieldset>
		 <legend><strong>{$this->ipsclass->lang['cp_prune_days']}</strong></legend>
		 <table class='ipbtable' cellspacing=\"0\" cellpadding='4'>
		 <tr>
		  <td>{$this->ipsclass->lang['cp_prune_member']}</td>
		  <td><input type=\"text\" size=\"30\" name=\"member\" id='entered_name' autocomplete='off' style='width:210px' value=\"{$this->ipsclass->input['member']}\" /></td>
		 </tr>
		 <tr>
		  <td width='35%'>{$this->ipsclass->lang['cp_prune_days2']}</td>
		  <td width='65%'><input type=\"text\" size=\"5\" name=\"dateline\" value=\"{$this->ipsclass->input['dateline']}\" /></td>
		 </tr>
		 <tr>
		   <td>{$this->ipsclass->lang['cp_prune_replies']}</td>
		   <td><input type=\"text\" size=\"5\" name=\"posts\" value=\"{$this->ipsclass->input['posts']}\" /></td>
		 </tr>
		 <tr>
		  <td>{$this->ipsclass->lang['cp_prune_type']}</td>
		  <td>$select</td>
		 </tr>
		 <tr>
		  <td>{$this->ipsclass->lang['mps_ignorepin']}</td>
		  <td><input type=\"checkbox\" id=\"cbox\" name=\"ignore_pin\" value=\"1\" checked=\"checked\" class=\"checkbox\" /></td>
		 </tr>
		 </table>
		 <div class='desc' align='center'>{$this->ipsclass->lang['cp_optional']}</div>
		</fieldset>
		</div>
		<div class=\"formsubtitle\" align=\"center\"><input type=\"submit\" value=\"{$this->ipsclass->lang['cp_prune_sub1']}\" class=\"button\" /></div>
	</div>
</form>
<script type=\"text/javascript\">
	// INIT find names
	init_js( 'postingform', 'entered_name');
	// Run main loop
	setTimeout( 'main_loop()', 10 );
</script>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:split_body:desc::trigger:>
//===========================================================================
function split_body($jump="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"row2\">{$this->ipsclass->lang['st_explain']}</div>
		<table class='ipbtable' cellspacing=\"1\">
			<tr>
				<td class=\"row1\"><b>{$this->ipsclass->lang['mt_new_title']}</b></td>
				<td class=\"row2\"><input type=\"text\" size=\"40\"  maxlength=\"100\" name=\"title\" value=\"\" /></td>
			</tr>
			<tr>
				<td class=\"row1\"><b>{$this->ipsclass->lang['mt_new_desc']}</b></td>
				<td class=\"row2\"><input type=\"text\" size=\"40\"  maxlength=\"100\" name=\"desc\" value=\"\" /></td>
			</tr>
			<tr>
				<td class=\"row1\"><b>{$this->ipsclass->lang['st_forum']}</b></td>
				<td class=\"row2\"><select name=\"fid\">$jump</select></td>
			</tr>
		</table>
	</div>
<br />
	<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['st_post']}</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:split_end_form:desc::trigger:>
//===========================================================================
function split_end_form($action="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\" align=\"center\">
			<input type=\"submit\" name=\"submit\" class='button' value=\"$action\" />
		</div>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:split_row:desc::trigger:>
//===========================================================================
function split_row($row="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"formsubtitle\">{$row['st_top_bit']}</div>
	<div class=\"tablepad\">
		{$row['post']}
		<div align=\"right\"><b>{$this->ipsclass->lang['st_split']}</b>&nbsp;&nbsp;<input class='checkbox' type=\"checkbox\" name=\"post_{$row['pid']}\" value=\"1\" checked=\"checked\" /></div>
	</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:table_top:desc::trigger:>
//===========================================================================
function table_top($posting_title="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">$posting_title</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topic_history:desc::trigger:>
//===========================================================================
function topic_history($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
		<div class=\"maintitle\">{$this->ipsclass->lang['th_title']}</div>
		<table class='ipbtable' cellspacing=\"1\">
			<tr>
				<td class=\"pformleftw\"><b>{$this->ipsclass->lang['th_topic']}</b></td>
				<td class=\"pformright\">{$data['th_topic']}</td>
			</tr>
			<tr>
				<td class=\"pformleftw\"><b>{$this->ipsclass->lang['th_desc']}</b></td>
				<td class=\"pformright\">{$data['th_desc']}&nbsp;</td>
			</tr>
			<tr>
				<td class=\"pformleftw\"><b>{$this->ipsclass->lang['th_start_date']}</b></td>
				<td class=\"pformright\">{$data['th_start_date']}</td>
			</tr>
			<tr>
				<td class=\"pformleftw\"><b>{$this->ipsclass->lang['th_start_name']}</b></td>
				<td class=\"pformright\">{$data['th_start_name']}</td>
			</tr>
			<tr>
				<td class=\"pformleftw\"><b>{$this->ipsclass->lang['th_last_date']}</b></td>
				<td class=\"pformright\">{$data['th_last_date']}</td>
			</tr>
			<tr>
				<td class=\"pformleftw\"><b>{$this->ipsclass->lang['th_last_name']}</b></td>
				<td class=\"pformright\">{$data['th_last_name']}</td>
			</tr>
			<tr>
				<td class=\"pformleftw\"><b>{$this->ipsclass->lang['th_avg_post']}</b></td>
				<td class=\"pformright\">{$data['th_avg_post']}</td>
			</tr>
		</table>
	</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:topictitle_fields:desc::trigger:>
//===========================================================================
function topictitle_fields($title="",$desc="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<table class='ipbtable' cellspacing=\"1\">
		<tr>
			<td class=\"pformleftw\"><b>{$this->ipsclass->lang['edit_f_title']}</b></td>
			<td class=\"pformright\"><input type=\"text\" size=\"40\" maxlength=\"{$this->ipsclass->vars['topic_title_max_len']}\" name=\"TopicTitle\" value=\"$title\" /></td>
		</tr>
		<tr>
			<td class=\"pformleftw\"><b>{$this->ipsclass->lang['edit_f_desc']}</b></td>
			<td class=\"pformright\"><input type=\"text\" size=\"40\" maxlength=\"70\" name=\"TopicDesc\" value=\"$desc\" /></td>
		</tr>
	</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:uploadbox_entry:desc::trigger:>
//===========================================================================
function uploadbox_entry($attach="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td width=\"1%\" align=\"center\"><select name=\"attach_{$attach['attach_id']}\" class=\"dropdown\"><option value=\"keep\">{$this->ipsclass->lang['cm_keep']}</option><option value=\"delete\">{$this->ipsclass->lang['cm_delete']}</option></select></td>
			<td width=\"1%\"><img src=\"{$this->ipsclass->vars['mime_img']}/{$attach['image']}\" alt=\"\" /></td>
			<td width=\"15%\" nowrap=\"nowrap\">{$attach['size']}</td>
			<td width=\"95%\"><a href=\"{$this->ipsclass->base_url}act=Attach&amp;type=post&amp;id={$attach['attach_id']}\" target=\"_blank\"><b>{$attach['attach_file']}</b></a> #{$attach['attach_pid']}</td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_add_note_form:desc::trigger:>
//===========================================================================
function warn_add_note_form($id="",$name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form method=\"post\" action=\"{$this->ipsclass->base_url}&amp;act=warn&amp;CODE=save_note&amp;mid=$id\" id='postingform'>
<div class=\"borderwrap\">
	<div class=\"maintitle\"><{CAT_IMG}>&nbsp;{$this->ipsclass->lang['mod_warn_new_note']} <a href=\"{$this->ipsclass->base_url}showuser=$id\">$name</a></div>
	<div class='row2' style='padding:4px'>
		<fieldset>
			<legend><strong>{$this->ipsclass->lang['mod_warn_fieldset']}</strong></legend>
			<textarea name='note' style='width:95%;height:300px'>{$_POST['note']}</textarea>
			<br />
			<div align='center'><input class='button' type='submit' value='{$this->ipsclass->lang['mod_warn_note_save']}' /></div>
		</fieldset>
	</div>
</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_errors:desc::trigger:>
//===========================================================================
function warn_errors($data="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"formsubtitle\">{$this->ipsclass->lang['errors_found']}</div>
	<div class=\"tablepad\"><span class=\"postcolor\">$data</span></div>
</div>
<br />";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_footer:desc::trigger:>
//===========================================================================
function warn_footer($no_pm="",$editor_html="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row1\" valign=\"top\"><b>{$this->ipsclass->lang['w_reason']}</b><br />{$this->ipsclass->lang['w_reason2']}</td>
			<td class=\"row2\"><textarea rows=\"6\" cols=\"70\" class=\"textinput\" name=\"reason\">{$this->ipsclass->input['reason']}</textarea></td>
		</tr>
		<tr>
			<td class=\"row1\"><b>{$this->ipsclass->lang['w_c_subj']}</b></td>
			<td class=\"row2\"><input type=\"text\" name=\"subject\" value=\"{$this->ipsclass->input['subject']}\" size=\"30\" /></td>
		</tr>
		<tr>
			<td class=\"row1\" valign=\"top\"><b>{$this->ipsclass->lang['w_contact']}</b><br />{$this->ipsclass->lang['w_contact2']}</td>
			<td class=\"row2\">
				&nbsp;{$this->ipsclass->lang['w_c']}&nbsp;
				<select name=\"contactmethod\">
" . (($no_pm != 1) ? ("
<option value=\"pm\">{$this->ipsclass->lang['w_c_p']}</option>
") : ("")) . "
					
					<option value=\"email\">{$this->ipsclass->lang['w_c_e']}</option>
				</select>
					<br />
				{$editor_html}
			</td>
		</tr>
	</table>
		<div align=\"center\" class=\"formsubtitle\"><input type=\"submit\" class='button' value=\"{$this->ipsclass->lang['w_submit']}\" /></div>
	</div>
</form>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_header:desc::trigger:>
//===========================================================================
function warn_header($mid="",$name="",$cur=0,$min=0,$max=10,$key="",$tid="",$st="",$type="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<form method=\"post\" action=\"{$this->ipsclass->base_url}&amp;act=warn&amp;CODE=dowarn&amp;mid=$mid&amp;t=$tid&amp;st=$st&amp;type={$this->ipsclass->input['type']}\" id='postingform' onsubmit='return ValidateForm()'>
	<input type=\"hidden\" name=\"key\" value=\"$key\" />
		<div class=\"borderwrap\">
		<div class=\"maintitle\">{$this->ipsclass->lang['w_warnfor']} <a href=\"{$this->ipsclass->base_url}showuser=$mid\">$name</a> ( $min &lt; $cur &gt; $max )</div>
			<div class=\"subtitle\">{$this->ipsclass->lang['w_complete']}</div>
				<table class='ipbtable' cellspacing=\"0\">
					<tr>
						<td class=\"row1\"><b>{$this->ipsclass->lang['w_adjust_level']}</b></td>
						<td class=\"row2\">
							<input type=\"radio\" name=\"level\" id=\"add\" class=\"radiobutton\" value=\"add\" {$type['add']} /><label for=\"add\" class=\"warnbad\"><b>{$this->ipsclass->lang['w_add']}</b></label>
								<br />
							<input type=\"radio\" name=\"level\" id=\"minus\" class=\"radiobutton\" value=\"remove\" {$type['minus']} /><label for=\"minus\" class=\"warngood\"><b>{$this->ipsclass->lang['w_remove']}</b></label>
						</td>
					</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_mod_posts:desc::trigger:>
//===========================================================================
function warn_mod_posts($mod_tick="",$mod_array="",$mod_extra="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
						<td class=\"row1\"><b>{$this->ipsclass->lang['w_modq']}</b></td>
						<td class=\"row2\">
							<input class='checkbox' type=\"checkbox\" name=\"mod_indef\" value=\"1\" $mod_tick /> {$this->ipsclass->lang['w_modq_i']}
								<br />
							&nbsp;<b>{$this->ipsclass->lang['w_orfor']}</b>
							<input type=\"text\" name=\"mod_value\" value=\"{$mod_array['timespan']}\" size=\"5\" />&nbsp;
							<select name=\"mod_unit\">
								<option value=\"d\" {$mod_array['days']}>{$this->ipsclass->lang['w_day']}</option>
								<option value=\"h\" {$mod_array['hours']}>{$this->ipsclass->lang['w_hour']}</option>
							</select>
							$mod_extra
					</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_rem_posts:desc::trigger:>
//===========================================================================
function warn_rem_posts($post_tick="",$post_array="",$post_extra="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
						<td class=\"row1\"><b>{$this->ipsclass->lang['w_resposts']}</b></td>
						<td class=\"row2\">
							<input class='checkbox' type=\"checkbox\" name=\"post_indef\" value=\"1\" $post_tick /> {$this->ipsclass->lang['w_resposts_i']}
								<br />
							&nbsp;<b>{$this->ipsclass->lang['w_orfor']}</b>
							<input type=\"text\" name=\"post_value\" value=\"{$post_array['timespan']}\" size=\"5\" />&nbsp;
							<select name=\"post_unit\">
								<option value=\"d\" {$post_array['days']}>{$this->ipsclass->lang['w_day']}</option>
								<option value=\"h\" {$post_array['hours']}>{$this->ipsclass->lang['w_hour']}</option>
							</select>
							$post_extra
					</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_restricition_in_place:desc::trigger:>
//===========================================================================
function warn_restricition_in_place() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<br />
		<b>{$this->ipsclass->lang['w_restricted']}</b>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_success:desc::trigger:>
//===========================================================================
function warn_success() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
	<div class=\"maintitle\">{$this->ipsclass->lang['w_done_t']}</div>
	<div class=\"subtitle\">&nbsp;</div>
		<div class=\"tablepad\">
			{$this->ipsclass->lang['w_done_te']}
			<ul>
				<li><a href=\"{$this->ipsclass->base_url}\">{$this->ipsclass->lang['w_done_home']}</a></li>
				<!--IBF.FORUM_TOPIC-->
			</ul>
		</div>
	</div>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_success_forum:desc::trigger:>
//===========================================================================
function warn_success_forum($fid="",$fname="",$tid="",$tname="",$st=0) {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<li><a href=\"{$this->ipsclass->base_url}showforum=$fid\">{$this->ipsclass->lang['w_done_forum']} <b>$fname</b></a></li>
				<li><a href=\"{$this->ipsclass->base_url}showtopic=$tid&amp;st=$st\">{$this->ipsclass->lang['w_done_topic']} <b>$tname</b></a></li>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_suspend:desc::trigger:>
//===========================================================================
function warn_suspend($susp_array="",$susp_extra="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
		<td class=\"row1\"><b>{$this->ipsclass->lang['w_suspend']}</b></td>
		<td class=\"row2\">
			&nbsp;{$this->ipsclass->lang['w_susfor']}  <input type=\"text\" name=\"susp_value\" value=\"{$susp_array['timespan']}\" size=\"5\" />&nbsp;
			<select name=\"susp_unit\">
				<option value=\"d\" {$susp_array['days']}>{$this->ipsclass->lang['w_day']}</option>
				<option value=\"h\" {$susp_array['hours']}>{$this->ipsclass->lang['w_hour']}</option>
			</select>
			$susp_extra
	</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_view_footer:desc::trigger:>
//===========================================================================
function warn_view_footer($links="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "</table>
	</div>
<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<td align=\"right\">$links</td>
		</tr>
	</table>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_view_header:desc::trigger:>
//===========================================================================
function warn_view_header($id="",$name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<div class=\"borderwrap\">
		<div class=\"maintitle\">{$this->ipsclass->lang['w_v_title']}: <a href=\"{$this->ipsclass->base_url}showuser=$id\">$name</a></div>
	<table class='ipbtable' cellspacing=\"0\">
		<tr>
			<th class=\"subtitle\" width=\"30%\">{$this->ipsclass->lang['w_v_warnby']}</th>
			<th class=\"subtitle\" width=\"70%\">{$this->ipsclass->lang['w_v_notes']}</th>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_view_negative_row:desc::trigger:>
//===========================================================================
function warn_view_negative_row($date="",$content="",$puni_name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row2\" valign=\"top\"><b>$puni_name</b></td>
			<td class=\"row2\" valign=\"top\">{$this->ipsclass->lang['w_v_warned_on']} <b>$date</b></td>
		</tr>
		<tr>
			<td class=\"row1\" valign=\"middle\"><span class=\"warnbad\">{$this->ipsclass->lang['w_v_add']}</span></td>
			<td class=\"row1\" valign=\"top\"><span class=\"postcolor\">$content</span></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_view_none:desc::trigger:>
//===========================================================================
function warn_view_none() {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row1\" colspan=\"2\" align=\"center\"><b>{$this->ipsclass->lang['w_v_none']}</b></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_view_note_row:desc::trigger:>
//===========================================================================
function warn_view_note_row($date="",$content="",$puni_name='') {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row2\" valign=\"top\"><b>$puni_name</b></td>
			<td class=\"row2\" valign=\"top\">{$this->ipsclass->lang['mod_warn_added']} <b>$date</b></td>
		</tr>
		<tr>
			<td class=\"row1\" valign=\"middle\"><span class=\"warngood\" style='color:gray'>{$this->ipsclass->lang['mod_warn_note']}</span></td>
			<td class=\"row1\" valign=\"top\"><span class=\"postcolor\">$content</span></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}

//===========================================================================
// <ips:warn_view_positive_row:desc::trigger:>
//===========================================================================
function warn_view_positive_row($date="",$content="",$puni_name="") {
$IPBHTML = "";
//--starthtml--//
$IPBHTML .= "<tr>
			<td class=\"row2\" valign=\"top\"><b>$puni_name</b></td>
			<td class=\"row2\" valign=\"top\">{$this->ipsclass->lang['w_v_warned_on']} <b>$date</b></td>
		</tr>
		<tr>
			<td class=\"row1\" valign=\"middle\"><span class=\"warngood\">{$this->ipsclass->lang['w_v_minus']}</span></td>
			<td class=\"row1\" valign=\"top\"><span class=\"postcolor\">$content</span></td>
		</tr>";
//--endhtml--//
return $IPBHTML;
}



}

/*--------------------------------------------------*/
/*<changed bits>
warn_footer,warn_header,warn_mod_posts,warn_rem_posts,warn_success,warn_suspend,warn_view_header
</changed bits>*/
/* END OF FILE                                      */
/*--------------------------------------------------*/

?>