# This file is part of PyFarm.
# Copyright (C) 2008-2013 Oliver Palmer
#
# PyFarm is free software: you can redistribute it and/or modify
# it under the terms of the GNU Lesser General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# PyFarm is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Lesser General Public License for more details.
#
# You should have received a copy of the GNU Lesser General Public License
# along with PyFarm.  If not, see <http://www.gnu.org/licenses/>.

# NOTE: not all values are required to be populated, port and driver for example
#       will be defined my sqlalchemy if they are not provided.
database:
  host:   # hostname to connect to
  port:   # port the master is running on
  user:   # username to connect with
  pass:   # password to connect with
  name:   # name of database
  engine: # type of engine (mysql, postgresql, etc)
  driver: # specifies the python module to connect with

db-vmdb:
  host: localhost
  port: 9999
  user: someuser
  pass: somepass
  name: pyfarm
  driver: psycopg2ct
  engine: psycopg2

# example sqlite db to be used for local testing *only*
db-sqlite:
  host: /tmp/pyfarm.sql
  host: ':memory:'
  engine: sqlite

setup:
  # list of possible configs to use, first db which we can connect without
  # raising an error will be be used in all future connections
  configs:
    testing:
     - db-sqlite             # name of the configuration to use
     - db-vmdb
     - foo
    production:
     - db-vmdb
  rebuild: false           # if true then we drop any existing tables
  close-connections: true  # if true we attempt to close every connection made
