postgres:
   host: bbot-database-postgres-01
   database: buildbot_pyfarm
   username: buildbot_pyfarm
   password: pr9kedrugUsecrudruphephabesawresaspebruVupaPuruQacrUzEnecREspaxu
   engine: postgresql
   driver: psycopg2

configs:
  unittest: postgres

config_order:
  - unittest

setup:
  rebuild: false
  close-connections: false
