# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\opalmer\Desktop\PyFarm\testing\proto1\QtDesigner\Proto1.ui'
#
# Created: Mon Dec 22 21:26:39 2008
#      by: PyQt4 UI code generator 4.4.3
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

class Ui_Proto1(object):
    def setupUi(self, Proto1):
        Proto1.setObjectName("Proto1")
        Proto1.resize(390, 300)
        Proto1.setMinimumSize(QtCore.QSize(390, 300))
        Proto1.setMaximumSize(QtCore.QSize(390, 300))
        self.widget = QtGui.QWidget(Proto1)
        self.widget.setGeometry(QtCore.QRect(10, 10, 371, 281))
        self.widget.setObjectName("widget")
        self.gridLayout = QtGui.QGridLayout(self.widget)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtGui.QLabel(self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.sceneEntry = QtGui.QLineEdit(self.widget)
        self.sceneEntry.setObjectName("sceneEntry")
        self.horizontalLayout.addWidget(self.sceneEntry)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtGui.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sFrameBox = QtGui.QSpinBox(self.widget)
        self.sFrameBox.setMinimum(1)
        self.sFrameBox.setMaximum(999999999)
        self.sFrameBox.setObjectName("sFrameBox")
        self.horizontalLayout_2.addWidget(self.sFrameBox)
        self.label_3 = QtGui.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.eFrameBox = QtGui.QSpinBox(self.widget)
        self.eFrameBox.setMinimum(1)
        self.eFrameBox.setMaximum(999999999)
        self.eFrameBox.setObjectName("eFrameBox")
        self.horizontalLayout_2.addWidget(self.eFrameBox)
        self.findNodesButton = QtGui.QPushButton(self.widget)
        self.findNodesButton.setObjectName("findNodesButton")
        self.horizontalLayout_2.addWidget(self.findNodesButton)
        self.gridLayout.addLayout(self.horizontalLayout_2, 1, 0, 1, 1)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.nodeTable = QtGui.QTableWidget(self.widget)
        self.nodeTable.setObjectName("nodeTable")
        self.nodeTable.setColumnCount(2)
        self.nodeTable.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.nodeTable.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.nodeTable.setHorizontalHeaderItem(1, item)
        self.horizontalLayout_3.addWidget(self.nodeTable)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.aboutButton = QtGui.QPushButton(self.widget)
        self.aboutButton.setObjectName("aboutButton")
        self.verticalLayout.addWidget(self.aboutButton)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.renderButton = QtGui.QPushButton(self.widget)
        self.renderButton.setObjectName("renderButton")
        self.verticalLayout.addWidget(self.renderButton)
        spacerItem1 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.quitButton = QtGui.QPushButton(self.widget)
        self.quitButton.setObjectName("quitButton")
        self.verticalLayout.addWidget(self.quitButton)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 1)
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtGui.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.progressBar = QtGui.QProgressBar(self.widget)
        self.progressBar.setProperty("value", QtCore.QVariant(0))
        self.progressBar.setObjectName("progressBar")
        self.horizontalLayout_4.addWidget(self.progressBar)
        self.gridLayout.addLayout(self.horizontalLayout_4, 3, 0, 1, 1)

        self.retranslateUi(Proto1)
        QtCore.QObject.connect(self.quitButton, QtCore.SIGNAL("clicked()"), Proto1.close)
        QtCore.QMetaObject.connectSlotsByName(Proto1)

    def retranslateUi(self, Proto1):
        Proto1.setWindowTitle(QtGui.QApplication.translate("Proto1", "PyFarm -- Prototype  1", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("Proto1", "Scene:", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("Proto1", "Start Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.label_3.setText(QtGui.QApplication.translate("Proto1", "End Frame", None, QtGui.QApplication.UnicodeUTF8))
        self.findNodesButton.setText(QtGui.QApplication.translate("Proto1", "Find Nodes", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTable.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("Proto1", "Hostname", None, QtGui.QApplication.UnicodeUTF8))
        self.nodeTable.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("Proto1", "IP Address", None, QtGui.QApplication.UnicodeUTF8))
        self.aboutButton.setText(QtGui.QApplication.translate("Proto1", "About", None, QtGui.QApplication.UnicodeUTF8))
        self.renderButton.setText(QtGui.QApplication.translate("Proto1", "Render", None, QtGui.QApplication.UnicodeUTF8))
        self.quitButton.setText(QtGui.QApplication.translate("Proto1", "Quit", None, QtGui.QApplication.UnicodeUTF8))
        self.label_4.setText(QtGui.QApplication.translate("Proto1", "Progress", None, QtGui.QApplication.UnicodeUTF8))

