#!/usr/bin/env python
'''
PURPOSE [FOR DEVELOPMENT PURPOSES ONLY]:
    This file is part of PyFarm.
    Copyright (C) 2008-2012 Oliver Palmer

    PyFarm is free software: you can redistribute it and/or modify
    it under the terms of the GNU Lesser General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    PyFarm is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU Lesser General Public License for more details.

    You should have received a copy of the GNU Lesser General Public License
    along with PyFarm.  If not, see <http://www.gnu.org/licenses/>.
'''

import os
import sys

# diff is called by git with 7 parameters:
# path old-file old-hex old-mode new-file new-hex new-mode

# how to setup:
# git config --global diff.external <path_to_wrapper_script>

if os.name == "posix":
    cmd = "xxdiff %s %s" % (sys.argv[2], sys.argv[5])
    print "Running: %s" % cmd
    os.system(cmd)

else:
    print "git2diff not wrapped for %s" % os.name