#!/bin/bash

ID_RSA="/home/opalmer/.ssh/id_rsa_insecure"
HOSTS=`cat ./hostlist`

ssh -i $ID_RSA render@pyroot "sudo aptitude update"
ssh -i $ID_RSA render@pyroot "sudo aptitude -y safe-upgrade"
	
for host in $HOSTS; do
	ssh -i $ID_RSA render@$host "sudo aptitude update"
	ssh -i $ID_RSA render@$host "sudo aptitude -y safe-upgrade"
done
